CREATE PROCEDURE [dbo].[GetClinicNames20120815]
(
	@DMISID bigint
)
AS
	SET NOCOUNT ON;
SELECT 	HOSPITAL_LOCATION.HospitalLocationId, HOSPITAL_LOCATION.HospitalLocationName 
FROM 		HOSPITAL_LOCATION INNER JOIN MEPRS_CODE ON HOSPITAL_LOCATION.MeprsCodeId = MEPRS_CODE.MeprsCodeId 
WHERE 	(MEPRS_CODE.DmisId = @DMISID)
		AND NOT (MEPRSCODE LIKE 'A%' OR MEPRSCODE LIKE 'E%' OR MEPRSCODE LIKE 'D%' 
			     OR MEPRSCODE LIKE 'C%' OR MEPRSCODE LIKE '%5')
ORDER BY HOSPITAL_LOCATION.HospitalLocationName;