
CREATE PROCEDURE [dbo].[procCP_PATIENT_FLAG_DIABETIC]

AS
BEGIN	
	SET NOCOUNT ON;
	
	INSERT INTO PATIENT_FLAG
	(
		PatientId,
		FlagId,
		SourceSystemId
	)
	SELECT DISTINCT 
		PE.PatientId, 
		2 AS FlagId,
		2 AS SourceSystemId
	FROM PATIENT_ENCOUNTER AS PE 
		INNER JOIN ENCOUNTER_DIAGNOSIS AS ED 
		ON PE.PatientEncounterId = ED.PatientEncounterId 
		INNER JOIN PATIENT P 
		ON P.PATIENTID = PE.PATIENTID
	WHERE (ED.DiagnosisId IN 
		(
			SELECT ICDId
			FROM FLAG_ICD
			WHERE FlagId = 2
		)) --TESTS FOR DIABETES DIAGNOSIS
		and (ED.DiagnosisId NOT IN 
		(
			1193,1217,6695
			--OTHER SPECIFIED DISORDERS OF PANCREATIC INTERNAL SECRETION,
			--POLYCYSTIC OVARIES'
			--POISONING BY ADRENAL CORTICAL STEROIDS
		)) -- EXCLUDED DIAGNOSES
		
	--tests for death codes
		
		AND P.PatientDeceased = 0
	UNION
	SELECT 
		P.PatientId, 
		2 AS FlagId,
		6 AS SourceSystemId
	FROM vwMDE_PATIENT AS PAT  
		INNER JOIN vwSTG_POP_HEALTH_DIABETES AS DIA 
		ON PAT.PATIENT_IDENTIFIER = DIA.EDIPN 
		INNER JOIN PATIENT P 
		ON PAT.KEY_PATIENT = P.PatientKey
	WHERE P.PATIENTID IN 
		(
			SELECT PATIENTID 
			FROM PRIMARY_CARE_MANAGER
		)
	
		AND P.PatientDeceased = 0
END
