CREATE PROCEDURE dbo.upLog
(
	@logDescription	varchar(4000)
)
AS
	BEGIN TRANSACTION
	PRINT 'INSERT INTO ACTIVITY_LOG'
INSERT INTO ACTIVITY_LOG (
LogDescription) 
VALUES(@logDescription);
	COMMIT TRANSACTION
