CREATE LOGIN [PORTAL]
    WITH PASSWORD = N'IRFf;AX{Qr@xgmf_xgqlyt<smsFT7_&#$!~<q}o0gbuXj:nr', SID = 0xCB3B9F60C053284A8DBEFEDC8AED68E4, DEFAULT_DATABASE = [CLINICAL_PORTAL], DEFAULT_LANGUAGE = [us_english];

