CREATE TABLE [dbo].[ACCESS_TO_CARE_CATEGORY] (
    [KEY_SITE]                    NUMERIC (5)     NULL,
    [KEY_ACCESS_TO_CARE_CATEGORY] NUMERIC (7, 3)  NULL,
    [NAME]                        VARCHAR (30)    NULL,
    [STANDARD]                    NUMERIC (10, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ACCESS_TO_CARE_CATEGORY_KEY_ACCESS_TO_CARE_CATEGORY]
    ON [dbo].[ACCESS_TO_CARE_CATEGORY]([KEY_ACCESS_TO_CARE_CATEGORY] ASC) WITH (FILLFACTOR = 100);

