CREATE TABLE [dbo].[ACCESSION] (
    [KEY_SITE]                   NUMERIC (5)     NULL,
    [KEY_ACCESSION]              NUMERIC (14, 3) NULL,
    [ACCESSION_NUMBER]           NUMERIC (15, 3) NULL,
    [PATIENT_IEN]                NUMERIC (21, 3) NULL,
    [ORDER_DATE]                 DATETIME        NULL,
    [COLLECTION_DATE_TIME]       DATETIME        NULL,
    [ACCESSION_DATE]             DATETIME        NULL,
    [LAB_ARRIVAL_TIME]           DATETIME        NULL,
    [LOGGED_IN_WORK_ELEMENT_IEN] NUMERIC (21, 3) NULL,
    [COLLECTION_SAMPLE_IEN]      NUMERIC (21, 3) NULL,
    [REQUESTION_LOCATION_IEN]    NUMERIC (22, 4) NULL,
    [CURRENT_ACCESSION_NAME]     VARCHAR (17)    NULL,
    [CURRENT_ACCESSION_AREA_IEN] NUMERIC (21, 3) NULL,
    [COPATH_SPECIMEN_NUMBER]     VARCHAR (50)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_ACCESSION]
    ON [dbo].[ACCESSION]([KEY_SITE] ASC, [KEY_ACCESSION] ASC);

