CREATE TABLE [dbo].[ACCESSION$ACCESSION_NAME] (
    [KEY_SITE]                     NUMERIC (5)     NULL,
    [KEY_ACCESSION]                NUMERIC (14, 3) NULL,
    [KEY_ACCESSION$ACCESSION_NAME] NUMERIC (7, 3)  NULL,
    [ACCESSION_NAME]               VARCHAR (17)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_ACCESSION$ACCESSION_NAME]
    ON [dbo].[ACCESSION$ACCESSION_NAME]([KEY_SITE] ASC, [KEY_ACCESSION] ASC, [KEY_ACCESSION$ACCESSION_NAME] ASC);

