CREATE TABLE [dbo].[ACCESSION$TEST_ORDERED] (
    [KEY_SITE]                   NUMERIC (5)     NULL,
    [KEY_ACCESSION]              NUMERIC (14, 3) NULL,
    [KEY_ACCESSION$TEST_ORDERED] NUMERIC (10, 3) NULL,
    [TEST_ORDERED_IEN]           NUMERIC (21, 3) NULL,
    [ORDER_TASK_IEN]             NUMERIC (21, 3) NULL,
    [ORDER_REFERENCE_IEN]        NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_ACCESSION$TEST_ORDERED]
    ON [dbo].[ACCESSION$TEST_ORDERED]([KEY_SITE] ASC, [KEY_ACCESSION] ASC, [KEY_ACCESSION$TEST_ORDERED] ASC);

