CREATE TABLE [dbo].[ACCESSION_AREA] (
    [KEY_SITE]           NUMERIC (5)    NULL,
    [KEY_ACCESSION_AREA] NUMERIC (9, 3) NULL,
    [AREA]               VARCHAR (20)   NULL,
    [LR_SUBSCRIPT]       VARCHAR (30)   NULL,
    [ABBREVIATION]       VARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ACCESSION_AREA_KEY_ACCESSION_AREA]
    ON [dbo].[ACCESSION_AREA]([KEY_ACCESSION_AREA] ASC) WITH (FILLFACTOR = 100);

