CREATE TABLE [dbo].[ALLERGIES_DEFINITIONS] (
    [KEY_SITE]                  NUMERIC (5)     NULL,
    [KEY_ALLERGIES_DEFINITIONS] NUMERIC (13, 3) NULL,
    [ALLERGY_NAME_GNN]          VARCHAR (50)    NULL
);


GO
CREATE CLUSTERED INDEX [IX_ALLERGIES_DEFINITIONS_KEY_ALLERGIES_DEFINITIONS]
    ON [dbo].[ALLERGIES_DEFINITIONS]([KEY_ALLERGIES_DEFINITIONS] ASC) WITH (FILLFACTOR = 100);

