CREATE TABLE [dbo].[ANCILLARY_PROCEDURE] (
    [KEY_SITE]                NUMERIC (5)     NULL,
    [KEY_ANCILLARY_PROCEDURE] NUMERIC (10, 3) NULL,
    [NAME]                    VARCHAR (30)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_ANCILLARY_PROCEDURE]
    ON [dbo].[ANCILLARY_PROCEDURE]([KEY_SITE] ASC, [KEY_ANCILLARY_PROCEDURE] ASC);

