CREATE TABLE [dbo].[AP_DESCRIPTION_DIAGNOSIS] (
    [KEY_SITE]                     NUMERIC (5)    NULL,
    [KEY_AP_DESCRIPTION_DIAGNOSIS] NUMERIC (9, 3) NULL,
    [CODE]                         VARCHAR (70)   NULL,
    [NAME]                         VARCHAR (70)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_AP_DESCRIPTION_DIAGNOSIS_KEY_AP_DESCRIPTION_DIAGNOSIS]
    ON [dbo].[AP_DESCRIPTION_DIAGNOSIS]([KEY_AP_DESCRIPTION_DIAGNOSIS] ASC) WITH (FILLFACTOR = 100);

