CREATE TABLE [dbo].[APPOINTMENT_STATUS] (
    [KEY_SITE]               NUMERIC (5)     NULL,
    [KEY_APPOINTMENT_STATUS] NUMERIC (8, 3)  NULL,
    [NUMBER_]                NUMERIC (10, 3) NULL,
    [APPOINTMENT_STATUS]     VARCHAR (30)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_APPOINTMENT_STATUS_KEY_APPOINTMENT_STATUS]
    ON [dbo].[APPOINTMENT_STATUS]([KEY_APPOINTMENT_STATUS] ASC) WITH (FILLFACTOR = 100);

