CREATE TABLE [dbo].[APPOINTMENT_DETAIL_CODES] (
    [KEY_SITE]                     NUMERIC (5)    NULL,
    [KEY_APPOINTMENT_DETAIL_CODES] NUMERIC (9, 3) NULL,
    [CODE]                         VARCHAR (8)    NULL,
    [DESCRIPTION]                  VARCHAR (75)   NULL,
    [STATUS]                       VARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_APPOINTMENT_DETAIL_CODES_KEY_APPOINTMENT_DETAIL_CODES]
    ON [dbo].[APPOINTMENT_DETAIL_CODES]([KEY_APPOINTMENT_DETAIL_CODES] ASC) WITH (FILLFACTOR = 100);

