CREATE TABLE [dbo].[BORROWERS_FILE_AREAS] (
    [KEY_SITE]                 NUMERIC (5)     NULL,
    [KEY_BORROWERS_FILE_AREAS] NUMERIC (15, 3) NULL,
    [NUMBER_]                  NUMERIC (15, 3) NULL,
    [NAME]                     VARCHAR (45)    NULL,
    [NAME_IEN]                 VARCHAR (16)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_BORROWERS_FILE_AREAS_KEY_BORROWERS_FILE_AREAS]
    ON [dbo].[BORROWERS_FILE_AREAS]([KEY_BORROWERS_FILE_AREAS] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_BORROWERS_FILE_AREAS_NUMBER_]
    ON [dbo].[BORROWERS_FILE_AREAS]([NUMBER_] ASC) WITH (FILLFACTOR = 100);

