CREATE TABLE [dbo].[BRANCH_OF_SERVICE] (
    [KEY_SITE]              NUMERIC (5)    NULL,
    [KEY_BRANCH_OF_SERVICE] NUMERIC (8, 3) NULL,
    [NAME]                  VARCHAR (36)   NULL,
    [CODE]                  VARCHAR (3)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_BRANCH_OF_SERVICE_KEY_BRANCH_OF_SERVICE]
    ON [dbo].[BRANCH_OF_SERVICE]([KEY_BRANCH_OF_SERVICE] ASC) WITH (FILLFACTOR = 100);

