CREATE TABLE [dbo].[CLINICAL_HISTORY$DRUG_ALLERGY] (
    [KEY_SITE]                          NUMERIC (5)     NULL,
    [KEY_CLINICAL_HISTORY]              NUMERIC (13, 3) NULL,
    [KEY_CLINICAL_HISTORY$DRUG_ALLERGY] NUMERIC (9, 3)  NULL,
    [ALLERGY_SELECTION_IEN]             NUMERIC (21, 3) NULL,
    [COMMENT_]                          VARCHAR (150)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_CLINICAL_HISTORY$DRUG_ALLERGY]
    ON [dbo].[CLINICAL_HISTORY$DRUG_ALLERGY]([KEY_SITE] ASC, [KEY_CLINICAL_HISTORY] ASC, [KEY_CLINICAL_HISTORY$DRUG_ALLERGY] ASC);

