CREATE TABLE [dbo].[CLINICAL_HISTORY] (
    [KEY_SITE]             NUMERIC (5)     NULL,
    [KEY_CLINICAL_HISTORY] NUMERIC (13, 3) NULL,
    [NAME_IEN]             NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_CLINICAL_HISTORY]
    ON [dbo].[CLINICAL_HISTORY]([KEY_SITE] ASC, [KEY_CLINICAL_HISTORY] ASC);

