CREATE TABLE [dbo].[CO_INSURANCE_CLAIM] (
    [KEY_SITE]                     NUMERIC (5)     NULL,
    [KEY_CO_INSURANCE_CLAIM]       NUMERIC (12, 3) NULL,
    [ACCOUNT_NUMBER_IEN]           NUMERIC (21, 3) NULL,
    [DIVISION_IEN]                 NUMERIC (21, 3) NULL,
    [PATIENT_IEN]                  NUMERIC (21, 3) NULL,
    [CURRENT_INSURANCE_POLICY_IEN] NUMERIC (21, 3) NULL,
    [ACCOUNT_STATUS_DATE]          DATETIME        NULL,
    [REASON_FOR_CLOSE_ACCOUNT_IEN] NUMERIC (21, 3) NULL,
    [ACCOUNT_STATUS]               VARCHAR (30)    NULL,
    [COVERAGE_TYPE_CODE_IEN]       NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_CO_INSURANCE_CLAIM]
    ON [dbo].[CO_INSURANCE_CLAIM]([KEY_SITE] ASC, [KEY_CO_INSURANCE_CLAIM] ASC);

