CREATE TABLE [dbo].[CPT_HCPCS] (
    [KEY_SITE]      NUMERIC (5)     NULL,
    [KEY_CPT_HCPCS] NUMERIC (11, 3) NULL,
    [CODE]          VARCHAR (30)    NULL,
    [DESCRIPTION]   VARCHAR (30)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_CPT_HCPCS]
    ON [dbo].[CPT_HCPCS]([KEY_SITE] ASC, [KEY_CPT_HCPCS] ASC);

