CREATE TABLE [dbo].[DEERS_SPONSOR_STATUS] (
    [KEY_SITE]                 NUMERIC (5)    NULL,
    [KEY_DEERS_SPONSOR_STATUS] NUMERIC (8, 3) NULL,
    [DEERS_SPONSOR_STATUS]     VARCHAR (1)    NULL,
    [DESCRIPTION]              VARCHAR (25)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_DEERS_SPONSOR_STATUS]
    ON [dbo].[DEERS_SPONSOR_STATUS]([KEY_SITE] ASC, [KEY_DEERS_SPONSOR_STATUS] ASC);

