CREATE TABLE [dbo].[DEERS_PATIENT_INQUIRY_RESPONSE$CONTACT_INFORMATION] (
    [KEY_SITE]                                           NUMERIC (5)     NULL,
    [KEY_DEERS_PATIENT_INQUIRY_RESPONSE]                 NUMERIC (12, 3) NULL,
    [KEY_DEERS_PATIENT_INQUIRY_RESPONSE$CONTACT_INFORMA] NUMERIC (7, 3)  NULL,
    [CONTACT_RELATIONSHIP_TYPE]                          VARCHAR (30)    NULL,
    [CONTACT_LAST_NAME]                                  VARCHAR (26)    NULL,
    [CONTACT_FIRST_NAME]                                 VARCHAR (20)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_DEERS_PATIENT_INQUIRY_RESPONSE$CONTACT_INFORMATION]
    ON [dbo].[DEERS_PATIENT_INQUIRY_RESPONSE$CONTACT_INFORMATION]([KEY_SITE] ASC, [KEY_DEERS_PATIENT_INQUIRY_RESPONSE] ASC, [KEY_DEERS_PATIENT_INQUIRY_RESPONSE$CONTACT_INFORMA] ASC);

