CREATE TABLE [dbo].[DEERS_EXCEPTIONS] (
    [KEY_SITE]             NUMERIC (5)     NULL,
    [KEY_DEERS_EXCEPTIONS] NUMERIC (13, 3) NULL,
    [PATIENT_IEN]          NUMERIC (21, 3) NULL,
    [DATE_ADDED_TO_FILE]   DATETIME        NULL,
    [PATIENT_NAME]         VARCHAR (30)    NULL,
    [DISCREPANCY_REASON]   VARCHAR (200)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_DEERS_EXCEPTIONS]
    ON [dbo].[DEERS_EXCEPTIONS]([KEY_SITE] ASC, [KEY_DEERS_EXCEPTIONS] ASC);

