CREATE TABLE [dbo].[DEERS_PATIENT_INQUIRY_RESPO$OTHER_HEALTH_INSURANCE] (
    [KEY_SITE]                                           NUMERIC (5)     NULL,
    [KEY_DEERS_PATIENT_INQUIRY_RESPONSE]                 VARCHAR (1)     NULL,
    [KEY_DEERS_PATIENT_INQUIRY_RESPO$OTHER_HEALTH_INSUR] VARCHAR (1)     NULL,
    [POLICY_IDENTIFIER]                                  VARCHAR (20)    NULL,
    [INSURANCE_TYPE_CODE_IEN]                            NUMERIC (21, 3) NULL,
    [OHI_TRANSACTION_SYSTEM_ID]                          VARCHAR (7)     NULL,
    [OHI_EFFECTIVE_DATE]                                 DATETIME        NULL,
    [OHI_EXPIRATION_DATE]                                DATETIME        NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_DEERS_PATIENT_INQUIRY_RESPO$OTHER_HEALTH_INSURANCE]
    ON [dbo].[DEERS_PATIENT_INQUIRY_RESPO$OTHER_HEALTH_INSURANCE]([KEY_SITE] ASC, [KEY_DEERS_PATIENT_INQUIRY_RESPONSE] ASC, [KEY_DEERS_PATIENT_INQUIRY_RESPO$OTHER_HEALTH_INSUR] ASC);

