CREATE TABLE [dbo].[DEERS_PATIENT$OTHER_HEALTH_$OHI_COVERAGE_TYPE_CODE] (
    [KEY_SITE]                                           NUMERIC (5)  NULL,
    [KEY_DEERS_PATIENT_INQUIRY_RESPONSE]                 VARCHAR (1)  NULL,
    [KEY_DEERS_PATIENT$OTHER_HEALTH_$OHI_COVERAGE_TYPE_] VARCHAR (1)  NULL,
    [KEY_DEERS_PATIENT_INQUIRY_RESPO$OTHER_HEALTH_INSUR] VARCHAR (1)  NULL,
    [OHI_COVERAGE_TYPE_CODE]                             VARCHAR (30) NULL,
    [PAYER_TYPE_CODE]                                    VARCHAR (30) NULL,
    [COVERAGE_TRANSACTION_SYSTEM_ID]                     VARCHAR (7)  NULL,
    [COVERAGE_TRANSACTION_DATE]                          DATETIME     NULL,
    [COVERAGE_EFFECTIVE_DATE]                            DATETIME     NULL,
    [COVERAGE_EXPIRATION_DATE]                           DATETIME     NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_DEERS_PATIENT$OTHER_HEALTH_$OHI_COVERAGE_TYPE_CODE]
    ON [dbo].[DEERS_PATIENT$OTHER_HEALTH_$OHI_COVERAGE_TYPE_CODE]([KEY_SITE] ASC, [KEY_DEERS_PATIENT_INQUIRY_RESPONSE] ASC, [KEY_DEERS_PATIENT$OTHER_HEALTH_$OHI_COVERAGE_TYPE_] ASC, [KEY_DEERS_PATIENT_INQUIRY_RESPO$OTHER_HEALTH_INSUR] ASC);

