CREATE TABLE [dbo].[DIAGNOSTIC_RELATED_GROUP] (
    [KEY_SITE]                     NUMERIC (5)     NULL,
    [KEY_DIAGNOSTIC_RELATED_GROUP] NUMERIC (9, 3)  NULL,
    [DRG_CODE]                     VARCHAR (3)     NULL,
    [DRG_DESCRIPTION]              VARCHAR (64)    NULL,
    [RELATIVE_WEIGHT]              NUMERIC (18, 7) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_DIAGNOSTIC_RELATED_GROUP_KEY_DIAGNOSTIC_RELATED_GROUP]
    ON [dbo].[DIAGNOSTIC_RELATED_GROUP]([KEY_DIAGNOSTIC_RELATED_GROUP] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_DIAGNOSTIC_RELATED_GROUP_DRG_CODE]
    ON [dbo].[DIAGNOSTIC_RELATED_GROUP]([DRG_CODE] ASC) WITH (FILLFACTOR = 100);

