CREATE TABLE [dbo].[DMIS_ID_CODES] (
    [KEY_SITE]          NUMERIC (5)     NULL,
    [KEY_DMIS_ID_CODES] NUMERIC (10, 3) NULL,
    [DMIS_ID]           VARCHAR (30)    NULL,
    [FACILITY_NAME]     VARCHAR (50)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_DMIS_ID_CODES_KEY_DMIS_ID_CODES]
    ON [dbo].[DMIS_ID_CODES]([KEY_DMIS_ID_CODES] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_DMIS_ID_CODES_DMIS_ID]
    ON [dbo].[DMIS_ID_CODES]([DMIS_ID] ASC) WITH (FILLFACTOR = 100);

