CREATE TABLE [dbo].[DRUG_NAME_ROUTE] (
    [KEY_SITE]            NUMERIC (5)    NULL,
    [KEY_DRUG_NAME_ROUTE] NUMERIC (8, 3) NULL,
    [NAME]                VARCHAR (5)    NULL,
    [DESCRIPTION]         VARCHAR (30)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_DRUG_NAME_ROUTE]
    ON [dbo].[DRUG_NAME_ROUTE]([KEY_SITE] ASC, [KEY_DRUG_NAME_ROUTE] ASC);

