CREATE TABLE [dbo].[ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS] (
    [KEY_SITE]                                       NUMERIC (5)     NULL,
    [KEY_ENCOUNTER]                                  NUMERIC (13, 3) NULL,
    [KEY_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS] NUMERIC (7, 3)  NULL,
    [KEY_ENCOUNTER$ICD_OPERATIONS_PROCEDURES]        NUMERIC (8, 3)  NULL,
    [ASSISTING_HCPS_IEN]                             NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS_KEY_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS]
    ON [dbo].[ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS]([KEY_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS] ASC) WITH (FILLFACTOR = 100);

