CREATE TABLE [dbo].[ENCOUNTER$DIAGNOSIS] (
    [KEY_SITE]                NUMERIC (5)     NULL,
    [KEY_ENCOUNTER]           NUMERIC (13, 3) NULL,
    [KEY_ENCOUNTER$DIAGNOSIS] NUMERIC (8, 3)  NULL,
    [DIAGNOSIS_IEN]           NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_ENCOUNTER$DIAGNOSIS]
    ON [dbo].[ENCOUNTER$DIAGNOSIS]([KEY_SITE] ASC, [KEY_ENCOUNTER] ASC, [KEY_ENCOUNTER$DIAGNOSIS] ASC);

