CREATE TABLE [dbo].[ENCOUNTER] (
    [KEY_SITE]                NUMERIC (5)     NULL,
    [KEY_ENCOUNTER]           NUMERIC (13, 3) NULL,
    [DATE_TIME]               DATETIME        NULL,
    [PATIENT_IEN]             NUMERIC (21, 3) NULL,
    [PROVIDER_IEN]            NUMERIC (21, 3) NULL,
    [HOSPITAL_LOCATION_IEN]   NUMERIC (21, 3) NULL,
    [TYPE_]                   VARCHAR (30)    NULL,
    [ADMISSION_ENTRY]         NUMERIC (10, 3) NULL,
    [ADMISSION_DATE]          DATETIME        NULL,
    [DISCHARGE_DATE]          DATETIME        NULL,
    [ADMISSION_DATE__FORMAT_] VARCHAR (16)    NULL,
    [CHIEF_COMPLAINT]         VARCHAR (60)    NULL,
    [PRIMARY_DIAGNOSIS_IEN]   NUMERIC (21, 3) NULL,
    [RELATED_ENCOUNTER_IEN]   NUMERIC (21, 3) NULL,
    [DISPOSITION]             VARCHAR (30)    NULL,
    [PAT_APPT_ENTRY_PTR_IEN]  NUMERIC (21, 3) NULL,
    [RESTRAINT_INDICATOR]     VARCHAR (30)    NULL,
    [DRG_CODE_IEN]            NUMERIC (21, 3) NULL,
    [MDC_CODE_IEN]            NUMERIC (21, 3) NULL,
    [DIVISION_IEN]            NUMERIC (21, 3) NULL,
    [ER_COMMENT]              VARCHAR (40)    NULL,
    [SERVICE_IEN]             NUMERIC (21, 3) NULL,
    [MEPRS_CODE_IEN]          NUMERIC (21, 3) NULL,
    [APPOINTMENT_TYPE_IEN]    NUMERIC (21, 3) NULL,
    [STATUS]                  VARCHAR (30)    NULL
);


GO
CREATE CLUSTERED INDEX [IX_ENCOUNTER_DATE_TIME]
    ON [dbo].[ENCOUNTER]([DATE_TIME] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ENCOUNTER_KEY_ENCOUNTER]
    ON [dbo].[ENCOUNTER]([KEY_ENCOUNTER] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ENCOUNTER_PATIENT_IEN]
    ON [dbo].[ENCOUNTER]([PATIENT_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ENCOUNTER_PROVIDER_IEN]
    ON [dbo].[ENCOUNTER]([PROVIDER_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ENCOUNTER_DRG_CODE_IEN]
    ON [dbo].[ENCOUNTER]([DRG_CODE_IEN] ASC) WITH (FILLFACTOR = 100);

