CREATE TABLE [dbo].[ENCOUNTER$DIAGNOSIS__FREE_TEXT_] (
    [KEY_SITE]                            NUMERIC (5)     NULL,
    [KEY_ENCOUNTER]                       NUMERIC (13, 3) NULL,
    [KEY_ENCOUNTER$DIAGNOSIS__FREE_TEXT_] NUMERIC (8, 3)  NULL,
    [DIAGNOSIS__FREE_TEXT_]               VARCHAR (60)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ENCOUNTER$DIAGNOSIS__FREE_TEXT__KEY_ENCOUNTER$DIAGNOSIS__FREE_TEXT_]
    ON [dbo].[ENCOUNTER$DIAGNOSIS__FREE_TEXT_]([KEY_ENCOUNTER$DIAGNOSIS__FREE_TEXT_] ASC) WITH (FILLFACTOR = 100);

