CREATE TABLE [dbo].[ETIOLOGY_FIELD] (
    [KEY_SITE]           NUMERIC (5)     NULL,
    [KEY_ETIOLOGY_FIELD] NUMERIC (12, 3) NULL,
    [NAME]               VARCHAR (70)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ETIOLOGY_FIELD_KEY_ETIOLOGY_FIELD]
    ON [dbo].[ETIOLOGY_FIELD]([KEY_ETIOLOGY_FIELD] ASC) WITH (FILLFACTOR = 100);

