CREATE TABLE [dbo].[EXAMINATION_STATUS] (
    [KEY_SITE]               NUMERIC (5)    NULL,
    [KEY_EXAMINATION_STATUS] NUMERIC (8, 3) NULL,
    [STATUS]                 VARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_EXAMINATION_STATUS_KEY_EXAMINATION_STATUS]
    ON [dbo].[EXAMINATION_STATUS]([KEY_EXAMINATION_STATUS] ASC) WITH (FILLFACTOR = 100);

