CREATE TABLE [dbo].[FAMILY_MEMBER_PREFIX] (
    [KEY_SITE]                 NUMERIC (5)    NULL,
    [KEY_FAMILY_MEMBER_PREFIX] NUMERIC (8, 3) NULL,
    [NUMBER_]                  NUMERIC (9, 3) NULL,
    [FMP]                      VARCHAR (30)   NULL,
    [DESCRIPTION]              VARCHAR (50)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_FAMILY_MEMBER_PREFIX_KEY_FAMILY_MEMBER_PREFIX]
    ON [dbo].[FAMILY_MEMBER_PREFIX]([KEY_FAMILY_MEMBER_PREFIX] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_FAMILY_MEMBER_PREFIX_NUMBER_]
    ON [dbo].[FAMILY_MEMBER_PREFIX]([NUMBER_] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_FAMILY_MEMBER_PREFIX_FMP]
    ON [dbo].[FAMILY_MEMBER_PREFIX]([FMP] ASC) WITH (FILLFACTOR = 100);

