CREATE TABLE [dbo].[FORMULARY_GROUP] (
    [KEY_SITE]            NUMERIC (5)    NULL,
    [KEY_FORMULARY_GROUP] NUMERIC (8, 3) NULL,
    [NAME]                VARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_FORMULARY_GROUP_KEY_FORMULARY_GROUP]
    ON [dbo].[FORMULARY_GROUP]([KEY_FORMULARY_GROUP] ASC) WITH (FILLFACTOR = 100);

