CREATE TABLE [dbo].[HEALTH_INSURANCE_CARRIER] (
    [KEY_SITE]                     NUMERIC (5)     NULL,
    [KEY_HEALTH_INSURANCE_CARRIER] NUMERIC (11, 3) NULL,
    [CARRIER_NAME]                 VARCHAR (35)    NULL,
    [CARRIER_IDENTIFIER]           VARCHAR (11)    NULL,
    [CARRIER_STATUS_CODE_IEN]      NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_HEALTH_INSURANCE_CARRIER]
    ON [dbo].[HEALTH_INSURANCE_CARRIER]([KEY_SITE] ASC, [KEY_HEALTH_INSURANCE_CARRIER] ASC);

