CREATE TABLE [dbo].[HOSPITAL_LOCATION$CLINIC_SPECIALTY] (
    [KEY_SITE]                               NUMERIC (5)     NULL,
    [KEY_HOSPITAL_LOCATION]                  NUMERIC (11, 3) NULL,
    [KEY_HOSPITAL_LOCATION$CLINIC_SPECIALTY] NUMERIC (9, 3)  NULL,
    [CLINIC_SPECIALTY_IEN]                   NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_HOSPITAL_LOCATION$CLINIC_SPECIALTY]
    ON [dbo].[HOSPITAL_LOCATION$CLINIC_SPECIALTY]([KEY_SITE] ASC, [KEY_HOSPITAL_LOCATION] ASC, [KEY_HOSPITAL_LOCATION$CLINIC_SPECIALTY] ASC);

