CREATE TABLE [dbo].[ICD_OPERATION_PROCEDURE] (
    [KEY_SITE]                    NUMERIC (5)     NULL,
    [KEY_ICD_OPERATION_PROCEDURE] NUMERIC (11, 3) NULL,
    [CODE_NUMBER]                 VARCHAR (30)    NULL,
    [DESCRIPTION]                 VARCHAR (250)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_ICD_OPERATION_PROCEDURE]
    ON [dbo].[ICD_OPERATION_PROCEDURE]([KEY_SITE] ASC, [KEY_ICD_OPERATION_PROCEDURE] ASC);

