CREATE TABLE [dbo].[IMAGING_TYPE] (
    [KEY_SITE]             NUMERIC (5)    NULL,
    [KEY_IMAGING_TYPE]     NUMERIC (8, 3) NULL,
    [TYPE_OF_IMAGING]      VARCHAR (30)   NULL,
    [ABBREVIATION]         VARCHAR (4)    NULL,
    [OPERATING_CONDITIONS] VARCHAR (30)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_IMAGING_TYPE]
    ON [dbo].[IMAGING_TYPE]([KEY_SITE] ASC, [KEY_IMAGING_TYPE] ASC);

