CREATE TABLE [dbo].[IMMUNIZATION_EVENTS$VACCINE_REACTIONS] (
    [KEY_SITE]                                  NUMERIC (5)     NULL,
    [KEY_IMMUNIZATION_EVENTS]                   VARCHAR (1)     NULL,
    [KEY_IMMUNIZATION_EVENTS$VACCINE_REACTIONS] VARCHAR (1)     NULL,
    [VACCINE_REACTIONS_IEN]                     NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_IMMUNIZATION_EVENTS$VACCINE_REACTIONS]
    ON [dbo].[IMMUNIZATION_EVENTS$VACCINE_REACTIONS]([KEY_SITE] ASC, [KEY_IMMUNIZATION_EVENTS] ASC, [KEY_IMMUNIZATION_EVENTS$VACCINE_REACTIONS] ASC);

