CREATE TABLE [dbo].[IMMUNIZATION_EVENTS] (
    [KEY_SITE]                       NUMERIC (5)     NULL,
    [KEY_IMMUNIZATION_EVENTS]        NUMERIC (10, 3) NULL,
    [PATIENT_IEN_IEN]                NUMERIC (21, 3) NULL,
    [VACCINE_TYPE_IEN]               NUMERIC (22, 4) NULL,
    [DATE_TIME_ADMINISTERED]         DATETIME        NULL,
    [IMMUNIZATION_IEN]               NUMERIC (21, 3) NULL,
    [EVENT_STATUS]                   VARCHAR (30)    NULL,
    [PRIMARY_IMMUNIZATION_EVENT_IEN] NUMERIC (21, 3) NULL,
    [DOSE]                           NUMERIC (18, 6) NULL,
    [SITE_IEN]                       NUMERIC (21, 3) NULL,
    [ADMINISTERED_BY_IEN]            NUMERIC (21, 3) NULL,
    [PERFORMING_LOCATION_IEN]        NUMERIC (21, 3) NULL,
    [RESULT_COMMENT]                 VARCHAR (60)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_IMMUNIZATION_EVENTS]
    ON [dbo].[IMMUNIZATION_EVENTS]([KEY_SITE] ASC, [KEY_IMMUNIZATION_EVENTS] ASC);

