CREATE TABLE [dbo].[INSURANCE_CO_FILE] (
    [KEY_SITE]              NUMERIC (5)     NULL,
    [KEY_INSURANCE_CO_FILE] NUMERIC (11, 3) NULL,
    [INSURANCE_CO_NAME]     VARCHAR (35)    NULL,
    [SHORT_NAME]            VARCHAR (14)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_INSURANCE_CO_FILE]
    ON [dbo].[INSURANCE_CO_FILE]([KEY_SITE] ASC, [KEY_INSURANCE_CO_FILE] ASC);

