CREATE TABLE [dbo].[INSURED_PARTY$POLICY_COVERAGE] (
    [KEY_SITE]                          NUMERIC (5)     NULL,
    [KEY_INSURED_PARTY]                 NUMERIC (13, 3) NULL,
    [KEY_INSURED_PARTY$POLICY_COVERAGE] NUMERIC (11, 3) NULL,
    [POLICY_COVERAGE_IEN]               NUMERIC (21, 3) NULL,
    [PRIMARY_FLAG]                      VARCHAR (30)    NULL,
    [RELATIONSHIP_IEN]                  NUMERIC (21, 3) NULL,
    [DATE_TIME_POLICY_UPDATED]          DATETIME        NULL,
    [PATIENT_POLICY_EFFECTIVE_DATE]     DATETIME        NULL,
    [PATIENT_POLICY_EXPIRATION_DATE]    DATETIME        NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_INSURED_PARTY$POLICY_COVERAGE]
    ON [dbo].[INSURED_PARTY$POLICY_COVERAGE]([KEY_SITE] ASC, [KEY_INSURED_PARTY] ASC, [KEY_INSURED_PARTY$POLICY_COVERAGE] ASC);

