CREATE TABLE [dbo].[KG_ADC_DATA$CPT_CODE] (
    [KEY_SITE]                 NUMERIC (5)     NULL,
    [KEY_KG_ADC_DATA]          NUMERIC (14, 3) NULL,
    [KEY_KG_ADC_DATA$CPT_CODE] NUMERIC (8, 3)  NULL,
    [CPT_CODE_IEN]             NUMERIC (21, 3) NULL,
    [DIAGNOSIS_PRIORITY]       NUMERIC (10, 3) NULL
);


GO
CREATE CLUSTERED INDEX [IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA$CPT_CODE]
    ON [dbo].[KG_ADC_DATA$CPT_CODE]([KEY_KG_ADC_DATA$CPT_CODE] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_KG_ADC_DATA$CPT_CODE_CPT_CODE_IEN]
    ON [dbo].[KG_ADC_DATA$CPT_CODE]([CPT_CODE_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA]
    ON [dbo].[KG_ADC_DATA$CPT_CODE]([KEY_KG_ADC_DATA] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_KG_ADC_DATA$CPT_CODE_DIAGNOSIS_PRIORITY]
    ON [dbo].[KG_ADC_DATA$CPT_CODE]([DIAGNOSIS_PRIORITY] ASC) WITH (FILLFACTOR = 100);

