CREATE TABLE [dbo].[KG_ADC_DATA] (
    [KEY_SITE]            NUMERIC (5)     NULL,
    [KEY_KG_ADC_DATA]     NUMERIC (14, 3) NULL,
    [APPOINTMENT_IEN]     NUMERIC (21, 3) NULL,
    [LAST_EDIT_DATE_TIME] DATETIME        NULL,
    [SOURCE_SYSTEM]       VARCHAR (30)    NULL,
    [CAPER_TRANSMIT_DT]   DATETIME        NULL,
    [CHIEF_COMPLAINT_IEN] NUMERIC (21, 3) NULL,
    [DATE_OF_ACCIDENT]    DATETIME        NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_KG_ADC_DATA]
    ON [dbo].[KG_ADC_DATA]([KEY_SITE] ASC, [KEY_KG_ADC_DATA] ASC);

