CREATE TABLE [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2] (
    [KEY_SITE]                                          NUMERIC (5)     NULL,
    [KEY_LAB_RESULT]                                    NUMERIC (13, 3) NULL,
    [KEY_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2] NUMERIC (9, 3)  NULL,
    [KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM]         NUMERIC (12, 3) NULL,
    [KEY_LAB_RESULT$BACTERIOLOGY$TEST]                  NUMERIC (10, 3) NULL,
    [KEY_LAB_RESULT$BACTERIOLOGY]                       NUMERIC (26, 9) NULL,
    [ANTIBIOTIC_IEN]                                    NUMERIC (21, 3) NULL,
    [SENSITIVITY]                                       VARCHAR (10)    NULL,
    [INTERPRETATION_IEN]                                NUMERIC (21, 3) NULL
);


GO
CREATE CLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_MULTIKEY]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([KEY_LAB_RESULT] ASC, [KEY_LAB_RESULT$BACTERIOLOGY] ASC, [KEY_LAB_RESULT$BACTERIOLOGY$TEST] ASC, [KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM] ASC, [ANTIBIOTIC_IEN] ASC, [INTERPRETATION_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([KEY_LAB_RESULT] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([KEY_LAB_RESULT$BACTERIOLOGY] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([KEY_LAB_RESULT$BACTERIOLOGY$TEST] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([KEY_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_ANTIBIOTIC_IEN]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([ANTIBIOTIC_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_INTERPRETATION_IEN]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2]([INTERPRETATION_IEN] ASC) WITH (FILLFACTOR = 100);

