CREATE TABLE [dbo].[LAB_TEST$MTF_CPT_CODE] (
    [KEY_SITE]                  NUMERIC (5)     NULL,
    [KEY_LAB_TEST]              NUMERIC (10, 3) NULL,
    [KEY_LAB_TEST$MTF_CPT_CODE] NUMERIC (11, 3) NULL,
    [MTF_CPT_CODE_IEN]          NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST$MTF_CPT_CODE_KEY_LAB_TEST$MTF_CPT_CODE]
    ON [dbo].[LAB_TEST$MTF_CPT_CODE]([KEY_LAB_TEST$MTF_CPT_CODE] ASC) WITH (FILLFACTOR = 100);

