CREATE TABLE [dbo].[LAB_STATUS] (
    [KEY_SITE]       NUMERIC (5)    NULL,
    [KEY_LAB_STATUS] NUMERIC (8, 3) NULL,
    [NAME]           VARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_STATUS_KEY_LAB_STATUS]
    ON [dbo].[LAB_STATUS]([KEY_LAB_STATUS] ASC) WITH (FILLFACTOR = 100);

