CREATE TABLE [dbo].[LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR] (
    [KEY_SITE]                                          NUMERIC (5)     NULL,
    [KEY_LAB_RESULT]                                    NUMERIC (13, 3) NULL,
    [KEY_LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR] NUMERIC (7, 3)  NULL,
    [KEY_LAB_RESULT$BACTERIOLOGY$TEST]                  NUMERIC (10, 3) NULL,
    [KEY_LAB_RESULT$BACTERIOLOGY]                       NUMERIC (26, 9) NULL,
    [APPENDED_AMENDED_RNR_HCP_IEN]                      NUMERIC (22, 4) NULL,
    [APPENDED_AMENDED_RNR_DATE_TIME]                    DATETIME        NULL
);


GO
CREATE CLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR_APPENDED_AMENDED_RNR_DATE_TIME]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR]([APPENDED_AMENDED_RNR_DATE_TIME] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR_KEY_LAB_RESULT]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR]([KEY_LAB_RESULT] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR_KEY_LAB_RESULT$BACTERIOLOGY]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR]([KEY_LAB_RESULT$BACTERIOLOGY] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR_KEY_LAB_RESULT$BACTERIOLOGY$TEST]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR]([KEY_LAB_RESULT$BACTERIOLOGY$TEST] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR_MULTI_KEY]
    ON [dbo].[LAB_RESUL$BACTERIOL$TEST$APPENDED_AMENDED_RNR]([KEY_LAB_RESULT] ASC, [KEY_LAB_RESULT$BACTERIOLOGY] ASC, [KEY_LAB_RESULT$BACTERIOLOGY$TEST] ASC) WITH (FILLFACTOR = 100);

