CREATE TABLE [dbo].[LAB_TEST$COLLECTION_SAMPLE] (
    [KEY_SITE]                       NUMERIC (5)     NULL,
    [KEY_LAB_TEST]                   NUMERIC (10, 3) NULL,
    [KEY_LAB_TEST$COLLECTION_SAMPLE] NUMERIC (9, 3)  NULL,
    [COLLECTION_SAMPLE]              VARCHAR (30)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_LAB_TEST$COLLECTION_SAMPLE]
    ON [dbo].[LAB_TEST$COLLECTION_SAMPLE]([KEY_SITE] ASC, [KEY_LAB_TEST] ASC, [KEY_LAB_TEST$COLLECTION_SAMPLE] ASC);

