CREATE TABLE [dbo].[LAB_TEST$LAB_TEST_IN_PANEL] (
    [KEY_SITE]                       NUMERIC (5)     NULL,
    [KEY_LAB_TEST]                   NUMERIC (10, 3) NULL,
    [KEY_LAB_TEST$LAB_TEST_IN_PANEL] NUMERIC (9, 3)  NULL,
    [LAB_TEST_IN_PANEL_IEN]          NUMERIC (21, 3) NULL,
    [PANEL_TEST_ID]                  VARCHAR (30)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST$LAB_TEST_IN_PANEL]
    ON [dbo].[LAB_TEST$LAB_TEST_IN_PANEL]([KEY_LAB_TEST$LAB_TEST_IN_PANEL] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST]
    ON [dbo].[LAB_TEST$LAB_TEST_IN_PANEL]([KEY_LAB_TEST] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST$LAB_TEST_IN_PANEL_LAB_TEST_IN_PANEL_IEN]
    ON [dbo].[LAB_TEST$LAB_TEST_IN_PANEL]([LAB_TEST_IN_PANEL_IEN] ASC) WITH (FILLFACTOR = 100);

