CREATE TABLE [dbo].[LAB_TEST] (
    [KEY_SITE]     NUMERIC (5)     NULL,
    [KEY_LAB_TEST] NUMERIC (10, 3) NULL,
    [NAME]         VARCHAR (30)    NULL,
    [SINGLE_PANEL] VARCHAR (30)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST_KEY_LAB_TEST]
    ON [dbo].[LAB_TEST]([KEY_LAB_TEST] ASC) WITH (FILLFACTOR = 100);

