CREATE TABLE [dbo].[LAB_TEST$LAB_WORK_ELEMENT] (
    [KEY_SITE]                      NUMERIC (5)     NULL,
    [KEY_LAB_TEST]                  NUMERIC (10, 3) NULL,
    [KEY_LAB_TEST$LAB_WORK_ELEMENT] NUMERIC (11, 3) NULL,
    [LAB_WORK_ELEMENT_IEN]          NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST$LAB_WORK_ELEMENT]
    ON [dbo].[LAB_TEST$LAB_WORK_ELEMENT]([KEY_LAB_TEST$LAB_WORK_ELEMENT] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST]
    ON [dbo].[LAB_TEST$LAB_WORK_ELEMENT]([KEY_LAB_TEST] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_LAB_TEST$LAB_WORK_ELEMENT_LAB_WORK_ELEMENT_IEN]
    ON [dbo].[LAB_TEST$LAB_WORK_ELEMENT]([LAB_WORK_ELEMENT_IEN] ASC) WITH (FILLFACTOR = 100);

