CREATE TABLE [dbo].[MCP_UNIT_PCM] (
    [KEY_SITE]         NUMERIC (5)     NULL,
    [KEY_MCP_UNIT_PCM] NUMERIC (12, 3) NULL,
    [NAME_IEN]         NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_MCP_UNIT_PCM]
    ON [dbo].[MCP_UNIT_PCM]([KEY_SITE] ASC, [KEY_MCP_UNIT_PCM] ASC);

