CREATE TABLE [dbo].[MCP_REFERRAL$APPOINTMENT_REFUSALS] (
    [KEY_SITE]                              NUMERIC (5)     NULL,
    [KEY_MCP_REFERRAL]                      NUMERIC (17, 3) NULL,
    [KEY_MCP_REFERRAL$APPOINTMENT_REFUSALS] NUMERIC (8, 3)  NULL,
    [DATE_TIME]                             DATETIME        NULL,
    [REFUSAL_STATUS]                        VARCHAR (30)    NULL,
    [REFUSAL_REASON_IEN]                    NUMERIC (21, 3) NULL,
    [REASON_TEXT]                           TEXT            NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL]
    ON [dbo].[MCP_REFERRAL$APPOINTMENT_REFUSALS]([KEY_MCP_REFERRAL] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL$APPOINTMENT_REFUSALS]
    ON [dbo].[MCP_REFERRAL$APPOINTMENT_REFUSALS]([KEY_MCP_REFERRAL$APPOINTMENT_REFUSALS] ASC) WITH (FILLFACTOR = 100);

