CREATE TABLE [dbo].[MCP_APPOINTMENT_REFUSAL_REASON] (
    [KEY_SITE]                           NUMERIC (5)     NULL,
    [KEY_MCP_APPOINTMENT_REFUSAL_REASON] NUMERIC (8, 3)  NULL,
    [CODE]                               NUMERIC (13, 5) NULL,
    [TYPE_]                              VARCHAR (30)    NULL,
    [DESCRIPTION]                        VARCHAR (65)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_APPOINTMENT_REFUSAL_REASON_KEY_MCP_APPOINTMENT_REFUSAL_REASON]
    ON [dbo].[MCP_APPOINTMENT_REFUSAL_REASON]([KEY_MCP_APPOINTMENT_REFUSAL_REASON] ASC) WITH (FILLFACTOR = 100);

