CREATE TABLE [dbo].[MCP_REFERRAL$APPOINTMENT_REQUEST_REVIEW] (
    [KEY_SITE]                                    NUMERIC (5)     NULL,
    [KEY_MCP_REFERRAL]                            NUMERIC (17, 3) NULL,
    [KEY_MCP_REFERRAL$APPOINTMENT_REQUEST_REVIEW] NUMERIC (8, 3)  NULL,
    [REVIEW_DATE_TIME]                            DATETIME        NULL,
    [REVIEWER_IEN]                                NUMERIC (21, 3) NULL,
    [APPOINTMENT_REQUEST_STATUS_IEN]              NUMERIC (21, 3) NULL,
    [REVIEW_COMMENT]                              TEXT            NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_MCP_REFERRAL$APPOINTMENT_REQUEST_REVIEW]
    ON [dbo].[MCP_REFERRAL$APPOINTMENT_REQUEST_REVIEW]([KEY_SITE] ASC, [KEY_MCP_REFERRAL] ASC, [KEY_MCP_REFERRAL$APPOINTMENT_REQUEST_REVIEW] ASC);

