CREATE TABLE [dbo].[MCP_REFERRAL$FREE_TEXT_DIAGNOSIS] (
    [KEY_SITE]                             NUMERIC (5)     NULL,
    [KEY_MCP_REFERRAL]                     NUMERIC (17, 3) NULL,
    [KEY_MCP_REFERRAL$FREE_TEXT_DIAGNOSIS] NUMERIC (7, 3)  NULL,
    [FREE_TEXT_DIAGNOSIS]                  VARCHAR (78)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_MCP_REFERRAL$FREE_TEXT_DIAGNOSIS]
    ON [dbo].[MCP_REFERRAL$FREE_TEXT_DIAGNOSIS]([KEY_SITE] ASC, [KEY_MCP_REFERRAL] ASC, [KEY_MCP_REFERRAL$FREE_TEXT_DIAGNOSIS] ASC);

