CREATE TABLE [dbo].[MCP_REFERRAL$PROVISIONAL_DIAGNOSIS] (
    [KEY_SITE]                               NUMERIC (5)     NULL,
    [KEY_MCP_REFERRAL]                       NUMERIC (17, 3) NULL,
    [KEY_MCP_REFERRAL$PROVISIONAL_DIAGNOSIS] NUMERIC (7, 3)  NULL,
    [PROVISIONAL_DIAGNOSIS_IEN]              NUMERIC (21, 3) NULL,
    [DESCRIPTION]                            VARCHAR (225)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_MCP_REFERRAL$PROVISIONAL_DIAGNOSIS]
    ON [dbo].[MCP_REFERRAL$PROVISIONAL_DIAGNOSIS]([KEY_SITE] ASC, [KEY_MCP_REFERRAL] ASC, [KEY_MCP_REFERRAL$PROVISIONAL_DIAGNOSIS] ASC);

