CREATE TABLE [dbo].[MCP_REFERRAL] (
    [KEY_SITE]                      NUMERIC (5)     NULL,
    [KEY_MCP_REFERRAL]              NUMERIC (17, 3) NULL,
    [REFERRAL_NUMBER]               VARCHAR (11)    NULL,
    [PATIENT_IEN]                   NUMERIC (21, 3) NULL,
    [REFERRAL_DATE_TIME]            DATETIME        NULL,
    [SPECIALTY_IEN]                 NUMERIC (21, 3) NULL,
    [NUMBER_OF_VISITS]              NUMERIC (8, 3)  NULL,
    [SPECIALTY_LOCATION]            VARCHAR (35)    NULL,
    [REFERRED_TO_PROVIDER_IEN]      NUMERIC (21, 3) NULL,
    [REFERRED_BY_IEN]               NUMERIC (21, 3) NULL,
    [PRIORITY_IEN]                  NUMERIC (22, 4) NULL,
    [NUMBER_OF_APPOINTMENTS_BOOKED] NUMERIC (10, 3) NULL,
    [REFERRAL_FROM_IEN]             NUMERIC (22, 4) NULL,
    [REQUESTED_APPT_TYPE_IEN]       NUMERIC (21, 3) NULL,
    [REFERRAL_TYPE]                 VARCHAR (31)    NULL,
    [REFERRED_TO_PLACE_OF_CARE_IEN] NUMERIC (21, 3) NULL,
    [ORDER_IEN]                     NUMERIC (21, 3) NULL,
    [TEMP_REVIEW_STATUS_IEN]        NUMERIC (21, 3) NULL,
    [REASON_FOR_REFERRAL]           TEXT            NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL_KEY_MCP_REFERRAL]
    ON [dbo].[MCP_REFERRAL]([KEY_MCP_REFERRAL] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL_ORDER_IEN]
    ON [dbo].[MCP_REFERRAL]([ORDER_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL_REFERRAL_FROM_IEN]
    ON [dbo].[MCP_REFERRAL]([REFERRAL_FROM_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL_REFERRED_BY_IEN]
    ON [dbo].[MCP_REFERRAL]([REFERRED_BY_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL_REFERRED_TO_PROVIDER_IEN]
    ON [dbo].[MCP_REFERRAL]([REFERRED_TO_PROVIDER_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL_REFERRED_TO_PLACE_OF_CARE_IEN]
    ON [dbo].[MCP_REFERRAL]([REFERRED_TO_PLACE_OF_CARE_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL_REFERRAL_DATE_TIME]
    ON [dbo].[MCP_REFERRAL]([REFERRAL_DATE_TIME] ASC) WITH (FILLFACTOR = 100);

