CREATE TABLE [dbo].[MCP_REFERRAL$APPOINTMENTS] (
    [KEY_SITE]                      NUMERIC (5)     NULL,
    [KEY_MCP_REFERRAL]              NUMERIC (17, 3) NULL,
    [KEY_MCP_REFERRAL$APPOINTMENTS] NUMERIC (14, 3) NULL,
    [APPOINTMENT_IEN]               NUMERIC (21, 3) NULL,
    [PROVIDER_SPECIALTY_TYPE_IEN]   NUMERIC (21, 3) NULL,
    [PROVIDER_IEN]                  NUMERIC (21, 3) NULL,
    [SPECIALTY_IEN]                 NUMERIC (21, 3) NULL,
    [SPECIALTY_LOCATION]            VARCHAR (35)    NULL,
    [SPECIALTY_LOCATION_IEN_IEN]    VARCHAR (15)    NULL,
    [CLINIC_IEN]                    NUMERIC (21, 3) NULL,
    [REFERRED_TO_IEN]               NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_REFERRAL$APPOINTMENTS_KEY_MCP_REFERRAL$APPOINTMENTS]
    ON [dbo].[MCP_REFERRAL$APPOINTMENTS]([KEY_MCP_REFERRAL$APPOINTMENTS] ASC) WITH (FILLFACTOR = 100);

