CREATE TABLE [dbo].[MCP_ALTERNATE_CARE_VALUE] (
    [KEY_SITE]                     NUMERIC (5)    NULL,
    [KEY_MCP_ALTERNATE_CARE_VALUE] NUMERIC (8, 3) NULL,
    [CODE]                         VARCHAR (30)   NULL,
    [DESCRIPTION]                  VARCHAR (51)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MCP_ALTERNATE_CARE_VALUE_KEY_MCP_ALTERNATE_CARE_VALUE]
    ON [dbo].[MCP_ALTERNATE_CARE_VALUE]([KEY_MCP_ALTERNATE_CARE_VALUE] ASC) WITH (FILLFACTOR = 100);

