CREATE TABLE [dbo].[MCP_REFERRAL$PROCEDURES] (
    [KEY_SITE]                    NUMERIC (5)     NULL,
    [KEY_MCP_REFERRAL]            NUMERIC (17, 3) NULL,
    [KEY_MCP_REFERRAL$PROCEDURES] NUMERIC (7, 3)  NULL,
    [PROCEDURE_IEN]               NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_MCP_REFERRAL$PROCEDURES]
    ON [dbo].[MCP_REFERRAL$PROCEDURES]([KEY_SITE] ASC, [KEY_MCP_REFERRAL] ASC, [KEY_MCP_REFERRAL$PROCEDURES] ASC);

