CREATE TABLE [dbo].[MCP_PROVIDER] (
    [KEY_SITE]                   NUMERIC (5)     NULL,
    [KEY_MCP_PROVIDER]           NUMERIC (11, 3) NULL,
    [MCP_PROVIDER_NAME_IEN]      NUMERIC (21, 3) NULL,
    [PROF_CATEGORY_IEN]          NUMERIC (21, 3) NULL,
    [CHAMPUS_NUMBER]             VARCHAR (18)    NULL,
    [NETWORK_PROVIDER_TYPE_CODE] VARCHAR (30)    NULL,
    [PCM_ID]                     VARCHAR (18)    NULL,
    [PCM_ID_TYPE_CODE_IEN]       NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_MCP_PROVIDER]
    ON [dbo].[MCP_PROVIDER]([KEY_SITE] ASC, [KEY_MCP_PROVIDER] ASC);

