CREATE TABLE [dbo].[MEDICATION_PROFILE] (
    [KEY_SITE]               NUMERIC (5)     NULL,
    [KEY_MEDICATION_PROFILE] NUMERIC (14, 3) NULL,
    [MEDICATION]             VARCHAR (40)    NULL,
    [PATIENT_IEN]            NUMERIC (21, 3) NULL,
    [START_DATE_TIME]        DATETIME        NULL,
    [STOP_EXPIRATION_DATE]   DATETIME        NULL,
    [ORDERING_HCP]           VARCHAR (30)    NULL,
    [PATIENT_STATUS]         VARCHAR (30)    NULL,
    [ENCOUNTER_EPISODE_IEN]  NUMERIC (21, 3) NULL,
    [ORDER_TYPE_IEN]         NUMERIC (21, 3) NULL,
    [ORDER_IEN]              NUMERIC (21, 3) NULL,
    [SIG]                    VARCHAR (306)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MEDICATION_PROFILE_PatientIEN]
    ON [dbo].[MEDICATION_PROFILE]([PATIENT_IEN] ASC);

