CREATE TABLE [dbo].[MEDICAL_CENTER_DIVISION] (
    [KEY_SITE]                    NUMERIC (5)     NULL,
    [KEY_MEDICAL_CENTER_DIVISION] NUMERIC (8, 3)  NULL,
    [NAME]                        VARCHAR (30)    NULL,
    [DMIS_ID_CODE_IEN]            NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MEDICAL_CENTER_DIVISION_KEY_MEDICAL_CENTER_DIVISION]
    ON [dbo].[MEDICAL_CENTER_DIVISION]([KEY_MEDICAL_CENTER_DIVISION] ASC) WITH (FILLFACTOR = 100);

