CREATE TABLE [dbo].[MEPRS_CODES] (
    [KEY_SITE]        NUMERIC (5)     NULL,
    [KEY_MEPRS_CODES] NUMERIC (10, 3) NULL,
    [CODE]            VARCHAR (4)     NULL,
    [DESCRIPTION]     VARCHAR (50)    NULL,
    [DMIS_ID_IEN]     NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MEPRS_CODES_KEY_MEPRS_CODES]
    ON [dbo].[MEPRS_CODES]([KEY_MEPRS_CODES] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MEPRS_CODES_DMIS_ID_IEN]
    ON [dbo].[MEPRS_CODES]([DMIS_ID_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_MEPRS_CODES_CODE]
    ON [dbo].[MEPRS_CODES]([CODE] ASC) WITH (FILLFACTOR = 100);

