CREATE TABLE [dbo].[MESSAGE$ADDRESSEE] (
    [KEY_SITE]              NUMERIC (5)     NULL,
    [KEY_MESSAGE]           NUMERIC (14, 3) NULL,
    [KEY_MESSAGE$ADDRESSEE] NUMERIC (7, 3)  NULL,
    [ADDRESSEE]             VARCHAR (60)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_MESSAGE$ADDRESSEE]
    ON [dbo].[MESSAGE$ADDRESSEE]([KEY_SITE] ASC, [KEY_MESSAGE] ASC, [KEY_MESSAGE$ADDRESSEE] ASC);

