CREATE TABLE [dbo].[METHOD_OF_TRANSIT] (
    [KEY_SITE]              NUMERIC (5)    NULL,
    [KEY_METHOD_OF_TRANSIT] NUMERIC (8, 3) NULL,
    [NAME]                  VARCHAR (30)   NULL,
    [CODE]                  VARCHAR (4)    NULL,
    [DBA_INACTIVE_FLAG]     VARCHAR (30)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_METHOD_OF_TRANSIT]
    ON [dbo].[METHOD_OF_TRANSIT]([KEY_SITE] ASC, [KEY_METHOD_OF_TRANSIT] ASC);

