CREATE TABLE [dbo].[MILITARY_GRADE_RANK] (
    [KEY_SITE]                NUMERIC (5)    NULL,
    [KEY_MILITARY_GRADE_RANK] NUMERIC (9, 3) NULL,
    [NAME]                    VARCHAR (38)   NULL,
    [CODE]                    VARCHAR (4)    NULL,
    [ABBREVIATION]            VARCHAR (4)    NULL,
    [PAYGRADE]                VARCHAR (2)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_MILITARY_GRADE_RANK_KEY_MILITARY_GRADE_RANK]
    ON [dbo].[MILITARY_GRADE_RANK]([KEY_MILITARY_GRADE_RANK] ASC) WITH (FILLFACTOR = 100);

