CREATE TABLE [dbo].[NDI_ELIGIBILITY] (
    [KEY_SITE]              NUMERIC (5)     NULL,
    [KEY_NDI_ELIGIBILITY]   NUMERIC (13, 3) NULL,
    [PATIENT_NAME_IEN]      NUMERIC (21, 3) NULL,
    [DATE_TIME_OF_RESPONSE] DATETIME        NULL,
    [ELIGIBILITY_INDICATOR] VARCHAR (30)    NULL,
    [PCM_ID]                VARCHAR (18)    NULL,
    [PCM_ID_TYPE_IEN]       NUMERIC (21, 3) NULL,
    [PCM_HCDP_CODE_IEN]     NUMERIC (21, 3) NULL,
    [PCM_START_DATE]        DATETIME        NULL,
    [PCM_STOP_DATE]         DATETIME        NULL,
    [PCM_NAME]              VARCHAR (35)    NULL,
    [PCM_CODE]              VARCHAR (30)    NULL,
    [PCM_DMIS_IEN]          NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_NDI_ELIGIBILITY_PCM_ID]
    ON [dbo].[NDI_ELIGIBILITY]([PCM_ID] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_NDI_ELIGIBILITY_PATIENT_NAME_IEN]
    ON [dbo].[NDI_ELIGIBILITY]([PATIENT_NAME_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_NDI_ELIGIBILITY_PCM_DMIS_IEN]
    ON [dbo].[NDI_ELIGIBILITY]([PCM_DMIS_IEN] ASC) WITH (FILLFACTOR = 100);

