CREATE TABLE [dbo].[NED_PROVIDER_GROUP] (
    [KEY_SITE]               NUMERIC (5)    NULL,
    [KEY_NED_PROVIDER_GROUP] NUMERIC (9, 3) NULL,
    [GROUP_NAME]             VARCHAR (30)   NULL,
    [MCP_GROUP_ID]           VARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_NED_PROVIDER_GROUP_KEY_NED_PROVIDER_GROUP]
    ON [dbo].[NED_PROVIDER_GROUP]([KEY_NED_PROVIDER_GROUP] ASC) WITH (FILLFACTOR = 100);

