CREATE TABLE [dbo].[NED_PATIENT$ENROLLMENT_HISTORY] (
    [KEY_SITE]                           NUMERIC (5)     NULL,
    [KEY_NED_PATIENT]                    NUMERIC (13, 3) NULL,
    [KEY_NED_PATIENT$ENROLLMENT_HISTORY] NUMERIC (8, 3)  NULL,
    [ENROLLMENT_HISTORY_NUMBER]          NUMERIC (17, 3) NULL,
    [HCDP_START_DATE]                    DATETIME        NULL,
    [HCDP_CONTRACTOR_COVERAGE_CODE_IEN]  NUMERIC (21, 3) NULL,
    [DMIS_ID_IEN]                        NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_NED_PATIENT$ENROLLMENT_HISTORY]
    ON [dbo].[NED_PATIENT$ENROLLMENT_HISTORY]([KEY_SITE] ASC, [KEY_NED_PATIENT] ASC, [KEY_NED_PATIENT$ENROLLMENT_HISTORY] ASC);

