CREATE TABLE [dbo].[NED_PCM_END_REASON] (
    [KEY_SITE]               NUMERIC (5)    NULL,
    [KEY_NED_PCM_END_REASON] NUMERIC (8, 3) NULL,
    [PCM_END_REASON_CODE]    VARCHAR (1)    NULL,
    [DESCRIPTION]            VARCHAR (75)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_NED_PCM_END_REASON]
    ON [dbo].[NED_PCM_END_REASON]([KEY_SITE] ASC, [KEY_NED_PCM_END_REASON] ASC);

