CREATE TABLE [dbo].[ORDER_TYPE] (
    [KEY_SITE]       NUMERIC (5)    NULL,
    [KEY_ORDER_TYPE] NUMERIC (8, 3) NULL,
    [NUMBER_]        NUMERIC (8, 3) NULL,
    [NAME]           VARCHAR (4)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_TYPE_KEY_ORDER_TYPE]
    ON [dbo].[ORDER_TYPE]([KEY_ORDER_TYPE] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_TYPE_NUMBER_]
    ON [dbo].[ORDER_TYPE]([NUMBER_] ASC) WITH (FILLFACTOR = 100);

