CREATE TABLE [dbo].[ORDER_TASK] (
    [KEY_SITE]             NUMERIC (5)     NULL,
    [KEY_ORDER_TASK]       NUMERIC (14, 3) NULL,
    [NUMBER_]              NUMERIC (14, 3) NULL,
    [DATE_TIME]            DATETIME        NULL,
    [ORDER_IEN]            NUMERIC (21, 3) NULL,
    [TASK_STATUS]          VARCHAR (30)    NULL,
    [COMPLETION_DATE_TIME] DATETIME        NULL
);


GO
CREATE CLUSTERED INDEX [IX_ORDER_TASK_KEY_ORDER_TASK]
    ON [dbo].[ORDER_TASK]([KEY_ORDER_TASK] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_TASK_ORDER_IEN]
    ON [dbo].[ORDER_TASK]([ORDER_IEN] ASC) WITH (FILLFACTOR = 100);

