CREATE TABLE [dbo].[ORDER_] (
    [KEY_SITE]                       NUMERIC (5)     NULL,
    [KEY_ORDER]                      NUMERIC (14, 3) NULL,
    [ID_NUMBER]                      VARCHAR (30)    NULL,
    [PATIENT_IEN]                    NUMERIC (21, 3) NULL,
    [IN_OUTPATIENT]                  VARCHAR (30)    NULL,
    [ORDER_TYPE_IEN]                 NUMERIC (21, 3) NULL,
    [PATIENT_LOCATION_IEN]           NUMERIC (22, 4) NULL,
    [ORDERING_HCP_IEN]               NUMERIC (21, 3) NULL,
    [ORDER_COMMENT]                  VARCHAR (78)    NULL,
    [EARLIEST_TASK_DATE_TIME]        DATETIME        NULL,
    [USER_SIG_DATE_TIME]             DATETIME        NULL,
    [NURSE_SIG_DATE_TIME]            DATETIME        NULL,
    [HCP_SIG_DATE_TIME]              DATETIME        NULL,
    [ORDER_DATE_TIME]                DATETIME        NULL,
    [ACTIVITY]                       VARCHAR (30)    NULL,
    [ACTIVE_STATUS]                  VARCHAR (30)    NULL,
    [INACTIVE_STATUS]                VARCHAR (30)    NULL,
    [PENDING_APPOINTMENT]            VARCHAR (30)    NULL,
    [PRIORITY_IEN]                   NUMERIC (22, 4) NULL,
    [APPOINTMENT_DATE_TIME]          DATETIME        NULL,
    [PAS_APPOINTMENT_STATUS_IEN]     NUMERIC (21, 3) NULL,
    [STOP_EXPIRATION_DATE]           DATETIME        NULL,
    [START_DATE_TIME]                DATETIME        NULL,
    [DISPLAY_TEXT]                   VARCHAR (240)   NULL,
    [OUTPATIENT_ENCOUNTER_IEN]       NUMERIC (21, 3) NULL,
    [LAB_TEST_IEN]                   NUMERIC (21, 3) NULL,
    [COLLECTION_SAMPLE_IEN]          NUMERIC (21, 3) NULL,
    [DATE_TIME_OF_COLLECTION]        DATETIME        NULL,
    [CLINICAL_COMMENT]               VARCHAR (70)    NULL,
    [REQUESTING_PHYSICIAN_IEN]       NUMERIC (21, 3) NULL,
    [MEDICATION_IEN]                 NUMERIC (21, 3) NULL,
    [PDTS_FILL_COST]                 NUMERIC (17, 5) NULL,
    [QUANTITY]                       NUMERIC (15, 5) NULL,
    [RADIOLOGY_PROCEDURE_IEN]        NUMERIC (21, 3) NULL,
    [PORTABLE]                       VARCHAR (15)    NULL,
    [CLINICAL_IMPRESSION__BRIEF_]    NUMERIC (21, 3) NULL,
    [MOBILITY_STATUS]                VARCHAR (30)    NULL,
    [REQUESTED_HCP_IEN]              NUMERIC (21, 3) NULL,
    [REQUESTED_DATE_TIME]            DATETIME        NULL,
    [PATIENT_APPOINTMENT_IEN]        NUMERIC (21, 3) NULL,
    [REFERRAL_NUMBER_IEN]            NUMERIC (21, 3) NULL,
    [ANCILLARY_PROCEDURE_IEN]        NUMERIC (21, 3) NULL,
    [ADT_PROCEDURE_IEN]              NUMERIC (21, 3) NULL,
    [TYPE_OF_ADMISSION_IEN]          NUMERIC (21, 3) NULL,
    [DIAGNOSIS__FREE_TEXT_]          VARCHAR (50)    NULL,
    [CLINICAL_IMPRESSION__EXTENDED_] TEXT            NULL
);


GO
CREATE CLUSTERED INDEX [IX_ORDER_USER_SIG_DATE_TIME]
    ON [dbo].[ORDER_]([USER_SIG_DATE_TIME] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ORDER__KEY_ORDER]
    ON [dbo].[ORDER_]([KEY_ORDER] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_PATIENT_IEN]
    ON [dbo].[ORDER_]([PATIENT_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_ORDER_TYPE_IEN]
    ON [dbo].[ORDER_]([ORDER_TYPE_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_LAB_TEST_IEN]
    ON [dbo].[ORDER_]([LAB_TEST_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_MEDICATION_IEN]
    ON [dbo].[ORDER_]([MEDICATION_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_RADIOLOGY_PROCEDURE_IEN]
    ON [dbo].[ORDER_]([RADIOLOGY_PROCEDURE_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_ORDER_DATE_TIME]
    ON [dbo].[ORDER_]([ORDER_DATE_TIME] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_ORDERING_HCP_IEN]
    ON [dbo].[ORDER_]([ORDERING_HCP_IEN] ASC) WITH (FILLFACTOR = 100);

