CREATE TABLE [dbo].[ORDER_PRIORITY] (
    [KEY_SITE]           NUMERIC (5)     NULL,
    [KEY_ORDER_PRIORITY] NUMERIC (10, 4) NULL,
    [CODE]               NUMERIC (7, 3)  NULL,
    [NAME]               VARCHAR (30)    NULL,
    [SHORT_DESCRIPTION]  VARCHAR (40)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ORDER_PRIORITY_KEY_ORDER_PRIORITY]
    ON [dbo].[ORDER_PRIORITY]([KEY_ORDER_PRIORITY] ASC) WITH (FILLFACTOR = 100);

