CREATE TABLE [dbo].[OTHER_HEALTH_INSURANCE__OHI_$POLICY] (
    [KEY_SITE]                                NUMERIC (5)     NULL,
    [KEY_OTHER_HEALTH_INSURANCE__OHI_]        NUMERIC (13, 3) NULL,
    [KEY_OTHER_HEALTH_INSURANCE__OHI_$POLICY] NUMERIC (8, 3)  NULL,
    [POLICY_IEN]                              NUMERIC (9, 3)  NULL,
    [POLICY_IDENTIFIER]                       VARCHAR (20)    NULL,
    [CARRIER_IDENTIFIER_IEN]                  NUMERIC (21, 3) NULL,
    [POLICY_EFFECTIVE_DATE]                   DATETIME        NULL,
    [POLICY_END_DATE]                         DATETIME        NULL,
    [INSURANCE_TYPE_CODE_IEN]                 NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_OTHER_HEALTH_INSURANCE__OHI_$POLICY]
    ON [dbo].[OTHER_HEALTH_INSURANCE__OHI_$POLICY]([KEY_SITE] ASC, [KEY_OTHER_HEALTH_INSURANCE__OHI_] ASC, [KEY_OTHER_HEALTH_INSURANCE__OHI_$POLICY] ASC);

