CREATE TABLE [dbo].[PATIENT_APPOINTMENT$APPT_DETAIL_CODES] (
    [KEY_SITE]                                  NUMERIC (5)     NULL,
    [KEY_PATIENT_APPOINTMENT]                   NUMERIC (14, 3) NULL,
    [KEY_PATIENT_APPOINTMENT$APPT_DETAIL_CODES] NUMERIC (7, 3)  NULL,
    [APPT_DETAIL_CODES_IEN]                     NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT_APPOINTMENT$APPT_DETAIL_CODES_KEY_PATIENT_APPOINTMENT$APPT_DETAIL_CODES]
    ON [dbo].[PATIENT_APPOINTMENT$APPT_DETAIL_CODES]([KEY_PATIENT_APPOINTMENT$APPT_DETAIL_CODES] ASC) WITH (FILLFACTOR = 100);

