CREATE TABLE [dbo].[PATIENT_CATEGORY] (
    [KEY_SITE]             NUMERIC (5)     NULL,
    [KEY_PATIENT_CATEGORY] NUMERIC (10, 3) NULL,
    [NAME]                 VARCHAR (35)    NULL,
    [CODE]                 VARCHAR (4)     NULL,
    [SHORT_DESCRIPTION]    VARCHAR (21)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT_CATEGORY_KEY_PATIENT_CATEGORY]
    ON [dbo].[PATIENT_CATEGORY]([KEY_PATIENT_CATEGORY] ASC) WITH (FILLFACTOR = 100);

