CREATE TABLE [dbo].[PATIENT$COMMAND_INTEREST_CATEGORY] (
    [KEY_SITE]                              NUMERIC (5)     NULL,
    [KEY_PATIENT]                           NUMERIC (13, 3) NULL,
    [KEY_PATIENT$COMMAND_INTEREST_CATEGORY] NUMERIC (8, 3)  NULL,
    [COMMAND_INTEREST_CATEGORY_IEN]         NUMERIC (21, 3) NULL,
    [JPTA_INPAT_PROCESSING_DATE]            DATETIME        NULL,
    [JPTA_OUTPAT_PROCESSING_DATE]           DATETIME        NULL,
    [JPTA_END_PROCESSING_DATE]              DATETIME        NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_PATIENT$COMMAND_INTEREST_CATEGORY]
    ON [dbo].[PATIENT$COMMAND_INTEREST_CATEGORY]([KEY_SITE] ASC, [KEY_PATIENT] ASC, [KEY_PATIENT$COMMAND_INTEREST_CATEGORY] ASC);

