CREATE TABLE [dbo].[PATIENT$ADMISSION_DATE] (
    [KEY_SITE]                     NUMERIC (5)     NULL,
    [KEY_PATIENT]                  NUMERIC (13, 3) NULL,
    [KEY_PATIENT$ADMISSION_DATE]   NUMERIC (8, 3)  NULL,
    [NUMBER_]                      NUMERIC (12, 3) NULL,
    [ADMISSION_DATE]               VARCHAR (16)    NULL,
    [TYPE_OF_ADMISSION_IEN]        NUMERIC (21, 3) NULL,
    [WARD_LOCATION_IEN]            NUMERIC (22, 4) NULL,
    [DIAGNOSIS__FREE_TEXT_]        VARCHAR (50)    NULL,
    [PROVIDER_IEN]                 NUMERIC (21, 3) NULL,
    [DIVISION_IEN]                 NUMERIC (21, 3) NULL,
    [ADMISSION_ORDER_IEN]          NUMERIC (21, 3) NULL,
    [DISPOSITION_DATE]             VARCHAR (16)    NULL,
    [TYPE_OF_DISPOSITION_IEN]      NUMERIC (22, 4) NULL,
    [DISPOSITION_ORDER_IEN]        NUMERIC (21, 3) NULL,
    [SAME_DAY_SURGERY]             VARCHAR (30)    NULL,
    [SECOND_ICU_WARD_CODE_IEN]     NUMERIC (21, 3) NULL,
    [SECOND_REFERRING_MEPRS_IEN]   NUMERIC (21, 3) NULL,
    [PATIENT_STATUS]               VARCHAR (10)    NULL,
    [CHIEF_COMPLAINT]              VARCHAR (80)    NULL,
    [ENCOUNTER]                    VARCHAR (15)    NULL,
    [ADMISSION_ENCOUNTER]          VARCHAR (15)    NULL,
    [ADMITTING_PHYSICIAN_IEN]      NUMERIC (21, 3) NULL,
    [ATTENDING_PHYSICIAN_IEN]      NUMERIC (21, 3) NULL,
    [DISPOSITIONING_PHYSICIAN_IEN] NUMERIC (21, 3) NULL,
    [DIAGNOSIS_AT_ADMISSION_IEN]   VARCHAR (15)    NULL,
    [ADMITTING_SERVICE_IEN]        NUMERIC (21, 3) NULL,
    [SUPERVISOR_VALIDATED]         VARCHAR (30)    NULL,
    [PATIENT_NAME]                 VARCHAR (30)    NULL,
    [FMP_SSN]                      VARCHAR (15)    NULL,
    [PATIENT_CATEGORY_IEN]         NUMERIC (21, 3) NULL,
    [SEX]                          VARCHAR (30)    NULL,
    [FMP_IEN]                      NUMERIC (21, 3) NULL,
    [PCM_IDENTIFIER]               VARCHAR (18)    NULL
);


GO
CREATE CLUSTERED INDEX [IX_PATIENT$ADMISSION_DATE_ADMISSION_DATE]
    ON [dbo].[PATIENT$ADMISSION_DATE]([ADMISSION_DATE] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT$ADMISSION_DATE_KEY_PATIENT$ADMISSION_DATE]
    ON [dbo].[PATIENT$ADMISSION_DATE]([KEY_PATIENT$ADMISSION_DATE] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT$ADMISSION_DATE_KEY_PATIENT]
    ON [dbo].[PATIENT$ADMISSION_DATE]([KEY_PATIENT] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT$ADMISSION_DATE_TYPE_OF_ADMISSION_IEN]
    ON [dbo].[PATIENT$ADMISSION_DATE]([TYPE_OF_ADMISSION_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT$ADMISSION_DATE_TYPE_OF_DISPOSITION_IEN]
    ON [dbo].[PATIENT$ADMISSION_DATE]([TYPE_OF_DISPOSITION_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT$ADMISSION_DATE_ADMITTING_PHYSICIAN_IEN]
    ON [dbo].[PATIENT$ADMISSION_DATE]([ADMITTING_PHYSICIAN_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT$ADMISSION_DATE_ATTENDING_PHYSICIAN_IEN]
    ON [dbo].[PATIENT$ADMISSION_DATE]([ATTENDING_PHYSICIAN_IEN] ASC) WITH (FILLFACTOR = 100);

