CREATE TABLE [dbo].[PATIENT_APPOINTMENT] (
    [KEY_SITE]                   NUMERIC (5)     NULL,
    [KEY_PATIENT_APPOINTMENT]    NUMERIC (14, 3) NULL,
    [NAME_IEN]                   NUMERIC (21, 3) NULL,
    [APPT_DIVISION_IEN]          NUMERIC (21, 3) NULL,
    [APPOINTMENT_DATE_TIME]      DATETIME        NULL,
    [ORDER_ENTRY_PTR_IEN]        NUMERIC (21, 3) NULL,
    [ORDER_NUMBER]               VARCHAR (12)    NULL,
    [CLINIC_IEN]                 NUMERIC (21, 3) NULL,
    [PROVIDER_IEN]               NUMERIC (21, 3) NULL,
    [REFERRAL_IEN_IEN]           NUMERIC (21, 3) NULL,
    [DURATION]                   NUMERIC (11, 3) NULL,
    [APPOINTMENT_TYPE_IEN]       NUMERIC (21, 3) NULL,
    [APPOINTMENT_STATUS_IEN]     NUMERIC (21, 3) NULL,
    [PATIENT_CANCELLED_REASON]   VARCHAR (30)    NULL,
    [PATIENT_STATUS]             VARCHAR (30)    NULL,
    [MEPRS_CODE_IEN]             NUMERIC (21, 3) NULL,
    [REFERRED_BY]                VARCHAR (30)    NULL,
    [APPOINTMENT_COMMENT]        VARCHAR (35)    NULL,
    [REASON_FOR_APPOINTMENT]     VARCHAR (81)    NULL,
    [COMMAND_SECURITY_IEN]       NUMERIC (21, 3) NULL,
    [DATE_APPOINTMENT_MADE]      DATETIME        NULL,
    [REASON_PATIENT_CANCELLED]   VARCHAR (75)    NULL,
    [CHECKED_IN]                 DATETIME        NULL,
    [CANCELLED_BY_IEN]           NUMERIC (21, 3) NULL,
    [CANCELLATION_DATE_TIME]     DATETIME        NULL,
    [NO_SHOW_FLAG]               VARCHAR (30)    NULL,
    [WALK_IN]                    VARCHAR (30)    NULL,
    [METHOD_OF_TRANSIT_IEN]      NUMERIC (21, 3) NULL,
    [THIRD_PARTY_PAYER]          VARCHAR (30)    NULL,
    [ARRIVAL_CATEGORY]           VARCHAR (30)    NULL,
    [RELEASE_CONDITION]          VARCHAR (30)    NULL,
    [DATE_TIME_OF_RELEASE]       DATETIME        NULL,
    [ENCOUNTER_PTR_IEN]          NUMERIC (21, 3) NULL,
    [OUTPATIENT_DISPOSITION_IEN] NUMERIC (21, 3) NULL,
    [REFERRED_TO_IEN]            NUMERIC (21, 3) NULL,
    [ER_ENTRY_NUMBER]            VARCHAR (30)    NULL,
    [PRIORITY]                   VARCHAR (30)    NULL,
    [ADMITTED_TO_IEN]            NUMERIC (21, 3) NULL,
    [SOURCE_OF_ADMISSION_IEN]    NUMERIC (21, 3) NULL,
    [PATIENT_CATEGORY_IEN]       NUMERIC (21, 3) NULL,
    [PROVIDER_SPECIALTY_IEN]     NUMERIC (21, 3) NULL,
    [ATC_CATEGORY_IEN]           NUMERIC (21, 3) NULL,
    [ATC_REQUEST_DATE_TIME]      DATETIME        NULL,
    [WORKLOAD_TYPE]              VARCHAR (30)    NULL,
    [ENROLLING_DMIS_ID_IEN]      NUMERIC (21, 3) NULL,
    [PCM_IEN_IEN]                NUMERIC (21, 3) NULL,
    [PATIENT_ZIP]                VARCHAR (10)    NULL,
    [GEOGRAPHIC_LOCATION_IEN]    NUMERIC (21, 3) NULL,
    [PLACE_OF_EMPLOYMENT]        VARCHAR (54)    NULL,
    [HCDP_IEN]                   NUMERIC (21, 3) NULL
);


GO
CREATE CLUSTERED INDEX [IX_PATIENT_APPOINTMENT_APPOINTMENT_DATE_TIME]
    ON [dbo].[PATIENT_APPOINTMENT]([APPOINTMENT_DATE_TIME] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT_APPOINTMENT_APPOINTMENT_STATUS_IEN]
    ON [dbo].[PATIENT_APPOINTMENT]([APPOINTMENT_STATUS_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT_APPOINTMENT_PROVIDER_IEN]
    ON [dbo].[PATIENT_APPOINTMENT]([PROVIDER_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT_APPOINTMENT_NAME_IEN]
    ON [dbo].[PATIENT_APPOINTMENT]([NAME_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PATIENT_APPOINTMENT_CLINIC_IEN]
    ON [dbo].[PATIENT_APPOINTMENT]([CLINIC_IEN] ASC) WITH (FILLFACTOR = 100);

