CREATE TABLE [dbo].[PATIENT_APPOINTMENT$PROCEDURE] (
    [KEY_SITE]                          NUMERIC (5)     NULL,
    [KEY_PATIENT_APPOINTMENT]           VARCHAR (1)     NULL,
    [KEY_PATIENT_APPOINTMENT$PROCEDURE] VARCHAR (1)     NULL,
    [PROCEDURE_]                        NUMERIC (7, 3)  NULL,
    [PROCEDURE__01_IEN]                 NUMERIC (21, 3) NULL,
    [PROVIDER_IEN]                      NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_PATIENT_APPOINTMENT$PROCEDURE]
    ON [dbo].[PATIENT_APPOINTMENT$PROCEDURE]([KEY_SITE] ASC, [KEY_PATIENT_APPOINTMENT] ASC, [KEY_PATIENT_APPOINTMENT$PROCEDURE] ASC);

