CREATE TABLE [dbo].[PDTS_PROFILE_COLLECTION_F$ACCEPTED_RESPONSE_DETAIL] (
    [KEY_SITE]                                           NUMERIC (5)     NULL,
    [KEY_PDTS_PROFILE_COLLECTION_FILE]                   NUMERIC (12, 3) NULL,
    [KEY_PDTS_PROFILE_COLLECTION_F$ACCEPTED_RESPONSE_DE] NUMERIC (7, 3)  NULL,
    [ACCEPTED_PHARMACY_NAME]                             VARCHAR (25)    NULL,
    [ACCEPTED_PRESCRIPTION_NUMBER]                       NUMERIC (13, 3) NULL,
    [ACCEPTED_DATE_FILLED]                               DATETIME        NULL,
    [ACCEPTED_NEW_REFILL_CODE]                           NUMERIC (8, 3)  NULL,
    [ACCEPTED_NDC_NUMBER]                                NUMERIC (17, 3) NULL,
    [ACCEPTED_DRUG_NAME]                                 VARCHAR (30)    NULL,
    [ACCEPTED_DAYS_SUPPLY]                               NUMERIC (9, 3)  NULL,
    [ACCEPTED_PRESCRIBER_ID]                             VARCHAR (25)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_PDTS_PROFILE_COLLECTION_F$ACCEPTED_RESPONSE_DETAIL]
    ON [dbo].[PDTS_PROFILE_COLLECTION_F$ACCEPTED_RESPONSE_DETAIL]([KEY_SITE] ASC, [KEY_PDTS_PROFILE_COLLECTION_FILE] ASC, [KEY_PDTS_PROFILE_COLLECTION_F$ACCEPTED_RESPONSE_DE] ASC);

