CREATE TABLE [dbo].[PDTS_PROFILE_COLLECTION_FILE] (
    [KEY_SITE]                         NUMERIC (5)     NULL,
    [KEY_PDTS_PROFILE_COLLECTION_FILE] NUMERIC (12, 3) NULL,
    [PATIENT_IEN]                      NUMERIC (21, 3) NULL,
    [PROFILE_COL_FILE_FRWD_PTR_IEN]    NUMERIC (21, 3) NULL,
    [PROFILE_COL_FILE_BKWD_PTR_IEN]    NUMERIC (21, 3) NULL,
    [DATE_TIME_API_CALLED_GIS]         DATETIME        NULL,
    [REQUESTING_PHARMACY_NUMBER]       NUMERIC (16, 3) NULL,
    [REQUEST_OUTPATIENT_SITE_IEN]      NUMERIC (21, 3) NULL,
    [REQUESTED_DATE_FILLED]            DATETIME        NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_PDTS_PROFILE_COLLECTION_FILE]
    ON [dbo].[PDTS_PROFILE_COLLECTION_FILE]([KEY_SITE] ASC, [KEY_PDTS_PROFILE_COLLECTION_FILE] ASC);

