CREATE TABLE [dbo].[POP_HEALTH_ANTIDEPRESSANT] (
    [Last Viewed On]             NVARCHAR (255) NULL,
    [Note]                       NVARCHAR (255) NULL,
    [Status]                     NVARCHAR (255) NULL,
    [ACG RUB]                    NVARCHAR (255) NULL,
    [ACG IBI]                    FLOAT (53)     NULL,
    [ACG Date]                   DATETIME       NULL,
    [Name]                       NVARCHAR (255) NULL,
    [FMP]                        NVARCHAR (255) NULL,
    [DOB]                        DATETIME       NULL,
    [Age]                        FLOAT (53)     NULL,
    [Gender]                     NVARCHAR (255) NULL,
    [BenCat]                     NVARCHAR (255) NULL,
    [PCM Name]                   NVARCHAR (255) NULL,
    [PCM NPI]                    NVARCHAR (255) NULL,
    [Provider Group]             NVARCHAR (255) NULL,
    [Earliest Prescription Date] DATETIME       NULL,
    [Earliest Diagnostic Date]   DATETIME       NULL,
    [Diagnosis Clinic]           NVARCHAR (255) NULL,
    [Diagnosis Location]         NVARCHAR (255) NULL,
    [Source]                     NVARCHAR (255) NULL,
    [Visits]                     FLOAT (53)     NULL,
    [Hospitalizations]           FLOAT (53)     NULL,
    [Trmt Days >=84]             NVARCHAR (255) NULL,
    [Trmt Days >=180]            NVARCHAR (255) NULL,
    [Last Prescription Date]     DATETIME       NULL,
    [Last Prescription Name]     NVARCHAR (255) NULL,
    [Last Days Supplied]         FLOAT (53)     NULL,
    [Next Appt Date]             DATETIME       NULL,
    [Next Appt Clinic]           NVARCHAR (255) NULL,
    [Next Appt Provider]         NVARCHAR (255) NULL,
    [Street 1]                   NVARCHAR (255) NULL,
    [Street 2]                   NVARCHAR (255) NULL,
    [City]                       NVARCHAR (255) NULL,
    [State]                      NVARCHAR (255) NULL,
    [Zip Code]                   NVARCHAR (255) NULL,
    [Country]                    NVARCHAR (255) NULL,
    [Home Phone]                 NVARCHAR (255) NULL,
    [Work Phone]                 NVARCHAR (255) NULL,
    [DMIS]                       NVARCHAR (255) NULL,
    [Service]                    NVARCHAR (255) NULL,
    [Notes Detail]               NVARCHAR (255) NULL,
    [Has Duplicate PCMs]         NVARCHAR (255) NULL,
    [EDIPN]                      NVARCHAR (255) NULL,
    [Last Viewed By]             NVARCHAR (255) NULL
);

