CREATE TABLE [dbo].[POP_HEALTH_BACK_PAIN_ACUTE] (
    [PatientName]   VARCHAR (255) NULL,
    [SponsorSSN]    VARCHAR (255) NULL,
    [FMP]           VARCHAR (255) NULL,
    [DOB]           VARCHAR (255) NULL,
    [Age]           VARCHAR (255) NULL,
    [BenCat]        VARCHAR (255) NULL,
    [PCMName]       VARCHAR (255) NULL,
    [ProviderGroup] VARCHAR (255) NULL,
    [Rank]          VARCHAR (255) NULL,
    [DAFSC]         VARCHAR (255) NULL,
    [Date]          VARCHAR (255) NULL,
    [ICD9Code]      VARCHAR (255) NULL,
    [TotalVisits]   VARCHAR (255) NULL,
    [Street1]       VARCHAR (255) NULL,
    [Street2]       VARCHAR (255) NULL,
    [City]          VARCHAR (255) NULL,
    [State]         VARCHAR (255) NULL,
    [Zip]           VARCHAR (255) NULL,
    [Country]       VARCHAR (255) NULL,
    [HomePhone]     VARCHAR (255) NULL,
    [WorkPhone]     VARCHAR (255) NULL,
    [DMIS]          VARCHAR (255) NULL
);

