CREATE TABLE [dbo].[PRESCRIPTION$FILL_DATES] (
    [KEY_SITE]                    NUMERIC (5)     NULL,
    [KEY_PRESCRIPTION]            NUMERIC (14, 3) NULL,
    [KEY_PRESCRIPTION$FILL_DATES] NUMERIC (8, 3)  NULL,
    [FILL_DATES]                  DATETIME        NULL,
    [LOGGED_BY_IEN]               NUMERIC (21, 3) NULL,
    [OUTPATIENT_SITE_IEN]         NUMERIC (21, 3) NULL,
    [MTF_DIVISION_IEN]            NUMERIC (21, 3) NULL,
    [MEPRS_CODE_IEN]              NUMERIC (21, 3) NULL,
    [ACTION_]                     VARCHAR (30)    NULL,
    [LABEL_PRINT_DATE_TIME]       DATETIME        NULL,
    [DISPENSED_DATE]              DATETIME        NULL
);


GO
CREATE CLUSTERED INDEX [IX_PRESCRIPTION$FILL_DATES_FILL_DATES]
    ON [dbo].[PRESCRIPTION$FILL_DATES]([FILL_DATES] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION$FILL_DATES]
    ON [dbo].[PRESCRIPTION$FILL_DATES]([KEY_PRESCRIPTION$FILL_DATES] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION]
    ON [dbo].[PRESCRIPTION$FILL_DATES]([KEY_PRESCRIPTION] ASC) WITH (FILLFACTOR = 100);

