CREATE TABLE [dbo].[PRESCRIPTION$ACTIVITY_LOG] (
    [KEY_SITE]                      NUMERIC (5)     NULL,
    [KEY_PRESCRIPTION]              NUMERIC (14, 3) NULL,
    [KEY_PRESCRIPTION$ACTIVITY_LOG] NUMERIC (8, 3)  NULL,
    [ACTIVITY_LOG]                  DATETIME        NULL,
    [USER_COMMENTS]                 VARCHAR (100)   NULL,
    [LOGGED_BY_IEN]                 NUMERIC (22, 4) NULL,
    [REMARKS]                       VARCHAR (75)    NULL,
    [PHARMACY_SITE_IEN]             NUMERIC (21, 3) NULL,
    [ASSOCIATED_FILL_NUMBER]        NUMERIC (8, 3)  NULL,
    [REASON_CODE_IEN]               NUMERIC (21, 3) NULL,
    [AUTHORIZING_PROVIDER_IEN]      NUMERIC (21, 3) NULL
);


GO
CREATE CLUSTERED INDEX [IX_PRESCRIPTION$ACTIVITY_lOG_KEY_PRESCRIPTION$ACTIVITY_LOG]
    ON [dbo].[PRESCRIPTION$ACTIVITY_LOG]([KEY_PRESCRIPTION$ACTIVITY_LOG] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PRESCRIPTION$ACTIVITY_LOG_KEY_PRESCRIPTION]
    ON [dbo].[PRESCRIPTION$ACTIVITY_LOG]([KEY_PRESCRIPTION] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_PRESCRIPTION$ACTIVITY_LOG_REASON_CODE_IEN]
    ON [dbo].[PRESCRIPTION$ACTIVITY_LOG]([REASON_CODE_IEN] ASC) WITH (FILLFACTOR = 100);

