CREATE TABLE [dbo].[Productivity] (
    [FY]                   NVARCHAR (50) NULL,
    [FM]                   NVARCHAR (50) NULL,
    [MEPRS4 Code]          NVARCHAR (50) NULL,
    [Tmt DMIS ID]          NVARCHAR (50) NULL,
    [Procedure 1]          NVARCHAR (50) NULL,
    [Procedure 2]          NVARCHAR (50) NULL,
    [Procedure 3]          NVARCHAR (50) NULL,
    [Procedure 4]          NVARCHAR (50) NULL,
    [Provider ID]          NVARCHAR (50) NULL,
    [Sponsor ID]           NVARCHAR (50) NULL,
    [Beneficiary Category] NVARCHAR (50) NULL,
    [Appointment Type]     NVARCHAR (50) NULL,
    [Diagnosis 1]          NVARCHAR (50) NULL,
    [Diagnosis 2]          NVARCHAR (50) NULL,
    [Diagnosis 3]          NVARCHAR (50) NULL,
    [Diagnosis 4]          NVARCHAR (50) NULL,
    [E&M Code]             NVARCHAR (50) NULL,
    [Enrollment Site]      NVARCHAR (50) NULL,
    [FMP]                  NVARCHAR (50) NULL,
    [Service Date]         NVARCHAR (50) NULL,
    [Appt Status Cd]       NVARCHAR (50) NULL,
    [Record ID]            NVARCHAR (50) NULL,
    [Countable Visit]      NVARCHAR (50) NULL,
    [Gender]               NVARCHAR (50) NULL,
    [Encounters]           NVARCHAR (50) NULL,
    [E&M Procedure RVU]    NVARCHAR (50) NULL,
    [Procedure 1 RVU]      NVARCHAR (50) NULL,
    [Procedure 2 RVU]      NVARCHAR (50) NULL,
    [Procedure 3 RVU]      NVARCHAR (50) NULL,
    [Procedure 4 RVU]      NVARCHAR (50) NULL,
    [Historical RVU]       NVARCHAR (50) NULL
);

