CREATE TABLE [dbo].[PROVIDER$PROVIDER_SPECIALTY_S_] (
    [KEY_SITE]                           NUMERIC (5)     NULL,
    [KEY_PROVIDER]                       NUMERIC (11, 3) NULL,
    [KEY_PROVIDER$PROVIDER_SPECIALTY_S_] NUMERIC (8, 3)  NULL,
    [PROVIDER_SPECIALTY_S__IEN]          NUMERIC (21, 3) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_PROVIDER$PROVIDER_SPECIALTY_S_]
    ON [dbo].[PROVIDER$PROVIDER_SPECIALTY_S_]([KEY_SITE] ASC, [KEY_PROVIDER] ASC, [KEY_PROVIDER$PROVIDER_SPECIALTY_S_] ASC);

