CREATE TABLE [dbo].[PROVIDER_SPECIALTY] (
    [KEY_SITE]               NUMERIC (5)    NULL,
    [KEY_PROVIDER_SPECIALTY] NUMERIC (9, 3) NULL,
    [CODE]                   VARCHAR (30)   NULL,
    [DESCRIPTION]            VARCHAR (60)   NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_PROVIDER_SPECIALTY]
    ON [dbo].[PROVIDER_SPECIALTY]([KEY_SITE] ASC, [KEY_PROVIDER_SPECIALTY] ASC);

