CREATE TABLE [dbo].[PROVIDER_CLASS] (
    [KEY_SITE]           NUMERIC (5)     NULL,
    [KEY_PROVIDER_CLASS] NUMERIC (10, 3) NULL,
    [NAME]               VARCHAR (30)    NULL,
    [ABBREV__TITLE]      VARCHAR (5)     NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_PROVIDER_CLASS_KEY_PROVIDER_CLASS]
    ON [dbo].[PROVIDER_CLASS]([KEY_PROVIDER_CLASS] ASC) WITH (FILLFACTOR = 100);

