CREATE TABLE [dbo].[PSAFDB_NDCTBL_20040610] (
    [KEY_SITE]          NUMERIC (5)     NULL,
    [KEY_PSAFDB_NDCTBL] NUMERIC (17, 3) NULL,
    [NUMBER_]           NUMERIC (17, 3) NULL,
    [GCNSEQNO_IEN]      NUMERIC (21, 3) NULL
);

