CREATE TABLE [dbo].[RADIOLOGY_REPORTS$AMENDED_REPORT] (
    [KEY_SITE]                             NUMERIC (5)     NULL,
    [KEY_RADIOLOGY_REPORTS]                NUMERIC (13, 3) NULL,
    [KEY_RADIOLOGY_REPORTS$AMENDED_REPORT] NUMERIC (7, 3)  NULL,
    [AMENDED_DATE_TIME]                    DATETIME        NULL,
    [VERIFIED_DATE_TIME]                   DATETIME        NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_RADIOLOGY_REPORTS$AMENDED_REPORT]
    ON [dbo].[RADIOLOGY_REPORTS$AMENDED_REPORT]([KEY_SITE] ASC, [KEY_RADIOLOGY_REPORTS] ASC, [KEY_RADIOLOGY_REPORTS$AMENDED_REPORT] ASC);

