CREATE TABLE [dbo].[RECORD_TYPES] (
    [KEY_SITE]         NUMERIC (5)    NULL,
    [KEY_RECORD_TYPES] NUMERIC (8, 3) NULL,
    [NAME]             VARCHAR (30)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_RECORD_TYPES_KEY_RECORD_TYPES]
    ON [dbo].[RECORD_TYPES]([KEY_RECORD_TYPES] ASC) WITH (FILLFACTOR = 100);

