CREATE TABLE [dbo].[RECORDS] (
    [KEY_SITE]                       NUMERIC (5)     NULL,
    [KEY_RECORDS]                    NUMERIC (15, 3) NULL,
    [RECORD_NUMBER]                  NUMERIC (15, 3) NULL,
    [ASSOCIATED_ENTITY]              VARCHAR (30)    NULL,
    [ASSOCIATED_ENTITY_IEN]          VARCHAR (15)    NULL,
    [TYPE_OF_RECORD_IEN]             NUMERIC (21, 3) NULL,
    [CURRENT_BORROWER_FILE_ROOM_IEN] NUMERIC (21, 3) NULL,
    [DATE_TIME_CHARGED_TO_BORROWER]  DATETIME        NULL,
    [TYPE_OF_MOVEMENT_IEN]           NUMERIC (21, 3) NULL,
    [DAYS_CHARGED_TO_BORROWER]       NUMERIC (21, 3) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_RECORDS_KEY_RECORDS]
    ON [dbo].[RECORDS]([KEY_RECORDS] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_RECORDS_RECORD_NUMBER]
    ON [dbo].[RECORDS]([RECORD_NUMBER] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_RECORDS_ASSOCIATED_ENTITY_IEN]
    ON [dbo].[RECORDS]([ASSOCIATED_ENTITY_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_RECORDS_TYPE_OF_RECORD_IEN]
    ON [dbo].[RECORDS]([TYPE_OF_RECORD_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_RECORDS_CURRENT_BORROWER_FILE_ROOM_IEN]
    ON [dbo].[RECORDS]([CURRENT_BORROWER_FILE_ROOM_IEN] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_RECORDS_DATE_TIME_CHARGED_TO_BORROWER]
    ON [dbo].[RECORDS]([DATE_TIME_CHARGED_TO_BORROWER] ASC) WITH (FILLFACTOR = 100);

