CREATE TABLE [dbo].[SCHEDULABLE_ENTITY] (
    [KEY_SITE]               NUMERIC (5)     NULL,
    [KEY_SCHEDULABLE_ENTITY] NUMERIC (11, 3) NULL,
    [ENTITY_NAME]            VARCHAR (30)    NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULABLE_ENTITY_KEY_SCHEDULABLE_ENTITY]
    ON [dbo].[SCHEDULABLE_ENTITY]([KEY_SCHEDULABLE_ENTITY] ASC) WITH (FILLFACTOR = 100);

