CREATE TABLE [dbo].[SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES] (
    [KEY_SITE]                                   NUMERIC (5)     NULL,
    [KEY_SCHEDULABLE_ENTITY]                     NUMERIC (11, 3) NULL,
    [KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES] NUMERIC (22, 7) NULL,
    [DATE_TIME]                                  DATETIME        NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES]
    ON [dbo].[SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES]([KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES] ASC) WITH (FILLFACTOR = 100);

