CREATE TABLE [dbo].[SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS] (
    [KEY_SITE]                                           NUMERIC (5)     NULL,
    [KEY_SCHEDULABLE_ENTITY]                             NUMERIC (11, 3) NULL,
    [KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL] NUMERIC (7, 3)  NULL,
    [KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES]         NUMERIC (22, 7) NULL,
    [APPOINTMENT_SLOT]                                   VARCHAR (5)     NULL,
    [APPOINTMENT_TYPE_IEN]                               NUMERIC (21, 3) NULL,
    [CLINIC_IEN]                                         NUMERIC (21, 3) NULL,
    [APPT_SLOT_STATUS]                                   VARCHAR (30)    NULL,
    [PROVIDER_IEN]                                       NUMERIC (21, 3) NULL
);


GO
CREATE CLUSTERED INDEX [IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_MULTIKEYS]
    ON [dbo].[SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS]([KEY_SCHEDULABLE_ENTITY] ASC, [KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES] ASC, [KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL]
    ON [dbo].[SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS]([KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY]
    ON [dbo].[SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS]([KEY_SCHEDULABLE_ENTITY] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES]
    ON [dbo].[SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS]([KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES] ASC) WITH (FILLFACTOR = 100);

