CREATE TABLE [dbo].[SOURCE_OF_ADMISSION] (
    [KEY_SITE]                NUMERIC (5)    NULL,
    [KEY_SOURCE_OF_ADMISSION] NUMERIC (8, 3) NULL,
    [NAME]                    VARCHAR (62)   NULL,
    [CODE]                    VARCHAR (1)    NULL,
    [ACTIVE]                  VARCHAR (30)   NULL,
    [DBA_INACTIVE_FLAG]       VARCHAR (30)   NULL,
    [DEACTIVATION_DATE]       DATETIME       NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_SOURCE_OF_ADMISSION_KEY_SOURCE_OF_ADMISSION]
    ON [dbo].[SOURCE_OF_ADMISSION]([KEY_SOURCE_OF_ADMISSION] ASC) WITH (FILLFACTOR = 100);

