CREATE TABLE [dbo].[STG_PROVIDER_ACTIVITY] (
    [Provider_Ien] NUMERIC (12, 4) NOT NULL,
    [CreatedDate]  DATETIME        CONSTRAINT [DF_STG_PROVIDER_ACTIVITY_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_STG_PROVIDER_ACTIVITY] PRIMARY KEY CLUSTERED ([Provider_Ien] ASC)
);

