CREATE TABLE [dbo].[STG_PATIENT_ACTIVITY] (
    [Patient_Ien] NUMERIC (21, 3) NOT NULL,
    [CreatedDate] DATETIME        CONSTRAINT [DF_STG_PATIENT_ACTIVITY_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_STG_PATIENT_ACTIVITY] PRIMARY KEY CLUSTERED ([Patient_Ien] ASC)
);

