CREATE TABLE [dbo].[STG_MAX_ENROLLMENT] (
    [KEY_NED_PATIENT] NUMERIC (13, 3) NOT NULL,
    [MaxEnr]          NUMERIC (17, 3) NOT NULL,
    [CreatedDate]     DATETIME        CONSTRAINT [DF_STG_MAX_ENROLLMENT_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_STG_MAX_ENROLLMENT] PRIMARY KEY CLUSTERED ([KEY_NED_PATIENT] ASC, [MaxEnr] ASC)
);

