CREATE TABLE [dbo].[WARD_LOCATION] (
    [KEY_SITE]          NUMERIC (5)     NULL,
    [KEY_WARD_LOCATION] NUMERIC (11, 3) NULL,
    [NAME]              VARCHAR (30)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_WARD_LOCATION]
    ON [dbo].[WARD_LOCATION]([KEY_SITE] ASC, [KEY_WARD_LOCATION] ASC);

