CREATE TABLE [dbo].[WARD_LOCATION$ROOM] (
    [KEY_SITE]               NUMERIC (5)     NULL,
    [KEY_WARD_LOCATION]      NUMERIC (11, 3) NULL,
    [KEY_WARD_LOCATION$ROOM] NUMERIC (8, 3)  NULL,
    [ROOM]                   VARCHAR (9)     NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ind_WARD_LOCATION$ROOM]
    ON [dbo].[WARD_LOCATION$ROOM]([KEY_SITE] ASC, [KEY_WARD_LOCATION] ASC, [KEY_WARD_LOCATION$ROOM] ASC);

