CREATE TABLE [dbo].[ASSET_HISTORY] (
    [AssetHistoryId]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [AssetId]              INT            NULL,
    [ModelId]              INT            NULL,
    [PlantAccountPrefix]   VARCHAR (50)   NULL,
    [PlantAccountNumber]   VARCHAR (50)   NULL,
    [NetworkName]          VARCHAR (100)  NULL,
    [SerialNumber]         VARCHAR (50)   NULL,
    [AcquisitionDate]      DATETIME       NULL,
    [MacAddress]           VARCHAR (50)   NULL,
    [Remarks]              VARCHAR (1000) NULL,
    [AssetDesc]            VARCHAR (100)  NULL,
    [WarrantyMonths]       INT            NULL,
    [UnitCost]             MONEY          NULL,
    [EqpMgtBarCode]        VARCHAR (15)   NULL,
    [ReqDocNumber]         VARCHAR (20)   NULL,
    [ProjectId]            INT            NULL,
    [AssetTypeId]          INT            NULL,
    [AssetSubtypeId]       INT            NULL,
    [DepartmentId]         INT            NULL,
    [BuildingId]           INT            NULL,
    [DeckId]               INT            NULL,
    [Room]                 VARCHAR (50)   NULL,
    [MissionCritical]      BIT            NULL,
    [RemoteAccess]         BIT            NULL,
    [OnLoan]               BIT            NULL,
    [LeasedPurchased]      INT            NULL,
    [DispositionId]        INT            NULL,
    [DomainId]             INT            NULL,
    [CreatedBy]            INT            NULL,
    [CreatedDate]          DATETIME       NULL,
    [UpdatedBy]            INT            NULL,
    [UpdatedDate]          DATETIME       NULL,
    [InventoryDate]        DATETIME       NULL,
    [PrinterConfig]        INT            NULL,
    [SharePC]              INT            NULL,
    [MACAddress2]          VARCHAR (50)   NULL,
    [ManufacturerId]       INT            NULL,
    [AudienceId]           BIGINT         NULL,
    [UpdateSourceSystemId] INT            NULL,
    [HistoryDate]          DATETIME       CONSTRAINT [DF_ASSET_HISTORY_HistoryDate] DEFAULT (getdate()) NULL,
    [HistoryBy]            INT            NULL,
    CONSTRAINT [PK_ASSET_HISTORY] PRIMARY KEY CLUSTERED ([AssetHistoryId] ASC)
);

