CREATE TABLE [dbo].[ASSET_ASSIGNMENT] (
    [AssignmentId] INT      IDENTITY (1, 1) NOT NULL,
    [AssetId]      INT      NOT NULL,
    [AssignedTo]   INT      CONSTRAINT [DF_ASSET_ASSIGNMENT_AssignedTo] DEFAULT ((0)) NOT NULL,
    [CreatedDate]  DATETIME CONSTRAINT [DF_ASSET_ASSIGNMENT_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]    INT      CONSTRAINT [DF_ASSET_ASSIGNMENT_CreatedBy] DEFAULT ((0)) NULL,
    [UpdatedDate]  DATETIME CONSTRAINT [DF_ASSET_ASSIGNMENT_UpdatedDate] DEFAULT (getdate()) NULL,
    [UpdatedBy]    INT      CONSTRAINT [DF_ASSET_ASSIGNMENT_UpdatedBy] DEFAULT ((0)) NULL,
    [Inactive]     BIT      CONSTRAINT [DF_ASSET_ASSIGNMENT_Inactive] DEFAULT ((0)) NULL,
    [PrimaryUser]  BIT      CONSTRAINT [DF_ASSET_ASSIGNMENT_PrimaryUser] DEFAULT ((0)) NULL,
    [Favorite]     BIT      CONSTRAINT [DF_ASSET_ASSIGNMENT_Favorite] DEFAULT ((0)) NULL,
    [Usage]        BIGINT   CONSTRAINT [DF_ASSET_ASSIGNMENT_Usage] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ASSET_ASSIGNMENT] PRIMARY KEY CLUSTERED ([AssignmentId] ASC),
    CONSTRAINT [FK_ASSET_ASSIGNMENT_ASSET] FOREIGN KEY ([AssetId]) REFERENCES [dbo].[ASSET] ([AssetId]) ON DELETE CASCADE,
    CONSTRAINT [FK_ASSET_ASSIGNMENT_TECHNICIAN] FOREIGN KEY ([AssignedTo]) REFERENCES [dbo].[TECHNICIAN] ([UserId])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ASSET_ASSIGNMENT_AssetId_AssignedTo]
    ON [dbo].[ASSET_ASSIGNMENT]([AssetId] ASC, [AssignedTo] ASC);


GO
CREATE TRIGGER [dbo].[PrimaryUser] ON [dbo].[ASSET_ASSIGNMENT] 
FOR INSERT, UPDATE
AS
DECLARE @Prim bit

IF UPDATE(PrimaryUser)
BEGIN
	SELECT @Prim = PrimaryUser FROM INSERTED
	IF @Prim = 1
	BEGIN
		UPDATE ASSET_ASSIGNMENT
		SET PrimaryUser = 0 
		WHERE AssetId = (SELECT AssetId FROM INSERTED) 
		AND AssignmentId <> (SELECT AssignmentId FROM INSERTED)
		AND PrimaryUser = 1
	END
END



