CREATE TABLE [dbo].[Pending12JUL11$] (
    [Dept]         NVARCHAR (255) NULL,
    [UIC]          NVARCHAR (255) NULL,
    [BSC]          NVARCHAR (255) NULL,
    [Desig]        NVARCHAR (255) NULL,
    [Rank]         NVARCHAR (255) NULL,
    [PNOBC]        NVARCHAR (255) NULL,
    [SNOBC]        NVARCHAR (255) NULL,
    [SSP1]         NVARCHAR (255) NULL,
    [SSP2]         NVARCHAR (255) NULL,
    [PAQD]         NVARCHAR (255) NULL,
    [Name]         NVARCHAR (255) NULL,
    [SSN4]         NVARCHAR (255) NULL,
    [G]            NVARCHAR (255) NULL,
    [Status]       NVARCHAR (255) NULL,
    [P]            NVARCHAR (255) NULL,
    [Deployed]     FLOAT (53)     NULL,
    [Dwell Days]   NVARCHAR (255) NULL,
    [Dwell]        NVARCHAR (255) NULL,
    [Returned]     NVARCHAR (255) NULL,
    [Dwell Period] NVARCHAR (255) NULL,
    [Days]         NVARCHAR (255) NULL,
    [Deployer]     NVARCHAR (255) NULL,
    [RTN Number]   NVARCHAR (255) NULL,
    [Mission]      NVARCHAR (255) NULL,
    [Mission Name] NVARCHAR (255) NULL,
    [Theater]      NVARCHAR (255) NULL,
    [Deploy]       DATETIME       NULL,
    [Return]       DATETIME       NULL,
    [Platform]     NVARCHAR (255) NULL,
    [A]            NVARCHAR (255) NULL,
    [T]            NVARCHAR (255) NULL,
    [Date]         DATETIME       NULL,
    [PRD]          DATETIME       NULL,
    [EAOS]         DATETIME       NULL,
    [PCS]          NVARCHAR (255) NULL,
    [Deploy1]      NVARCHAR (255) NULL,
    [Notes]        NVARCHAR (255) NULL
);

