CREATE TABLE [dbo].[sessASSET] (
    [AsssetId]           INT            NULL,
    [ModelId]            INT            NULL,
    [ModelDesc]          VARCHAR (50)   NULL,
    [ManufacturerId]     INT            NULL,
    [ManufacturerDesc]   VARCHAR (50)   NULL,
    [PlantAccountPrefix] VARCHAR (50)   NULL,
    [PlantAccountNumber] VARCHAR (50)   NULL,
    [NetworkName]        VARCHAR (100)  NULL,
    [SerialNumber]       VARCHAR (50)   NULL,
    [AcquisitionDate]    DATETIME       NULL,
    [MACAddress]         VARCHAR (50)   NULL,
    [Remarks]            VARCHAR (1000) NULL,
    [AssetDesc]          VARCHAR (100)  NULL,
    [WarrantyMonths]     INT            NULL,
    [UnitCost]           MONEY          NULL,
    [EqpMgtBarCode]      VARCHAR (20)   NULL,
    [ReqDocNumber]       VARCHAR (20)   NULL,
    [ProjectId]          INT            NULL,
    [ProjectDesc]        VARCHAR (50)   NULL,
    [AssetTypeId]        INT            NULL,
    [AssetTypeDesc]      VARCHAR (50)   NULL,
    [AssetSubtypeId]     INT            NULL,
    [AssetSubtypeDesc]   VARCHAR (50)   NULL,
    [AudienceId]         BIGINT         NULL,
    [AudienceDesc]       VARCHAR (50)   NULL,
    [OrgChartCode]       VARCHAR (20)   NULL,
    [BaseId]             INT            NULL,
    [BaseName]           VARCHAR (50)   NULL,
    [BuildingId]         INT            NULL,
    [BuildingDesc]       VARCHAR (50)   NULL,
    [DeckId]             INT            NULL,
    [DeckDesc]           VARCHAR (50)   NULL,
    [Room]               VARCHAR (50)   NULL,
    [MissionCritical]    BIT            NULL,
    [RemoteAccess]       BIT            NULL,
    [OnLoan]             BIT            NULL,
    [LeasedPurchased]    INT            NULL,
    [DispositionId]      INT            NULL,
    [DispositionDesc]    VARCHAR (50)   NULL,
    [DomainId]           INT            NULL,
    [DomainDesc]         VARCHAR (50)   NULL,
    [POCId]              INT            NULL,
    [POCName]            VARCHAR (150)  NULL,
    [CById]              INT            NULL,
    [CByName]            VARCHAR (150)  NULL,
    [CreatedDate]        DATETIME       NULL,
    [UById]              INT            NULL,
    [UByName]            VARCHAR (150)  NULL,
    [UpdatedDate]        DATETIME       NULL,
    [InventoryDate]      DATETIME       NULL,
    [PrinterConfig]      INT            NULL,
    [SharePC]            INT            NULL,
    [SharePCDesc]        VARCHAR (50)   NULL,
    [DisplayName]        VARCHAR (50)   NULL,
    [POCPhone]           VARCHAR (50)   NULL,
    [HistoryDate]        DATETIME       CONSTRAINT [DF_sessASSET_HistoryDate] DEFAULT (getdate()) NULL,
    [TechId]             INT            NULL
);

