CREATE TABLE [dbo].[sessEASIVSummary] (
    [EASIVSummaryId]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [DmisId]                    NVARCHAR (255) NULL,
    [Month]                     NVARCHAR (255) NULL,
    [Year]                      NVARCHAR (255) NULL,
    [ParentDmisId]              NVARCHAR (255) NULL,
    [Uic]                       NVARCHAR (255) NULL,
    [Fcc]                       NVARCHAR (255) NULL,
    [Supe]                      NVARCHAR (255) NULL,
    [NationalIdentifier]        NVARCHAR (255) NULL,
    [FullName]                  NVARCHAR (255) NULL,
    [EmployeeNumber]            NVARCHAR (255) NULL,
    [EmpAssignStartDate]        NVARCHAR (255) NULL,
    [EmpAssignEndDate]          NVARCHAR (255) NULL,
    [EmpAssignOrganizationName] NVARCHAR (255) NULL,
    [EmpAsgUic]                 NVARCHAR (255) NULL,
    [EmpAsgOrgDmisId]           NVARCHAR (255) NULL,
    [EmpAsgParentDmisId]        NVARCHAR (255) NULL,
    [EmpAsgFcc]                 NVARCHAR (255) NULL,
    [EmpPeopleGrpOrgName]       NVARCHAR (255) NULL,
    [PeopleGroupOrgDmisId]      NVARCHAR (255) NULL,
    [PeopleGroupUic]            NVARCHAR (255) NULL,
    [PeopleGroupParentDmisId]   NVARCHAR (255) NULL,
    [PeopleGroupFcc]            NVARCHAR (255) NULL,
    [PeopleGroupLoanedTimeFcc]  NVARCHAR (255) NULL,
    [PgSupe]                    NVARCHAR (255) NULL,
    [PersonTypeId]              NVARCHAR (255) NULL,
    [Service]                   NVARCHAR (255) NULL,
    [Grade]                     NVARCHAR (255) NULL,
    [ContractorType]            NVARCHAR (255) NULL,
    [LocalNationalType]         NVARCHAR (255) NULL,
    [ReserveType]               NVARCHAR (255) NULL,
    [ForeignMilitary]           NVARCHAR (255) NULL,
    [NonDodCivilian]            NVARCHAR (255) NULL,
    [Country]                   NVARCHAR (255) NULL,
    [Thcsrr]                    NVARCHAR (255) NULL,
    [SkillType]                 NVARCHAR (255) NULL,
    [SkillTypeSuffix]           NVARCHAR (255) NULL,
    [CommercialActReas]         NVARCHAR (255) NULL,
    [Suoc]                      NVARCHAR (255) NULL,
    [ProjectType]               NVARCHAR (255) NULL,
    [PersonnelCategory]         NVARCHAR (255) NULL,
    [ProjectNo]                 NVARCHAR (255) NULL,
    [ProjectName]               NVARCHAR (255) NULL,
    [TaskNumber]                NVARCHAR (255) NULL,
    [TaskName]                  NVARCHAR (255) NULL,
    [TaskUic]                   NVARCHAR (255) NULL,
    [TaskServiceType]           NVARCHAR (255) NULL,
    [TaskDmisId]                NVARCHAR (255) NULL,
    [TaskFcc]                   NVARCHAR (255) NULL,
    [TaskSupe]                  NVARCHAR (255) NULL,
    [ProjectParentUic]          NVARCHAR (255) NULL,
    [ProjectParentDmisId]       NVARCHAR (255) NULL,
    [SourceOfFunds]             NVARCHAR (255) NULL,
    [DutyIndicator]             NVARCHAR (255) NULL,
    [Bsl]                       NVARCHAR (255) NULL,
    [Suee]                      NVARCHAR (255) NULL,
    [AvailSalExpSUM]            NVARCHAR (255) NULL,
    [NonAvailSalExpSUM]         NVARCHAR (255) NULL,
    [AvailableFteSUM]           NVARCHAR (255) NULL,
    [NonAvailSickHospFteSUM]    NVARCHAR (255) NULL,
    [NonAvailLeaveFteSUM]       NVARCHAR (255) NULL,
    [NonAvailOthFteSUM]         NVARCHAR (255) NULL,
    [AvailHoursSUM]             NVARCHAR (255) NULL,
    [NonAvailHospSickHoursSUM]  NVARCHAR (255) NULL,
    [NonAvailLeaveHoursSUM]     NVARCHAR (255) NULL,
    [NonAvailOthHoursSUM]       NVARCHAR (255) NULL,
    [CreatedDate]               DATETIME       CONSTRAINT [DF_sessEASIVSummary_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]                 INT            CONSTRAINT [DF_sessEASIVSummary_CreatedBy] DEFAULT ((0)) NULL,
    [IsProcessed]               BIT            CONSTRAINT [DF_sessEASIVSummary_IsProcessed] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_sessEASIVSummary] PRIMARY KEY CLUSTERED ([EASIVSummaryId] ASC)
);

