CREATE TABLE [dbo].[TECHNICIAN_HISTORY] (
    [TechnicianHistoryId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [UserId]              INT           NULL,
    [UFName]              VARCHAR (50)  NULL,
    [ULName]              VARCHAR (50)  NULL,
    [UMName]              VARCHAR (50)  NULL,
    [Title]               VARCHAR (50)  NULL,
    [EMailAddress]        VARCHAR (250) NULL,
    [Location]            VARCHAR (100) NULL,
    [UPhone]              VARCHAR (50)  NULL,
    [Extension]           VARCHAR (10)  NULL,
    [Comments]            TEXT          NULL,
    [UPager]              VARCHAR (50)  NULL,
    [AltPhone]            VARCHAR (50)  NULL,
    [LoginId]             NVARCHAR (25) NULL,
    [CreatedDate]         DATETIME      NULL,
    [CreatedBy]           INT           NULL,
    [UpdatedDate]         DATETIME      NULL,
    [UpdatedBy]           INT           NULL,
    [Inactive]            BIT           NULL,
    [SSN]                 VARCHAR (11)  NULL,
    [BilletId]            INT           NULL,
    [RankId]              INT           NULL,
    [AudienceId]          BIGINT        NULL,
    [distinguishedName]   VARCHAR (255) NULL,
    [AutoUpdatedDate]     DATETIME      NULL,
    [ServiceAccount]      BIT           NULL,
    [DOB]                 DATETIME      NULL,
    [Rate]                VARCHAR (15)  NULL,
    [MedStuYr]            VARCHAR (20)  NULL,
    [OtherStu]            VARCHAR (50)  NULL,
    [EAOS_PRD]            DATETIME      NULL,
    [Sex]                 VARCHAR (1)   NULL,
    [CitizenshipId]       INT           NULL,
    [SourceSystemId]      INT           NULL,
    [NMCIEMail]           VARCHAR (100) NULL,
    [Address1]            VARCHAR (100) NULL,
    [Address2]            VARCHAR (100) NULL,
    [City]                VARCHAR (50)  NULL,
    [State]               VARCHAR (2)   NULL,
    [Zip]                 VARCHAR (10)  NULL,
    [DesignationId]       INT           NULL,
    [PreviousDutyStation] VARCHAR (50)  NULL,
    [ExpectedEndDate]     DATETIME      NULL,
    [ContractorCompany]   VARCHAR (50)  NULL,
    [ContractNumber]      VARCHAR (50)  NULL,
    [HealthcareStatusId]  INT           NULL,
    [BaseId]              INT           NULL,
    [NetworkAccess]       BIT           NULL,
    [OutlookExchange]     BIT           NULL,
    [EthnicityId]         INT           NULL,
    [DisplayName]         VARCHAR (150) NULL,
    [CheckInDate]         DATETIME      NULL,
    [EffectiveDate]       DATETIME      NULL,
    [SortOrder]           INT           NULL,
    [ComponentId]         INT           NULL,
    [Suffix]              VARCHAR (6)   NULL,
    [ADExpiresDate]       VARCHAR (50)  NULL,
    [ADLoginDate]         VARCHAR (50)  NULL,
    [ADUpdatedDate]       DATETIME      NULL,
    [LB]                  BIT           NULL,
    [PSQ]                 BIT           NULL,
    [LBDate]              DATETIME      NULL,
    [PSQDate]             DATETIME      NULL,
    [LBBy]                INT           NULL,
    [PSQBy]               INT           NULL,
    [DoNotDisplay]        BIT           NULL,
    [Supervisor]          VARCHAR (150) NULL,
    [IsAimExcetpion]      BIT           NULL,
    [AIMVersion]          VARCHAR (50)  NULL,
    [Deployed]            BIT           NULL,
    [EducationLevelId]    INT           NULL,
    [Prefix]              VARCHAR (10)  NULL,
    [EmployeeNumber]      INT           NULL,
    [HomePhone]           VARCHAR (50)  NULL,
    [CellPhone]           VARCHAR (50)  NULL,
    [DoDEDI]              NVARCHAR (10) NULL,
    [BloodTypeId]         INT           NULL,
    [CountryofBirthId]    INT           NULL,
    [HistoryDate]         DATETIME      CONSTRAINT [DF_TECHNICIAN_HISTORY_HistoryDate] DEFAULT (getdate()) NULL,
    [HistoryBy]           INT           CONSTRAINT [DF_TECHNICIAN_HISTORY_HistoryBy] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TECHNICIAN_HISTORY] PRIMARY KEY CLUSTERED ([TechnicianHistoryId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_TECHNICIAN_HISTORY_UserId]
    ON [dbo].[TECHNICIAN_HISTORY]([UserId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TECHNICIAN_HISTORY_HistoryDate]
    ON [dbo].[TECHNICIAN_HISTORY]([HistoryDate] ASC);

