CREATE TABLE [dbo].[TICKET_HISTORY] (
    [TicketHistoryId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [TicketId]        INT             NULL,
    [TicketNumber]    VARCHAR (50)    NULL,
    [ProblemTypeId]   INT             NULL,
    [SystemNameId]    INT             NULL,
    [PatientImpact]   BIT             NULL,
    [PlantAccountNum] VARCHAR (50)    NULL,
    [SoftwareId]      INT             NULL,
    [TicketLocation]  VARCHAR (50)    NULL,
    [Comments]        TEXT            NULL,
    [CreatedFor]      INT             NULL,
    [CreatedDate]     DATETIME        NULL,
    [AssignedBy]      INT             NULL,
    [AssignedDate]    DATETIME        NULL,
    [StatusId]        INT             NULL,
    [ClosedDate]      DATETIME        NULL,
    [ClosedBy]        INT             NULL,
    [CustomerName]    VARCHAR (50)    NULL,
    [UpdatedDate]     DATETIME        NULL,
    [UpdatedBy]       INT             NULL,
    [OpenDate]        DATETIME        NULL,
    [PriorityId]      INT             NULL,
    [EstimatedHours]  DECIMAL (18, 2) NULL,
    [AudienceId]      BIGINT          NULL,
    [CreatedBy]       INT             NULL,
    [HistoryDate]     DATETIME        CONSTRAINT [DF_TICKET_HISTORY_HistoryDate] DEFAULT (getdate()) NULL,
    [HistoryBy]       INT             CONSTRAINT [DF_TICKET_HISTORY_HistoryBy] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_TICKET_HISTORY] PRIMARY KEY CLUSTERED ([TicketHistoryId] ASC)
);

