CREATE TABLE [dbo].[xxx20141120Inventory] (
    [Network Name]     NVARCHAR (255) NULL,
    [PA Number]        NVARCHAR (255) NULL,
    [Model ]           NVARCHAR (255) NULL,
    [Manufacturer]     NVARCHAR (255) NULL,
    [Prefix]           NVARCHAR (255) NULL,
    [Serial Number]    NVARCHAR (255) NULL,
    [Acquisition Date] NVARCHAR (255) NULL,
    [Mac Address]      NVARCHAR (255) NULL,
    [Remarks]          NVARCHAR (255) NULL,
    [Asset Desc]       NVARCHAR (255) NULL,
    [F11]              NVARCHAR (255) NULL,
    [Warranty Months]  FLOAT (53)     NULL,
    [Unit Cost]        FLOAT (53)     NULL,
    [Eqp Mgt Bar Code] NVARCHAR (255) NULL,
    [Req Doc Number]   NVARCHAR (255) NULL,
    [Project]          NVARCHAR (255) NULL,
    [Asset Type]       NVARCHAR (255) NULL,
    [Asset Sub Type]   NVARCHAR (255) NULL,
    [Department]       NVARCHAR (255) NULL,
    [Org Chart Code]   NVARCHAR (255) NULL,
    [Base]             NVARCHAR (255) NULL,
    [Building]         NVARCHAR (255) NULL,
    [Deck]             NVARCHAR (255) NULL,
    [Room]             NVARCHAR (255) NULL,
    [Mission Critical] BIT            NOT NULL,
    [Remote Access]    BIT            NOT NULL,
    [On Loan]          BIT            NOT NULL,
    [Leased Purchased] FLOAT (53)     NULL,
    [Disposition]      NVARCHAR (255) NULL,
    [Domain]           NVARCHAR (255) NULL,
    [POC Name]         NVARCHAR (255) NULL,
    [POC Phone]        NVARCHAR (255) NULL,
    [Created By]       NVARCHAR (255) NULL,
    [Created Date]     NVARCHAR (255) NULL,
    [Last Updated By]  NVARCHAR (255) NULL,
    [Updated Date]     NVARCHAR (255) NULL,
    [Inventory Date]   NVARCHAR (255) NULL,
    [Printer Config]   FLOAT (53)     NULL,
    [Share PC]         FLOAT (53)     NULL,
    [Share PC Desc]    NVARCHAR (255) NULL,
    [Display Name]     NVARCHAR (255) NULL
);

