CREATE TABLE [dbo].[xxx20150226Inventory] (
    [ASSET TYPE]      NVARCHAR (255) NULL,
    [SUB TYPE]        NVARCHAR (255) NULL,
    [MANUFACTURER]    NVARCHAR (255) NULL,
    [MODEL]           NVARCHAR (255) NULL,
    [ECN/MAC ADDRESS] NVARCHAR (255) NULL,
    [SERIAL NUMBER]   NVARCHAR (255) NULL,
    [PLANT NUMBER]    NVARCHAR (255) NULL,
    [PLANT PREFIX]    NVARCHAR (255) NULL,
    [DISPOSITION]     NVARCHAR (255) NULL,
    [BASE]            NVARCHAR (255) NULL,
    [BUILDING]        NVARCHAR (255) NULL,
    [DECK]            NVARCHAR (255) NULL,
    [DEPARTMENT]      NVARCHAR (255) NULL,
    [ROOM]            NVARCHAR (255) NULL,
    [PRIMARY USER]    NVARCHAR (255) NULL,
    [WARR MONTHS]     NVARCHAR (255) NULL,
    [UNIT COST]       MONEY          NULL,
    [PROJECT]         NVARCHAR (255) NULL,
    [F19]             NVARCHAR (255) NULL
);

