CREATE TABLE [dbo].[xxx20160202Inventory] (
    [ASSET TYPE]    NVARCHAR (255) NULL,
    [SUB TYPE]      NVARCHAR (255) NULL,
    [MANUFACTURER]  NVARCHAR (255) NULL,
    [PLANT NUMBER]  FLOAT (53)     NULL,
    [PLANT PREFIX]  NVARCHAR (255) NULL,
    [MODEL]         NVARCHAR (255) NULL,
    [SERIAL NUMBER] NVARCHAR (255) NULL,
    [DISPOSITION]   NVARCHAR (255) NULL,
    [NETWORK NAME]  NVARCHAR (255) NULL,
    [BASE]          NVARCHAR (255) NULL,
    [DEPARTMENT]    NVARCHAR (255) NULL,
    [BUILDING]      FLOAT (53)     NULL,
    [ROOM]          FLOAT (53)     NULL,
    [DECK]          NVARCHAR (255) NULL,
    [PROJECT]       NVARCHAR (255) NULL,
    [PRIMARY USER]  NVARCHAR (255) NULL,
    [UNIT COST]     MONEY          NULL,
    [WARR MONTHS]   FLOAT (53)     NULL,
    [ECN]           FLOAT (53)     NULL,
    [F20]           NVARCHAR (255) NULL
);

