CREATE TABLE [dbo].[xxx20130709Inventory] (
    [ASSET TYPE]   NVARCHAR (255) NULL,
    [SUB TYPE]     NVARCHAR (255) NULL,
    [MNFTR]        NVARCHAR (255) NULL,
    [MODEL]        NVARCHAR (255) NULL,
    [SERIAL #]     NVARCHAR (255) NULL,
    [ECN]          NVARCHAR (255) NULL,
    [PLANT #]      NVARCHAR (255) NULL,
    [PRIMARY USER] NVARCHAR (255) NULL,
    [PLANT PREFIX] NVARCHAR (255) NULL,
    [DISPOSITION]  NVARCHAR (255) NULL,
    [NETWORK NAME] NVARCHAR (255) NULL,
    [BASE]         NVARCHAR (255) NULL,
    [BLDG]         NVARCHAR (50)  NULL,
    [ROOM]         NVARCHAR (255) NULL,
    [DECK]         NVARCHAR (255) NULL,
    [DEPT]         NVARCHAR (255) NULL,
    [PROJET]       NVARCHAR (255) NULL,
    [UNIT COST]    MONEY          NULL
);

