CREATE TABLE [dbo].[xxx20140620Inventory] (
    [ASSET TYPE]   NVARCHAR (255) NULL,
    [SUB TYPE]     NVARCHAR (255) NULL,
    [MNFTR]        NVARCHAR (255) NULL,
    [MODEL]        NVARCHAR (255) NULL,
    [SERIAL #]     NVARCHAR (255) NULL,
    [ECN]          NVARCHAR (255) NULL,
    [PLANT #]      FLOAT (53)     NULL,
    [PRIMARY USER] NVARCHAR (255) NULL,
    [PLANT PREFIX] NVARCHAR (255) NULL,
    [DISPOSITION]  NVARCHAR (255) NULL,
    [NETWORK NAME] NVARCHAR (255) NULL,
    [BASE]         NVARCHAR (255) NULL,
    [BLDG]         FLOAT (53)     NULL,
    [ROOM]         NVARCHAR (255) NULL,
    [DECK]         NVARCHAR (255) NULL,
    [DEPT]         NVARCHAR (255) NULL,
    [PROJECT]      NVARCHAR (255) NULL,
    [WARR MONTHS]  FLOAT (53)     NULL,
    [UNIT COST]    MONEY          NULL
);

