

create PROCEDURE [dbo].[procENET_sessEASIVSummary_Insert]
(
	@dmis varchar(255),
    @mth varchar(255),
    @yr varchar(255),
    @pdmis varchar(255),
    @uic varchar(255),
    @fcc varchar(255),
    @supe varchar(255),
    @ni varchar(255),
    @fnam varchar(255),
    @enum varchar(255),
    @easd varchar(255),
    @eaed varchar(255),
    @eaon varchar(255),
    @eau varchar(255),
    @eaod varchar(255),
    @eapd varchar(255),
    @eaf varchar(255),
    @epgon varchar(255),
    @pgod varchar(255),
    @pgu varchar(255),
    @pgpd varchar(255),
    @pgf varchar(255),
    @pgltf varchar(255),
    @psup varchar(255),
    @ptyp varchar(255),
    @svc varchar(255),
    @grd varchar(255),
    @ctyp varchar(255),
    @lntyp varchar(255),
    @rtyp varchar(255),
    @fmil varchar(255),
    @ndciv varchar(255),
    @ctry varchar(255),
    @thc varchar(255),
    @styp varchar(255),
    @styps varchar(255),
    @car varchar(255),
    @suoc varchar(255),
    @prtyp varchar(255),
    @pcat varchar(255),
    @pno varchar(255),
    @pnam varchar(255),
    @tnum varchar(255),
    @tnam varchar(255),
    @tuic varchar(255),
    @tstyp varchar(255),
    @tdmis varchar(255),
    @tfcc varchar(255),
    @tsup varchar(255),
    @ppuic varchar(255),
    @ppdmis varchar(255),
    @sof varchar(255),
    @di varchar(255),
    @bsl varchar(255),
    @suee varchar(255),
    @ases varchar(255),
    @nases varchar(255),
    @afs varchar(255),
    @nashfs varchar(255),
    @nalfs varchar(255),
    @naofs varchar(255),
    @ahs varchar(255),
    @nahshs varchar(255),
    @nalhs varchar(255),
    @naohs varchar(255),
    @cby int
)
AS
BEGIN
	
	SET NOCOUNT ON;

    INSERT INTO sessEASIVSummary
		(
		DmisId, 
		[Month], 
		[Year], 
		ParentDmisId, 
		Uic, 
		Fcc, 
		Supe, 
		NationalIdentifier, 
		FullName, 
		EmployeeNumber, 
		EmpAssignStartDate, 
        EmpAssignEndDate, 
        EmpAssignOrganizationName, 
        EmpAsgUic, 
        EmpAsgOrgDmisId, 
        EmpAsgParentDmisId, 
        EmpAsgFcc, 
        EmpPeopleGrpOrgName, 
		PeopleGroupOrgDmisId, 
		PeopleGroupUic, 
		PeopleGroupParentDmisId, 
		PeopleGroupFcc, 
		PeopleGroupLoanedTimeFcc, 
		PgSupe, 
		PersonTypeId, 
		[Service], 
		Grade, 
		ContractorType, 
		LocalNationalType, 
		ReserveType, 
		ForeignMilitary, 
		NonDodCivilian, 
		Country, 
		Thcsrr, 
		SkillType, 
		SkillTypeSuffix, 
		CommercialActReas, 
		Suoc, 
		ProjectType, 
		PersonnelCategory, 
		ProjectNo, 
		ProjectName, 
		TaskNumber, 
		TaskName, 
		TaskUic, 
		TaskServiceType, 
		TaskDmisId, 
		TaskFcc, 
		TaskSupe, 
		ProjectParentUic, 
		ProjectParentDmisId, 
		SourceOfFunds, 
		DutyIndicator, 
		Bsl, 
		Suee, 
		AvailSalExpSUM, 
		NonAvailSalExpSUM, 
		AvailableFteSUM, 
		NonAvailSickHospFteSUM, 
		NonAvailLeaveFteSUM, 
		NonAvailOthFteSUM, 
		AvailHoursSUM, 
		NonAvailHospSickHoursSUM, 
		NonAvailLeaveHoursSUM, 
		NonAvailOthHoursSUM, 
		CreatedBy
		)
	VALUES
		(
		@dmis ,
		@mth ,
		@yr ,
		@pdmis ,
		@uic ,
		@fcc ,
		@supe ,
		@ni ,
		@fnam ,
		@enum ,
		@easd ,
		@eaed ,
		@eaon ,
		@eau ,
		@eaod ,
		@eapd ,
		@eaf ,
		@epgon ,
		@pgod ,
		@pgu ,
		@pgpd ,
		@pgf ,
		@pgltf ,
		@psup ,
		@ptyp ,
		@svc ,
		@grd ,
		@ctyp ,
		@lntyp ,
		@rtyp ,
		@fmil ,
		@ndciv ,
		@ctry ,
		@thc ,
		@styp ,
		@styps ,
		@car ,
		@suoc ,
		@prtyp ,
		@pcat ,
		@pno,
		@pnam ,
		@tnum ,
		@tnam ,
		@tuic ,
		@tstyp ,
		@tdmis ,
		@tfcc ,
		@tsup ,
		@ppuic ,
		@ppdmis ,
		@sof ,
		@di ,
		@bsl ,
		@suee ,
		@ases ,
		@nases ,
		@afs ,
		@nashfs ,
		@nalfs ,
		@naofs ,
		@ahs ,
		@nahshs ,
		@nalhs ,
		@naohs ,
		@cby 
		)
END


