CREATE PROCEDURE [dbo].[upAssetUpdate]
(
	@pre varchar(50),
	@num varchar(50),
	@serial varchar(50),
	@mod int,
	@pro int,
	@atyp int,
	@disp int,
	@net varchar(100),
	@bldg int,
	@deck int,
	@dept int,
	@room varchar(50),
	@acq datetime,
	@unit money,
	@warr int,
	@bar varchar(20),
	@req varchar(20),
	@lease int,
	@miss bit,
	@loan bit,
	@remote bit,
	@sub int,
	@mac varchar(50),
	@remark varchar(1000),
	@udate datetime,
	@uby int,
	@ast int
)
AS
UPDATE ASSET 
        SET PlantAccountPrefix = @pre, 
        PlantAccountNumber = @num, 
        SerialNumber = @serial, 
        ModelId = @mod, 
        ProjectId = @pro, 
        AssetTypeId = @atyp, 
        DispositionId = @disp, 
        NetworkName = @net, 
        BuildingId = @bldg, 
        DeckId = @deck, 
        DepartmentId = @dept, 
        Room = @room, 
        AcquisitionDate = @acq, 
        UnitCost = @unit, 
        WarrantyMonths = @warr, 
        EqpMgtBarCode = @bar, 
        ReqDocNumber = @req, 
        LeasedPurchased = @lease, 
        MissionCritical = @miss, 
        OnLoan = @loan, 
        RemoteAccess = @remote, 
        AssetSubTypeId = @sub, 
        MACAddress = @mac, 
        Remarks = @remark, 
        UpdatedDate = @udate, 
        UpdatedBy = @uby 
        WHERE AssetId = @ast;
