CREATE LOGIN [PORTAL]
    WITH PASSWORD = N'qeTlo_nngomf8uhrhJmfbvO5msFT7_&#$!~<kLd|lnbzvxU<', SID = 0xCB3B9F60C053284A8DBEFEDC8AED68E4, DEFAULT_DATABASE = [CLINICAL_PORTAL], DEFAULT_LANGUAGE = [us_english];

