CREATE TABLE [dbo].[ACCESS_TO_CARE_HISTORY] (
    [AccessToCareHistoryId]    BIGINT         IDENTITY (1, 1) NOT NULL,
    [LocationName]             NVARCHAR (20)  NULL,
    [ClinicName]               NVARCHAR (36)  NULL,
    [LocationId]               BIGINT         NULL,
    [ProviderId]               BIGINT         NULL,
    [ProviderName]             NVARCHAR (40)  NULL,
    [AppointmentDateTime]      DATETIME       NULL,
    [AppointmentDescription]   NVARCHAR (30)  NULL,
    [AppointmentDate]          DATE           NULL,
    [AppointmentDateString]    NVARCHAR (10)  NULL,
    [AppointmentTimeString]    NVARCHAR (5)   NULL,
    [AppointmentType]          NVARCHAR (30)  NULL,
    [TotalOpen]                INT            NULL,
    [TotalFrozen]              INT            NULL,
    [TotalCancelled]           INT            NULL,
    [TotalBooked]              INT            NULL,
    [TotalWait]                INT            NULL,
    [TotalLocked]              INT            NULL,
    [ThirdNextAvailAcute]      DATETIME       NULL,
    [HoursDiffAcute]           INT            NULL,
    [ThirdNextAvailRoutine]    DATETIME       NULL,
    [HoursDiffRoutine]         INT            NULL,
    [ThirdNextAvailSpecial]    DATETIME       NULL,
    [HoursDiffSpecial]         INT            NULL,
    [ThirdNextAvailWellness]   DATETIME       NULL,
    [HoursDiffWellness]        INT            NULL,
    [LastAppointment]          DATETIME       NULL,
    [DaysScheduledForward]     INT            NULL,
    [HoursDivvAcuteDecimal]    DECIMAL (5, 2) NULL,
    [HoursDiffRoutineDecimal]  DECIMAL (5, 2) NULL,
    [HoursDiffSpecialDecimal]  DECIMAL (5, 2) NULL,
    [HoursDiffWellnessDecimal] DECIMAL (5, 2) NULL,
    [CreatedDate]              DATETIME       CONSTRAINT [DF_ACCESS_TO_CARE_HISTORY_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ACCESS_TO_CARE_HISTORY] PRIMARY KEY CLUSTERED ([AccessToCareHistoryId] ASC)
);

