CREATE TABLE [dbo].[DIAGNOSIS_CONVERSION] (
    [ICD9Id]      BIGINT   NOT NULL,
    [ICD10Id]     BIGINT   NOT NULL,
    [CreatedDate] DATETIME CONSTRAINT [DF_DIAGNOSIS_CONVERSION_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_DIAGNOSIS_CONVERSION] PRIMARY KEY CLUSTERED ([ICD9Id] ASC, [ICD10Id] ASC)
);

