CREATE TABLE [dbo].[DM_ASTHMA_ISC_DRUG_LOOKUP] (
    [ICSDrugId]    BIGINT        NOT NULL,
    [ICSDrugDesc]  NVARCHAR (41) NOT NULL,
    [ICSNDCNumber] NVARCHAR (15) NULL,
    [CreatedDate]  DATETIME      CONSTRAINT [DF_DM_ASTHMA_ISC_DRUG_LOOKUP_CreatedDate] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_DM_ASTHMA_ISC_DRUG_LOOKUP] PRIMARY KEY CLUSTERED ([ICSDrugId] ASC)
);

