CREATE TABLE [dbo].[PATIENT_ENCOUNTER_DETAIL_CODE] (
    [PatientEncounterId]  BIGINT   NOT NULL,
    [AppointmentDetailId] BIGINT   NOT NULL,
    [CreatedDate]         DATETIME CONSTRAINT [DF_PATIENT_ENCOUNTER_DETAIL_CODE_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_PATIENT_ENCOUNTER_DETAIL_CODE] PRIMARY KEY CLUSTERED ([PatientEncounterId] ASC, [AppointmentDetailId] ASC),
    CONSTRAINT [FK_PATIENT_ENCOUNTER_DETAIL_CODE_APPOINTMENT_DETAIL_CODE] FOREIGN KEY ([AppointmentDetailId]) REFERENCES [dbo].[APPOINTMENT_DETAIL_CODE] ([AppointmentDetailId]),
    CONSTRAINT [FK_PATIENT_ENCOUNTER_DETAIL_CODE_PATIENT_ENCOUNTER] FOREIGN KEY ([PatientEncounterId]) REFERENCES [dbo].[PATIENT_ENCOUNTER] ([PatientEncounterId])
);

