CREATE TABLE [dbo].[PCM_EXCEPTION] (
    [PCMExceptionId] BIGINT   NOT NULL,
    [CreatedDate]    DATETIME CONSTRAINT [DF_PCM_EXCEPTION_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_PCM_EXCEPTION] PRIMARY KEY CLUSTERED ([PCMExceptionId] ASC)
);

