CREATE TABLE [dbo].[RADIOLOGY_IN_GROUP] (
    [RadiologyId]        BIGINT   NOT NULL,
    [RadiologyInGroupId] BIGINT   NOT NULL,
    [CreatedDate]        DATETIME CONSTRAINT [DF_RADIOLOGY_IN_GROUP_CreatedDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_RADIOLOGY_IN_GROUP] PRIMARY KEY CLUSTERED ([RadiologyId] ASC, [RadiologyInGroupId] ASC),
    CONSTRAINT [FK_RADIOLOGY_IN_GROUP_RADIOLOGY] FOREIGN KEY ([RadiologyId]) REFERENCES [dbo].[RADIOLOGY] ([RadiologyId]),
    CONSTRAINT [FK_RADIOLOGY_IN_GROUP_RADIOLOGY1] FOREIGN KEY ([RadiologyInGroupId]) REFERENCES [dbo].[RADIOLOGY] ([RadiologyId])
);

