CREATE TABLE [dbo].[xxx20161018_ORDER] (
    [ORDER_IEN]                NUMERIC (20, 3) NULL,
    [ORDERING_PROVIDER_IEN]    NUMERIC (12, 4) NULL,
    [ORDERING_PROVIDER_NAME]   VARCHAR (40)    NULL,
    [REQUESTING_PROVIDER_IEN]  NUMERIC (12, 4) NULL,
    [REQUESTING_PROVIDER_NAME] VARCHAR (40)    NULL,
    [ORDER_DATE_TIME]          DATETIME        NULL,
    [PATIENT_LOCATION_IEN]     NUMERIC (22, 4) NULL,
    [RADIOLOGY_EXAM_IEN]       NUMERIC (21, 3) NULL,
    [RADIOLOGY_EXAM_DESC]      VARCHAR (60)    NULL,
    [ORDER_COMMENTS]           VARCHAR (1000)  NULL
);

