CREATE TABLE [dbo].[CHKMASTER_20080319] (
    [FIRSTNAME]        NVARCHAR (30) NULL,
    [LASTNAME]         NVARCHAR (30) NULL,
    [MI]               NVARCHAR (2)  NULL,
    [SSN]              NVARCHAR (11) NULL,
    [RANKRATE]         NVARCHAR (10) NULL,
    [DATEOFBIRTH]      DATETIME      NULL,
    [EAOSPRD]          DATETIME      NULL,
    [CORPS]            NVARCHAR (3)  NULL,
    [STATUS]           NVARCHAR (20) NULL,
    [MedStuYr]         NVARCHAR (20) NULL,
    [OtherStu]         NVARCHAR (50) NULL,
    [NETWORKACC]       NVARCHAR (3)  NULL,
    [OUTLKEXCH]        NVARCHAR (3)  NULL,
    [WORKCNT]          NVARCHAR (30) NULL,
    [WORKTITLE]        NVARCHAR (50) NULL,
    [WORKCNTPHONE]     NVARCHAR (30) NULL,
    [ACCESSCODE]       NVARCHAR (20) NULL,
    [VERIFYCODE]       NVARCHAR (20) NULL,
    [CHKID]            INT           IDENTITY (1, 1) NOT NULL,
    [CERTIFY]          TINYINT       NULL,
    [CERTIFYDATE]      DATETIME      NULL,
    [CHKOUTDATE]       DATETIME      NULL,
    [TITLE]            NVARCHAR (10) NULL,
    [SiteID]           INT           CONSTRAINT [DF_CHKMASTER_SiteID] DEFAULT ((0)) NOT NULL,
    [PreviousEmployee] BIT           NULL,
    [PreviousName]     VARCHAR (50)  NULL,
    [Sex]              CHAR (1)      NULL,
    [CreatedDate]      DATETIME      NULL
);

