CREATE TABLE [dbo].[PERSONNEL] (
    [PersonnelId]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [FirstName]           VARCHAR (50)    NULL,
    [LastName]            VARCHAR (50)    NULL,
    [MiddleName]          VARCHAR (50)    NULL,
    [Title]               VARCHAR (50)    NULL,
    [EMailAddress]        VARCHAR (100)   NULL,
    [Location]            VARCHAR (100)   NULL,
    [UPhone]              VARCHAR (50)    NULL,
    [Extension]           VARCHAR (10)    NULL,
    [Comments]            VARCHAR (8000)  NULL,
    [UPager]              VARCHAR (50)    NULL,
    [AltPhone]            VARCHAR (50)    NULL,
    [LoginId]             NVARCHAR (25)   NOT NULL,
    [SSN]                 VARCHAR (11)    NOT NULL,
    [RankId]              INT             NULL,
    [Rate]                VARCHAR (15)    NULL,
    [AudienceId]          BIGINT          NULL,
    [DOB]                 DATETIME        NULL,
    [MedStuYr]            VARCHAR (20)    NULL,
    [OtherStu]            VARCHAR (50)    NULL,
    [NMCIEMail]           VARCHAR (100)   NULL,
    [CitizenshipId]       INT             NULL,
    [CreatedDate]         DATETIME        CONSTRAINT [DF_PERSONNEL_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]           INT             CONSTRAINT [DF_PERSONNEL_CreatedBy] DEFAULT ((0)) NULL,
    [UpdatedDate]         DATETIME        CONSTRAINT [DF_PERSONNEL_UpdatedDate] DEFAULT (getdate()) NULL,
    [UpdatedBy]           INT             CONSTRAINT [DF_PERSONNEL_UpdatedBy] DEFAULT ((0)) NULL,
    [EAOS_PRD]            DATETIME        NULL,
    [Sex]                 VARCHAR (1)     NULL,
    [ACCESSCODE]          VARCHAR (20)    NULL,
    [VERIFYCODE]          VARCHAR (20)    NULL,
    [Address1]            VARCHAR (100)   NULL,
    [Address2]            VARCHAR (100)   NULL,
    [City]                VARCHAR (50)    NULL,
    [State]               VARCHAR (2)     NULL,
    [Zip]                 VARCHAR (10)    NULL,
    [DesignationId]       INT             NULL,
    [NetworkAccess]       BIT             NULL,
    [OutlookExchange]     BIT             NULL,
    [PreviousDutyStation] VARCHAR (50)    NULL,
    [ExpectedEndDate]     DATETIME        NULL,
    [UserId]              INT             CONSTRAINT [DF_PERSONNEL_UserId] DEFAULT ((0)) NULL,
    [ContractorCompany]   VARCHAR (50)    NULL,
    [ContractNumber]      VARCHAR (50)    NULL,
    [HealthcareStatusId]  INT             CONSTRAINT [DF_PERSONNEL_HealthcareStatusId] DEFAULT ((0)) NULL,
    [BaseId]              INT             CONSTRAINT [DF_PERSONNEL_BaseId] DEFAULT ((0)) NULL,
    [EthnicityId]         INT             CONSTRAINT [DF_PERSONNEL_EthnicityId] DEFAULT ((0)) NULL,
    [AHLTA]               VARCHAR (20)    NULL,
    [DisplayName]         VARCHAR (150)   NULL,
    [CheckInDate]         DATETIME        CONSTRAINT [DF_PERSONNEL_CheckInDate] DEFAULT (getdate()) NULL,
    [EffectiveDate]       DATETIME        CONSTRAINT [DF_PERSONNEL_EffectiveDate] DEFAULT (getdate()) NULL,
    [ComponentId]         INT             CONSTRAINT [DF_PERSONNEL_ComponentId] DEFAULT ((0)) NULL,
    [Suffix]              VARCHAR (6)     NULL,
    [LB]                  BIT             CONSTRAINT [DF_PERSONNEL_LB] DEFAULT ((0)) NULL,
    [PSQ]                 BIT             CONSTRAINT [DF_PERSONNEL_PSQ] DEFAULT ((0)) NULL,
    [LBDate]              DATETIME        CONSTRAINT [DF_PERSONNEL_LBDate] DEFAULT ('1/1/1776') NULL,
    [PSQDate]             DATETIME        CONSTRAINT [DF_PERSONNEL_PSQDate] DEFAULT ('1/1/1776') NULL,
    [LBBy]                INT             CONSTRAINT [DF_PERSONNEL_LBBy] DEFAULT ((0)) NULL,
    [PSQBy]               INT             CONSTRAINT [DF_PERSONNEL_PSQBy] DEFAULT ((0)) NULL,
    [Supervisor]          VARCHAR (150)   NULL,
    [EducationLevelId]    INT             CONSTRAINT [DF_PERSONNEL_EducationLevelId] DEFAULT ((0)) NULL,
    [DoDEDI]              NVARCHAR (10)   NULL,
    [EmployeeNumber]      INT             CONSTRAINT [DF_PERSONNEL_EmployeeNumber] DEFAULT ((0)) NULL,
    [NPIKey]              NUMERIC (16, 3) NULL,
    CONSTRAINT [PK_PERSONNEL] PRIMARY KEY CLUSTERED ([PersonnelId] ASC),
    CONSTRAINT [CK_PERSONNEL] CHECK (len([SSN])>(0))
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PERSONNEL_Duplicates]
    ON [dbo].[PERSONNEL]([FirstName] ASC, [LastName] ASC, [SSN] ASC, [DOB] ASC, [DesignationId] ASC, [CheckInDate] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'SSN cannot be blank', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PERSONNEL', @level2type = N'CONSTRAINT', @level2name = N'CK_PERSONNEL';

