CREATE LOGIN [NHJAX_REPORTS]
    WITH PASSWORD = N'wu@%bprUbgYu<gH2ran@0pirmsFT7_&#$!~<gtXdoytfedhF', SID = 0x236902D2BAC1CC4BBE19FAA0119B86E3, DEFAULT_DATABASE = [NHJAX_REPORTS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

