CREATE VIEW [dbo].[vwCPTModifierErrorCorrection20050228]
AS
SELECT     CPTMOD.KEY_CPT_HCPCS,CASE WHEN LEN(CPTMOD2.DOD_BILLING) > 0 THEN CPTMOD2.DOD_BILLING ELSE 0 END AS CMACUnit
FROM         dbo.CPT_HCPCS$MODIFIER CPTMOD LEFT OUTER JOIN
                      dbo.CPT_HCPCS$MODIFIER20040801 CPTMOD2 ON CPTMOD.KEY_CPT_HCPCS = CPTMOD2.KEY_CPT_HCPCS AND 
                      CPTMOD.KEY_CPT_HCPCS$MODIFIER = CPTMOD2.KEY_CPT_HCPCS$MODIFIER
WHERE     (CPTMOD.MODIFIER = '00')
