CREATE VIEW [dbo].[vwHyperlipidemicList]
AS
SELECT DISTINCT PAT.KEY_PATIENT, PAT.NAME, PAT.SEX, PAT.DOB, PAT.SSN, PAT.PHONE, PAT.OFFICE_PHONE
FROM         dbo.PATIENT PAT INNER JOIN
                      dbo.PATIENT_APPOINTMENT ON PAT.KEY_PATIENT = dbo.PATIENT_APPOINTMENT.NAME_IEN INNER JOIN
                      dbo.KG_ADC_DATA ON dbo.PATIENT_APPOINTMENT.KEY_PATIENT_APPOINTMENT = dbo.KG_ADC_DATA.APPOINTMENT_IEN INNER JOIN
                      dbo.KG_ADC_DATA$ICD_DIAGNOSIS ON 
                      dbo.KG_ADC_DATA.KEY_KG_ADC_DATA = dbo.KG_ADC_DATA$ICD_DIAGNOSIS.KEY_KG_ADC_DATA INNER JOIN
                      dbo.ICD_DIAGNOSIS ON dbo.KG_ADC_DATA$ICD_DIAGNOSIS.ICD_DIAGNOSIS_IEN = dbo.ICD_DIAGNOSIS.KEY_ICD_DIAGNOSIS
WHERE     (dbo.ICD_DIAGNOSIS.CODE_NUMBER IN ('272.0', '272.1', '272.2', '272.4'))
