CREATE VIEW [dbo].[vwPatientEncounterReferrals]
AS
SELECT DISTINCT MAX(REF_APT.KEY_MCP_REFERRAL) AS ReferralKey, REF_APT.KEY_MCP_REFERRAL$APPOINTMENTS AS PatientEncounterKey
FROM         dbo.MCP_REFERRAL REF INNER JOIN
                      dbo.MCP_REFERRAL$APPOINTMENTS REF_APT ON REF.KEY_MCP_REFERRAL = REF_APT.KEY_MCP_REFERRAL
GROUP BY REF_APT.KEY_MCP_REFERRAL$APPOINTMENTS
