
CREATE VIEW [dbo].[vwCIP_DM_ClinicReportCardAppt] 

AS
SELECT 	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	APP.PATIENTENCOUNTERID AS METRIC, 
	1 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM 		
	HOSPITAL_LOCATION LOC 
	INNER JOIN PATIENT_ENCOUNTER APP 
	ON APP.HOSPITALLOCATIONID = LOC.HOSPITALLOCATIONID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	STA.APPOINTMENTSTATUSID IN ('2', '6')
		AND PRO.PROVIDERFLAG = '1'


UNION
SELECT 	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	APP.PATIENTENCOUNTERID AS METRIC, 
	2 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM 		
	HOSPITAL_LOCATION LOC 
	INNER JOIN PATIENT_ENCOUNTER APP 
	ON APP.HOSPITALLOCATIONID = LOC.HOSPITALLOCATIONID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	STA.APPOINTMENTSTATUSID = '7'
		AND PRO.PROVIDERFLAG = '1'


UNION
SELECT 	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	APP.PATIENTENCOUNTERID AS METRIC, 
	3 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM 		
	HOSPITAL_LOCATION LOC 
	INNER JOIN PATIENT_ENCOUNTER APP 
	ON APP.HOSPITALLOCATIONID = LOC.HOSPITALLOCATIONID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	STA.APPOINTMENTSTATUSID = '5'
		AND PRO.PROVIDERFLAG = '1'


UNION
SELECT	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	CPT.RVU AS METRIC, 
	4 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM		
	PATIENT_ENCOUNTER APP 
	INNER JOIN PATIENT_PROCEDURE KG 
	ON APP.PATIENTENCOUNTERID = KG.PATIENTENCOUNTERID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN CPT 
	ON KG.CPTID = CPT.CPTID
	INNER JOIN CPT_TYPE CPT_TYPE 
	ON CPT.CPTTYPEID = CPT_TYPE.CPTTYPEID
	INNER JOIN HOSPITAL_LOCATION LOC 
	ON LOC.HOSPITALLOCATIONID = APP.HOSPITALLOCATIONID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	NOT APP.APPOINTMENTSTATUSID IN ('0', '1', '3', '4', '8', '9', '11', '50')
		AND CPT.CPTTYPEID = '2'
		AND PRO.PROVIDERFLAG = '1'

UNION
SELECT	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	CPT.RVU AS METRIC, 
	5 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM
	PATIENT_ENCOUNTER APP 
	INNER JOIN PATIENT_PROCEDURE KG 
	ON APP.PATIENTENCOUNTERID = KG.PATIENTENCOUNTERID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN	CPT 
	ON KG.CPTID = CPT.CPTID
	INNER JOIN CPT_TYPE CPT_TYPE 
	ON CPT.CPTTYPEID = CPT_TYPE.CPTTYPEID
	INNER JOIN HOSPITAL_LOCATION LOC 
	ON LOC.HOSPITALLOCATIONID = APP.HOSPITALLOCATIONID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN	MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	NOT APP.APPOINTMENTSTATUSID IN ('0', '1', '3', '4', '8', '9', '11', '50')
		AND CPT.CPTTYPEID = '0'
		AND PRO.PROVIDERFLAG = '1'


UNION
SELECT 	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	APP.DURATION AS METRIC, 
	6 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM
	HOSPITAL_LOCATION LOC 
	INNER JOIN PATIENT_ENCOUNTER APP 
	ON APP.HOSPITALLOCATIONID = LOC.HOSPITALLOCATIONID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	APP.APPOINTMENTSTATUSID IN ('2', '6', '7', '5')
		AND PRO.PROVIDERFLAG = '1'


UNION
SELECT 	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	APP.APPOINTMENTSTATUSID AS METRIC, 
	7 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM
	HOSPITAL_LOCATION LOC 
	INNER JOIN PATIENT_ENCOUNTER APP 
	ON APP.HOSPITALLOCATIONID = LOC.HOSPITALLOCATIONID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN PATIENT PT 
	ON PT.PATIENTID = APP.PATIENTID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	APP.APPOINTMENTSTATUSID IN ('2', '5', '6', '7')
		AND PRO.PROVIDERFLAG = '1'
		AND PT.CURRENTPCMID = APP.PROVIDERID

UNION
SELECT 	
	LOC.HOSPITALLOCATIONID AS CLINICID, 
	LOC.HOSPITALLOCATIONNAME AS CLINICNAME, 
	APP.APPOINTMENTSTATUSID AS METRIC, 
	8 AS TYPE,
	APP.APPOINTMENTDATETIME,
	MPR.DMISID
FROM
	HOSPITAL_LOCATION LOC 
	INNER JOIN PATIENT_ENCOUNTER APP 
	ON APP.HOSPITALLOCATIONID = LOC.HOSPITALLOCATIONID
	INNER JOIN APPOINTMENT_STATUS STA 
	ON APP.APPOINTMENTSTATUSID = STA.APPOINTMENTSTATUSID
	INNER JOIN PATIENT PT 
	ON PT.PATIENTID = APP.PATIENTID
	INNER JOIN PROVIDER PRO 
	ON PRO.PROVIDERID = APP.PROVIDERID
	INNER JOIN MEPRS_CODE MPR 
	ON MPR.MEPRSCODEID = LOC.MEPRSCODEID
WHERE	APP.APPOINTMENTSTATUSID IN ('2', '5', '6')
		AND PRO.PROVIDERFLAG = '1'
		AND PT.CURRENTPCMID = APP.PROVIDERID
