create PROCEDURE [dbo].[procMDE_SE_SCHEDULE_DATE_TIMES_SelectMissing]

AS
	SET NOCOUNT ON;


SELECT     
	KEY_SCHEDULABLE_ENTITY,
	KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES,
	DATE_TIME
FROM SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES
WHERE KEY_SCHEDULABLE_ENTITY NOT IN
(SELECT KEY_SCHEDULABLE_ENTITY
FROM SCHEDULABLE_ENTITY)
