
create PROCEDURE [dbo].[procMDE_SE_APPOINTMENT_SLOTS_UpdateStatus]
(
	@key numeric(7,3),
	@keyse numeric(11,3),
	@dkey numeric(22,7),
	@stat varchar(30)
)
AS
	SET NOCOUNT ON;
	
UPDATE SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS
SET APPT_SLOT_STATUS = @stat
WHERE KEY_SCHEDULABLE_ENTITY = @keyse
	AND KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL = @key
	AND KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES = @dkey;