
create PROCEDURE [dbo].[procMDE_SE_DETAIL_CODES_UpdateDetailCode]
(
	@keyas numeric(7,3),
	@key numeric(7,3),
	@keyse numeric(11,3),
	@dkey numeric(22,7),
	@dc numeric(21,3)
)
AS
	SET NOCOUNT ON;
	
UPDATE SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES
SET APPT_DETAIL_CODES_IEN = @dc
WHERE KEY_SCHEDULABLE_ENTITY = @keyse
	AND KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL = @keyas
	AND KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES = @dkey
	AND KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C = @key;