create PROCEDURE [dbo].[procSTG_CHCS_PRESCRIPTION_Select]
(
	@key numeric(14,3)
)
AS
	SET NOCOUNT ON;
SELECT     
	KEY_PRESCRIPTION, 
	RX_#, 
	PATIENT_IEN, 
	PROVIDER_IEN, 
	DRUG_IEN, 
	LAST_FILL_DATE, 
	ORDER_DATE_TIME, 
	ORDER_ENTRY_NUMBER, 
	ORDER_POINTER_IEN, 
	EXPIRATION_DATE, 
	[STATUS]
FROM CHCS_PRESCRIPTION
WHERE (KEY_PRESCRIPTION = @key)
