create PROCEDURE [dbo].[procMDE_SE_DETAIL_CODES_Select]
(
	@key numeric(7,3),
	@keyse numeric(11,3),
	@keyas numeric(7,3),
	@dkey numeric(22,7)
)
AS
	SET NOCOUNT ON;


SELECT     
	KEY_SCHEDULABLE_ENTITY,
	KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C,
	KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL,
	KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES,
	APPT_DETAIL_CODES_IEN
FROM SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES
WHERE (KEY_SCHEDULABLE_ENTITY = @keyse
	AND KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL = @keyas
	AND KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES = @dkey
	AND KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C = @key)
