create PROCEDURE [dbo].[procMDE_SCHEDULABLE_ENTITY_Select]
(
	@key numeric(11,3)
)
AS
	SET NOCOUNT ON;
SELECT     
	KEY_SCHEDULABLE_ENTITY, 
	[ENTITY_NAME]
FROM SCHEDULABLE_ENTITY
WHERE (KEY_SCHEDULABLE_ENTITY = @key)
