CREATE PROCEDURE [dbo].[procMDE_SE_SCHEDULE_DATE_TIMES_Select]
(
	@key numeric(11,3),
	@dkey numeric(22,7)
)
AS
	SET NOCOUNT ON;


SELECT     
	KEY_SCHEDULABLE_ENTITY,
	KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES,
	DATE_TIME
FROM SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES
WHERE (KEY_SCHEDULABLE_ENTITY = @key
	AND KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES = @dkey)
