CREATE PROCEDURE [dbo].[procSTG_CHCS_PRESCRIPTION_SelectPlavixInteractionDistinct]

AS
	SET NOCOUNT ON;
SELECT DISTINCT 
PATIENT.NAME, 
FMP.FMP, 
PATIENT.SPONSOR_SSN, 
PATIENT.STREET_ADDRESS, 
PATIENT.STREET_ADDRESS_2, 
PATIENT.STREET_ADDRESS_3, 
PATIENT.CITY, 
PATIENT.STATE_IEN, 
PATIENT.ZIP_CODE, 
PATIENT.PHONE, 
PATIENT.OFFICE_PHONE
FROM vwSTG_CHCS_PRESCRIPTION_Plavix AS PLAVIX 
INNER JOIN vwSTG_CHCS_PRESCRIPTION_NonPlavix AS NON 
ON PLAVIX.PATIENT_IEN = NON.PATIENT_IEN 
INNER JOIN PATIENT 
ON PLAVIX.PATIENT_IEN = PATIENT.KEY_PATIENT 
INNER JOIN FAMILY_MEMBER_PREFIX AS FMP 
ON PATIENT.FMP_IEN = FMP.KEY_FAMILY_MEMBER_PREFIX 
ORDER BY PATIENT.NAME
