CREATE PROCEDURE [dbo].[upCreateIndexes_PATIENT_APPOINTMENT$APPT_DETAIL_CODES] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_PATIENT_APPOINTMENT$APPT_DETAIL_CODES')
	DROP INDEX PATIENT_APPOINTMENT$APPT_DETAIL_CODES.ind_PATIENT_APPOINTMENT$APPT_DETAIL_CODES

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_PATIENT_APPOINTMENT$APPT_DETAIL_CODES_KEY_PATIENT_APPOINTMENT$APPT_DETAIL_CODES')
	DROP INDEX PATIENT_APPOINTMENT$APPT_DETAIL_CODES.IX_PATIENT_APPOINTMENT$APPT_DETAIL_CODES_KEY_PATIENT_APPOINTMENT$APPT_DETAIL_CODES
	
	CREATE INDEX IX_PATIENT_APPOINTMENT$APPT_DETAIL_CODES_KEY_PATIENT_APPOINTMENT$APPT_DETAIL_CODES
	ON			PATIENT_APPOINTMENT$APPT_DETAIL_CODES(KEY_PATIENT_APPOINTMENT$APPT_DETAIL_CODES)
	WITH		FILLFACTOR = 100
