CREATE PROCEDURE [dbo].[upCreateIndexes_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2] AS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'ind_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.ind_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2

	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT
		
	CREATE INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(KEY_LAB_RESULT)
	WITH 			FILLFACTOR = 100
				
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY
		
	CREATE INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(KEY_LAB_RESULT$BACTERIOLOGY)
	WITH 			FILLFACTOR = 100

	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST
		
	CREATE INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(KEY_LAB_RESULT$BACTERIOLOGY$TEST)
	WITH 			FILLFACTOR = 100

	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM
		
	CREATE INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM)
	WITH 			FILLFACTOR = 100

	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2
		
	CREATE INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_KEY_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(KEY_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2)
	WITH 			FILLFACTOR = 100

	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_ANTIBIOTIC_IEN')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_ANTIBIOTIC_IEN
		
	CREATE INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_ANTIBIOTIC_IEN
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(ANTIBIOTIC_IEN)
	WITH 			FILLFACTOR = 100

	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_INTERPRETATION_IEN')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_INTERPRETATION_IEN
		
	CREATE INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_INTERPRETATION_IEN
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(INTERPRETATION_IEN)
	WITH 			FILLFACTOR = 100

	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_MULTIKEY')
		DROP INDEX LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2.IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_MULTIKEY
		
	CREATE CLUSTERED INDEX 	IX_LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2_MULTIKEY
	ON 			LAB_RESUL$BACTERIOL$TEST$ORGANISM$ANTIBIOTIC2(KEY_LAB_RESULT,KEY_LAB_RESULT$BACTERIOLOGY,KEY_LAB_RESULT$BACTERIOLOGY$TEST,KEY_LAB_RESULT$BACTERIOLOGY$TEST$ORGANISM,ANTIBIOTIC_IEN,INTERPRETATION_IEN)
	WITH 			FILLFACTOR = 100
