CREATE PROCEDURE [dbo].[upCreateIndexes_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES] AS 
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES')
	DROP INDEX SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES.ind_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES')
	DROP INDEX SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES.IX_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES

	CREATE INDEX IX_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES
	ON SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES(KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES)
	WITH		FILLFACTOR = 100
