CREATE PROCEDURE [dbo].[upCreateIndexes_GEOGRAPHIC_LOCATION] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_GEOGRAPHIC_LOCATION')
		DROP INDEX GEOGRAPHIC_LOCATION.ind_GEOGRAPHIC_LOCATION
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_GEOGRAPHIC_LOCATION_KEY_GEOGRAPHIC_LOCATION')
		DROP INDEX GEOGRAPHIC_LOCATION.IX_GEOGRAPHIC_LOCATION_KEY_GEOGRAPHIC_LOCATION
		                                                                
	CREATE INDEX 	IX_GEOGRAPHIC_LOCATION_KEY_GEOGRAPHIC_LOCATION
	ON 			GEOGRAPHIC_LOCATION(KEY_GEOGRAPHIC_LOCATION)
	WITH 			FILLFACTOR = 100
