CREATE PROCEDURE [dbo].[upCreateIndexes_LAB_TEST$LAB_TEST_IN_PANEL] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_LAB_TEST$LAB_TEST_IN_PANEL')
		DROP INDEX LAB_TEST$LAB_TEST_IN_PANEL.ind_LAB_TEST$LAB_TEST_IN_PANEL
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST$LAB_TEST_IN_PANEL')
		DROP INDEX LAB_TEST$LAB_TEST_IN_PANEL.IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST$LAB_TEST_IN_PANEL
		                                                                
	CREATE INDEX 	IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST$LAB_TEST_IN_PANEL
	ON 			LAB_TEST$LAB_TEST_IN_PANEL(KEY_LAB_TEST$LAB_TEST_IN_PANEL)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST')
		DROP INDEX LAB_TEST$LAB_TEST_IN_PANEL.IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST
		                                                                
	CREATE INDEX 	IX_LAB_TEST$LAB_TEST_IN_PANEL_KEY_LAB_TEST
	ON 			LAB_TEST$LAB_TEST_IN_PANEL(KEY_LAB_TEST)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_TEST$LAB_TEST_IN_PANEL_LAB_TEST_IN_PANEL_IEN')
		DROP INDEX LAB_TEST$LAB_TEST_IN_PANEL.IX_LAB_TEST$LAB_TEST_IN_PANEL_LAB_TEST_IN_PANEL_IEN
		                                                                
	CREATE INDEX 	IX_LAB_TEST$LAB_TEST_IN_PANEL_LAB_TEST_IN_PANEL_IEN
	ON 			LAB_TEST$LAB_TEST_IN_PANEL(LAB_TEST_IN_PANEL_IEN)
	WITH 			FILLFACTOR = 100
