CREATE PROCEDURE [dbo].[upCreateIndexes_PROVIDER] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_PROVIDER')
		DROP INDEX PROVIDER.ind_PROVIDER
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PROVIDER_KEY_PROVIDER')
		DROP INDEX PROVIDER.IX_PROVIDER_KEY_PROVIDER
		
	CREATE INDEX 	IX_PROVIDER_KEY_PROVIDER
	ON 			PROVIDER(KEY_PROVIDER)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PROVIDER_PROVIDER_ID')
		DROP INDEX PROVIDER.IX_PROVIDER_PROVIDER_ID				
	CREATE INDEX 	IX_PROVIDER_PROVIDER_ID
	ON 			PROVIDER(PROVIDER_ID)
	WITH 			FILLFACTOR = 100
