CREATE PROCEDURE [dbo].[upCreateIndexes_KG_ADC_DATA$CPT_CODE] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_KG_ADC_DATA$CPT_CODE')
		DROP INDEX KG_ADC_DATA$CPT_CODE.ind_KG_ADC_DATA$CPT_CODE
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA$CPT_CODE')
		DROP INDEX KG_ADC_DATA$CPT_CODE.IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA$CPT_CODE
		
	CREATE CLUSTERED INDEX 	IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA$CPT_CODE
	ON 			KG_ADC_DATA$CPT_CODE(KEY_KG_ADC_DATA$CPT_CODE)
	WITH 			FILLFACTOR = 100
			
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_KG_ADC_DATA$CPT_CODE_CPT_CODE_IEN')
		DROP INDEX KG_ADC_DATA$CPT_CODE.IX_KG_ADC_DATA$CPT_CODE_CPT_CODE_IEN	
	CREATE INDEX 	IX_KG_ADC_DATA$CPT_CODE_CPT_CODE_IEN
	ON 			KG_ADC_DATA$CPT_CODE(CPT_CODE_IEN)
	WITH 			FILLFACTOR = 100
		
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA')
		DROP INDEX KG_ADC_DATA$CPT_CODE.IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA		
	CREATE INDEX 	IX_KG_ADC_DATA$CPT_CODE_KEY_KG_ADC_DATA
	ON 			KG_ADC_DATA$CPT_CODE(KEY_KG_ADC_DATA)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_KG_ADC_DATA$CPT_CODE_DIAGNOSIS_PRIORITY')
		DROP INDEX KG_ADC_DATA$CPT_CODE.IX_KG_ADC_DATA$CPT_CODE_DIAGNOSIS_PRIORITY
	CREATE INDEX		IX_KG_ADC_DATA$CPT_CODE_DIAGNOSIS_PRIORITY
	ON			KG_ADC_DATA$CPT_CODE(DIAGNOSIS_PRIORITY)
	WITH			FILLFACTOR = 100
