CREATE PROCEDURE [dbo].[upCreateIndexes_MCP_APPOINTMENT_REFUSAL_REASON] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_MCP_APPOINTMENT_REFUSAL_REASON')
		DROP INDEX MCP_APPOINTMENT_REFUSAL_REASON.ind_MCP_APPOINTMENT_REFUSAL_REASON
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_APPOINTMENT_REFUSAL_REASON_KEY_MCP_APPOINTMENT_REFUSAL_REASON')
		DROP INDEX MCP_APPOINTMENT_REFUSAL_REASON.IX_MCP_APPOINTMENT_REFUSAL_REASON_KEY_MCP_APPOINTMENT_REFUSAL_REASON
		                                                                
	CREATE INDEX 	IX_MCP_APPOINTMENT_REFUSAL_REASON_KEY_MCP_APPOINTMENT_REFUSAL_REASON
	ON 			MCP_APPOINTMENT_REFUSAL_REASON(KEY_MCP_APPOINTMENT_REFUSAL_REASON)
	WITH 			FILLFACTOR = 100
