--CREATE PROCEDURE [DBO].[upCreateIndexes_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES] AS
--	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C')
--	DROP INDEX SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES.ind_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C
--
--	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C_KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C')
--	DROP INDEX SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES.IX_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C_KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C
--
--	CREATE INDEX IX_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C_KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C
--	ON		SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES(KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C)
--	WITH		FILLFACTOR = 100

CREATE PROCEDURE [dbo].[upCreateIndexes_SCHEDULABLE_ENTITIES] AS 
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_SCHEDULABLE_ENTITIES')
	DROP INDEX SCHEDULABLE_ENTITIES.ind_SCHEDULABLE_ENTITIES
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_SCHEDULABLE_ENTITIES_KEY_SCHEDULABLE_ENTITIES')
	DROP INDEX SCHEDULABLE_ENTITIES.IX_SCHEDULABLE_ENTITIES_KEY_SCHEDULABLE_ENTITIES

	CREATE INDEX IX_SCHEDULABLE_ENTITIES_KEY_SCHEDULABLE_ENTITIES
	ON SCHEDULABLE_ENTITIES(KEY_SCHEDULABLE_ENTITIES)
	WITH		FILLFACTOR = 100
