CREATE PROCEDURE [dbo].[upCreateIndexes_NED_HCDP_COVERAGE_CODE] AS

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_NED_HCDP_COVERAGE_CODE')
		DROP INDEX NED_HCDP_COVERAGE_CODE.ind_NED_HCDP_COVERAGE_CODE

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_NED_HCDP_COVERAGE_CODE_KEY_NED_HCDP_COVERAGE_CODE')
		DROP INDEX	NED_HCDP_COVERAGE_CODE.IX_NED_HCDP_COVERAGE_CODE_KEY_NED_HCDP_COVERAGE_CODE
	
	CREATE INDEX IX_NED_HCDP_COVERAGE_CODE_KEY_NED_HCDP_COVERAGE_CODE
	ON			NED_HCDP_COVERAGE_CODE(KEY_NED_HCDP_COVERAGE_CODE)
	WITH			FILLFACTOR = 100
