CREATE PROCEDURE [dbo].[upCreateIndexes_WARD_LOCATION] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_WARD_LOCATION')
	DROP INDEX WARD_LOCATION.ind_WARD_LOCATION
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_WARD_LOCATION_KEY_WARD_LOCATION')
	DROP INDEX WARD_LOCATION.IX_WARD_LOCATION_KEY_WARD_LOCATION

	CREATE INDEX IX_WARD_LOCATION_KEY_WARD_LOCATION
	ON WARD_LOCATION(KEY_WARD_LOCATION)
	WITH		FILLFACTOR = 100
