CREATE PROCEDURE [dbo].[upCreateIndexes_MCP_BENEFICIARY_CATEGORIES] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_MCP_BENEFICIARY_CATEGORIES')
		DROP INDEX MCP_BENEFICIARY_CATEGORIES.ind_MCP_BENEFICIARY_CATEGORIES
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_BENEFICIARY_CATEGORIES_KEY_MCP_BENEFICIARY_CATEGORIES')
		DROP INDEX MCP_BENEFICIARY_CATEGORIES.IX_MCP_BENEFICIARY_CATEGORIES_KEY_MCP_BENEFICIARY_CATEGORIES
		                                                                
	CREATE INDEX 	IX_MCP_BENEFICIARY_CATEGORIES_KEY_MCP_BENEFICIARY_CATEGORIES
	ON 			MCP_BENEFICIARY_CATEGORIES(KEY_MCP_BENEFICIARY_CATEGORIES)
	WITH 			FILLFACTOR = 100
