CREATE PROCEDURE [dbo].[upCreateIndexes_DEPARTMENT_AND_SERVICE] AS

IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_DEPARTMENT_AND_SERVICE')
	DROP INDEX DEPARTMENT_AND_SERVICE.ind_DEPARTMENT_AND_SERVICE
                                                          
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_DEPARTMENT_AND_SERVICE_KEY_DEPARTMENT_AND_SERVICE')
	DROP INDEX DEPARTMENT_AND_SERVICE.IX_DEPARTMENT_AND_SERVICE_KEY_DEPARTMENT_AND_SERVICE
                                                                
	CREATE INDEX 	IX_DEPARTMENT_AND_SERVICE_KEY_DEPARTMENT_AND_SERVICE
	ON 			DEPARTMENT_AND_SERVICE(KEY_DEPARTMENT_AND_SERVICE)
	WITH 			FILLFACTOR = 100
