CREATE PROCEDURE [dbo].[upCreateIndexes_CLINICAL_HISTORY$DRUG_ALLERGY] AS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'ind_CLINICAL_HISTORY$DRUG_ALLERGY')
		DROP INDEX CLINICAL_HISTORY$DRUG_ALLERGY.ind_CLINICAL_HISTORY$DRUG_ALLERGY
	
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_CLINICAL_HISTORY$DRUG_ALLERGY_KEY_CLINICAL_HISTORY')
		DROP INDEX CLINICAL_HISTORY$DRUG_ALLERGY.IX_CLINICAL_HISTORY$DRUG_ALLERGY_KEY_CLINICAL_HISTORY
		
	CREATE INDEX 	IX_CLINICAL_HISTORY$DRUG_ALLERGY_KEY_CLINICAL_HISTORY
	ON 			CLINICAL_HISTORY$DRUG_ALLERGY(KEY_CLINICAL_HISTORY) 
	WITH 			FILLFACTOR = 100
	
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_CLINICAL_HISTORY$DRUG_ALLERGY_ALLERGY_SELECTION_IEN')
		DROP INDEX CLINICAL_HISTORY$DRUG_ALLERGY.IX_CLINICAL_HISTORY$DRUG_ALLERGY_ALLERGY_SELECTION_IEN
	CREATE INDEX 	IX_CLINICAL_HISTORY$DRUG_ALLERGY_ALLERGY_SELECTION_IEN
	ON 			CLINICAL_HISTORY$DRUG_ALLERGY(ALLERGY_SELECTION_IEN) 
	WITH 			FILLFACTOR = 100
