CREATE PROCEDURE [dbo].[upCreateIndexes_DRUG$ASSOCIATED_FORMULARY] AS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'ind_DRUG$ASSOCIATED_FORMULARY')
		DROP INDEX DRUG$ASSOCIATED_FORMULARY.ind_DRUG$ASSOCIATED_FORMULARY
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG')
		DROP INDEX DRUG$ASSOCIATED_FORMULARY.IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG
		
	CREATE INDEX 	IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG
	ON 			DRUG$ASSOCIATED_FORMULARY(KEY_DRUG)
	WITH 			FILLFACTOR = 100
				
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG')
		DROP INDEX DRUG$ASSOCIATED_FORMULARY.IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG
		
	CREATE INDEX 	IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG
	ON 			DRUG$ASSOCIATED_FORMULARY(KEY_DRUG)
	WITH 			FILLFACTOR = 100
				
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG$ASSOCIATED_FORMULARY')
		DROP INDEX DRUG$ASSOCIATED_FORMULARY.IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG$ASSOCIATED_FORMULARY				
	CREATE INDEX 	IX_DRUG$ASSOCIATED_FORMULARY_KEY_DRUG$ASSOCIATED_FORMULARY
	ON 			DRUG$ASSOCIATED_FORMULARY(KEY_DRUG$ASSOCIATED_FORMULARY)
	WITH 			FILLFACTOR = 100
		
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_DRUG$ASSOCIATED_FORMULARY_ASSOCIATED_FORMULARY_IEN')
		DROP INDEX DRUG$ASSOCIATED_FORMULARY.IX_DRUG$ASSOCIATED_FORMULARY_ASSOCIATED_FORMULARY_IEN				
	CREATE INDEX 	IX_DRUG$ASSOCIATED_FORMULARY_ASSOCIATED_FORMULARY_IEN
	ON 			DRUG$ASSOCIATED_FORMULARY(ASSOCIATED_FORMULARY_IEN)
	WITH 			FILLFACTOR = 100
