CREATE PROCEDURE [dbo].[upCreateIndexes_SCHEDULABLE_ENTITY] AS 
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_SCHEDULABLE_ENTITY')
	DROP INDEX SCHEDULABLE_ENTITY.ind_SCHEDULABLE_ENTITY
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_SCHEDULABLE_ENTITY_KEY_SCHEDULABLE_ENTITY')
	DROP INDEX SCHEDULABLE_ENTITY.IX_SCHEDULABLE_ENTITY_KEY_SCHEDULABLE_ENTITY

	CREATE INDEX IX_SCHEDULABLE_ENTITY_KEY_SCHEDULABLE_ENTITY
	ON SCHEDULABLE_ENTITY(KEY_SCHEDULABLE_ENTITY)
	WITH		FILLFACTOR = 100
