CREATE PROCEDURE [dbo].[upCreateIndexes_RADIOLOGY_EXAM] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_RADIOLOGY_EXAM')
		DROP INDEX RADIOLOGY_EXAM.ind_RADIOLOGY_EXAM
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_RADIOLOGY_EXAM_KEY_RADIOLOGY_EXAM')
		DROP INDEX RADIOLOGY_EXAM.IX_RADIOLOGY_EXAM_KEY_RADIOLOGY_EXAM
		                                                                
	CREATE INDEX 	IX_RADIOLOGY_EXAM_KEY_RADIOLOGY_EXAM
	ON 			RADIOLOGY_EXAM(KEY_RADIOLOGY_EXAM)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_RADIOLOGY_EXAM_EXAM_DATE_TIME')
		DROP INDEX RADIOLOGY_EXAM.IX_RADIOLOGY_EXAM_EXAM_DATE_TIME
		                                                                
	CREATE CLUSTERED INDEX 	IX_RADIOLOGY_EXAM_EXAM_DATE_TIME
	ON 			RADIOLOGY_EXAM(EXAM_DATE_TIME)
	WITH 			FILLFACTOR = 100
