CREATE PROCEDURE [dbo].[upCreateIndexes_PHARMACY_PATIENT] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_PHARMACY_PATIENT')
		DROP INDEX PHARMACY_PATIENT.ind_PHARMACY_PATIENT
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PHARMACY_PATIENT_KEY_PHARMACY_PATIENT')
		DROP INDEX PHARMACY_PATIENT.IX_PHARMACY_PATIENT_KEY_PHARMACY_PATIENT
		                                                                
	CREATE INDEX 	IX_PHARMACY_PATIENT_KEY_PHARMACY_PATIENT
	ON 			PHARMACY_PATIENT(KEY_PHARMACY_PATIENT)
	WITH 			FILLFACTOR = 100
