CREATE PROCEDURE [dbo].[upCreateIndexes_PATIENT_APPOINTMENT] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_PATIENT_APPOINTMENT')
		DROP INDEX PATIENT_APPOINTMENT.ind_PATIENT_APPOINTMENT
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PATIENT_APPOINTMENT_APPOINTMENT_STATUS_IEN')
		DROP INDEX PATIENT_APPOINTMENT.IX_PATIENT_APPOINTMENT_APPOINTMENT_STATUS_IEN
		
	CREATE INDEX 	IX_PATIENT_APPOINTMENT_APPOINTMENT_STATUS_IEN
	ON 			PATIENT_APPOINTMENT(APPOINTMENT_STATUS_IEN) 
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PATIENT_APPOINTMENT_PROVIDER_IEN')
		DROP INDEX PATIENT_APPOINTMENT.IX_PATIENT_APPOINTMENT_PROVIDER_IEN				
	CREATE INDEX 	IX_PATIENT_APPOINTMENT_PROVIDER_IEN
	ON 			PATIENT_APPOINTMENT(PROVIDER_IEN) 
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PATIENT_APPOINTMENT_NAME_IEN')
		DROP INDEX PATIENT_APPOINTMENT.IX_PATIENT_APPOINTMENT_NAME_IEN				
	CREATE INDEX 	IX_PATIENT_APPOINTMENT_NAME_IEN
	ON 			PATIENT_APPOINTMENT(NAME_IEN) 
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PATIENT_APPOINTMENT_APPOINTMENT_DATE_TIME')
		DROP INDEX PATIENT_APPOINTMENT.IX_PATIENT_APPOINTMENT_APPOINTMENT_DATE_TIME					
	CREATE CLUSTERED INDEX 	IX_PATIENT_APPOINTMENT_APPOINTMENT_DATE_TIME
	ON 			PATIENT_APPOINTMENT(APPOINTMENT_DATE_TIME) 
	WITH 			FILLFACTOR = 100
				
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PATIENT_APPOINTMENT_CLINIC_IEN')
		DROP INDEX PATIENT_APPOINTMENT.IX_PATIENT_APPOINTMENT_CLINIC_IEN				
	CREATE INDEX 	IX_PATIENT_APPOINTMENT_CLINIC_IEN
	ON 			PATIENT_APPOINTMENT(CLINIC_IEN) 
	WITH 			FILLFACTOR = 100
