CREATE PROCEDURE [dbo].[upCreateIndexes_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES')
	DROP INDEX SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES.ind_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES_KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C')
	DROP INDEX SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES.IX_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES_KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C

	CREATE INDEX IX_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES_KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C
	ON		SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_CODES(KEY_SCHEDULABL$SCHEDULE_D$APPOINTMEN$APPT_DETAIL_C)
	WITH		FILLFACTOR = 100
