CREATE PROCEDURE [dbo].[upCreateIndexes_PATIENT$ADMISSION_DATE] AS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'ind_PATIENT$ADMISSION_DATE')
		DROP INDEX PATIENT$ADMISSION_DATE.ind_PATIENT$ADMISSION_DATE
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_PATIENT$ADMISSION_DATE_KEY_PATIENT$ADMISSION_DATE')
		DROP INDEX PATIENT$ADMISSION_DATE.IX_PATIENT$ADMISSION_DATE_KEY_PATIENT$ADMISSION_DATE
		
	CREATE INDEX 	IX_PATIENT$ADMISSION_DATE_KEY_PATIENT$ADMISSION_DATE
	ON 			PATIENT$ADMISSION_DATE(KEY_PATIENT$ADMISSION_DATE) 
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_PATIENT$ADMISSION_DATE_KEY_PATIENT')
		DROP INDEX PATIENT$ADMISSION_DATE.IX_PATIENT$ADMISSION_DATE_KEY_PATIENT
	CREATE INDEX 	IX_PATIENT$ADMISSION_DATE_KEY_PATIENT
	ON 			PATIENT$ADMISSION_DATE(KEY_PATIENT) 
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_PATIENT$ADMISSION_DATE_ADMISSION_DATE')
		DROP INDEX PATIENT$ADMISSION_DATE.IX_PATIENT$ADMISSION_DATE_ADMISSION_DATE
	CREATE CLUSTERED INDEX 	IX_PATIENT$ADMISSION_DATE_ADMISSION_DATE
	ON 			PATIENT$ADMISSION_DATE(ADMISSION_DATE) 
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_PATIENT$ADMISSION_DATE_TYPE_OF_ADMISSION_IEN')
		DROP INDEX PATIENT$ADMISSION_DATE.IX_PATIENT$ADMISSION_DATE_TYPE_OF_ADMISSION_IEN
	CREATE INDEX 	IX_PATIENT$ADMISSION_DATE_TYPE_OF_ADMISSION_IEN
	ON 			PATIENT$ADMISSION_DATE(TYPE_OF_ADMISSION_IEN) 
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_PATIENT$ADMISSION_DATE_TYPE_OF_DISPOSITION_IEN')
		DROP INDEX PATIENT$ADMISSION_DATE.IX_PATIENT$ADMISSION_DATE_TYPE_OF_DISPOSITION_IEN
	CREATE INDEX 	IX_PATIENT$ADMISSION_DATE_TYPE_OF_DISPOSITION_IEN
	ON 			PATIENT$ADMISSION_DATE(TYPE_OF_DISPOSITION_IEN) 
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_PATIENT$ADMISSION_DATE_ADMITTING_PHYSICIAN_IEN')
		DROP INDEX PATIENT$ADMISSION_DATE.IX_PATIENT$ADMISSION_DATE_ADMITTING_PHYSICIAN_IEN
	CREATE INDEX 	IX_PATIENT$ADMISSION_DATE_ADMITTING_PHYSICIAN_IEN
	ON 			PATIENT$ADMISSION_DATE(ADMITTING_PHYSICIAN_IEN) 
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_PATIENT$ADMISSION_DATE_ATTENDING_PHYSICIAN_IEN')
		DROP INDEX PATIENT$ADMISSION_DATE.IX_PATIENT$ADMISSION_DATE_ATTENDING_PHYSICIAN_IEN
	CREATE INDEX 	IX_PATIENT$ADMISSION_DATE_ATTENDING_PHYSICIAN_IEN
	ON 			PATIENT$ADMISSION_DATE(ATTENDING_PHYSICIAN_IEN) 
	WITH 			FILLFACTOR = 100
