Create PROCEDURE [dbo].[upCreateIndexes_ANTIBIOTIC_SUSCEPTIBILITY] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_ANTIBIOTIC_SUSCEPTIBILITY')
		DROP INDEX ANTIBIOTIC_SUSCEPTIBILITY.ind_ANTIBIOTIC_SUSCEPTIBILITY
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_ANTIBIOTIC_SUSCEPTIBILITY_KEY_ANTIBIOTIC_SUSCEPTIBILITY')
		DROP INDEX ANTIBIOTIC_SUSCEPTIBILITY.IX_ANTIBIOTIC_SUSCEPTIBILITY_KEY_ANTIBIOTIC_SUSCEPTIBILITY
		                                                                
	CREATE INDEX 	IX_ANTIBIOTIC_SUSCEPTIBILITY_KEY_ANTIBIOTIC_SUSCEPTIBILITY
	ON 			ANTIBIOTIC_SUSCEPTIBILITY(KEY_ANTIBIOTIC_SUSCEPTIBILITY)
	WITH 			FILLFACTOR = 100
