CREATE PROCEDURE [dbo].[upCreateIndexes_OUTPATIENT_DISPOSITION] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_OUTPATIENT_DISPOSITION')
	DROP INDEX OUTPATIENT_DISPOSITION.ind_OUTPATIENT_DISPOSITION

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_OUTPATIENT_DISPOSITION_KEY_OUTPATIENT_DISPOSITION')
	DROP INDEX OUTPATIENT_DISPOSITION.IX_OUTPATIENT_DISPOSITION_KEY_OUTPATIENT_DISPOSITION
	
	CREATE INDEX IX_OUTPATIENT_DISPOSITION_KEY_OUTPATIENT_DISPOSITION
	ON			OUTPATIENT_DISPOSITION(KEY_OUTPATIENT_DISPOSITION)
	WITH		FILLFACTOR = 100
