CREATE PROCEDURE [dbo].[upCreateIndexes_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY')
		DROP INDEX NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY.ind_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY')
		DROP INDEX NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY.IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY
		
	CREATE INDEX 	IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY
	ON 			NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY(KEY_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_PCM_IEN')
		DROP INDEX NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY.IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_PCM_IEN				
	CREATE INDEX 	IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_PCM_IEN
	ON 			NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY(PCM_IEN)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT')
		DROP INDEX NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY.IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT				
	CREATE INDEX 	IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT
	ON 			NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY(KEY_NED_PATIENT)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT$ENROLLMENT_HISTORY')
		DROP INDEX NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY.IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT$ENROLLMENT_HISTORY				
	CREATE INDEX 	IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_KEY_NED_PATIENT$ENROLLMENT_HISTORY
	ON 			NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY(KEY_NED_PATIENT$ENROLLMENT_HISTORY)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_Combined')
		DROP INDEX NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY.IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_Combined			
	CREATE CLUSTERED INDEX 	IX_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY_Combined
	ON 			NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY(KEY_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY,KEY_NED_PATIENT$ENROLLMENT_HISTORY,KEY_NED_PATIENT)
	WITH 			FILLFACTOR = 100
