CREATE PROCEDURE [dbo].[upCreateIndexes_WARD_LOCATION$ROOM$BED] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_WARD_LOCATION$ROOM$BED')
	DROP INDEX WARD_LOCATION$ROOM$BED.ind_WARD_LOCATION$ROOM$BED
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_WARD_LOCATION$ROOM$BED_KEY_WARD_LOCATION$ROOM$BED')
	DROP INDEX WARD_LOCATION$ROOM$BED.IX_WARD_LOCATION$ROOM$BED_KEY_WARD_LOCATION$ROOM$BED

	CREATE INDEX IX_WARD_LOCATION$ROOM$BED_KEY_WARD_LOCATION$ROOM$BED
	ON WARD_LOCATION$ROOM$BED(KEY_WARD_LOCATION$ROOM$BED)
	WITH		FILLFACTOR = 100
