CREATE PROCEDURE [dbo].[upCreateIndexes_APPOINTMENT_AUDIT_TRAIL] AS

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_APPOINTMENT_AUDIT_TRAIL')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.ind_APPOINTMENT_AUDIT_TRAIL
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_AUDIT_TRAIL_KEY_APPOINTMENT_AUDIT_TRAIL')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.IX_APPOINTMENT_AUDIT_TRAIL_KEY_APPOINTMENT_AUDIT_TRAIL
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_AUDIT_TRAIL_KEY_APPOINTMENT_AUDIT_TRAIL
	ON 			APPOINTMENT_AUDIT_TRAIL(KEY_APPOINTMENT_AUDIT_TRAIL)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_AUDIT_TRAIL_PATIENT_NAME_IEN')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.IX_APPOINTMENT_AUDIT_TRAIL_PATIENT_NAME_IEN
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_AUDIT_TRAIL_PATIENT_NAME_IEN
	ON 			APPOINTMENT_AUDIT_TRAIL(PATIENT_NAME_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_AUDIT_TRAIL_CLERK_IEN')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.IX_APPOINTMENT_AUDIT_TRAIL_CLERK_IEN
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_AUDIT_TRAIL_CLERK_IEN
	ON 			APPOINTMENT_AUDIT_TRAIL(CLERK_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_AUDIT_TRAIL_APPOINTMENT_STATUS_IEN')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.IX_APPOINTMENT_AUDIT_TRAIL_APPOINTMENT_STATUS_IEN
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_AUDIT_TRAIL_APPOINTMENT_STATUS_IEN
	ON 			APPOINTMENT_AUDIT_TRAIL(APPOINTMENT_STATUS_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_AUDIT_TRAIL_DIVISION_IEN')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.IX_APPOINTMENT_AUDIT_TRAIL_DIVISION_IEN
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_AUDIT_TRAIL_DIVISION_IEN
	ON 			APPOINTMENT_AUDIT_TRAIL(DIVISION_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_AUDIT_TRAIL_CLINIC_IEN')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.IX_APPOINTMENT_AUDIT_TRAIL_CLINIC_IEN
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_AUDIT_TRAIL_CLINIC_IEN
	ON 			APPOINTMENT_AUDIT_TRAIL(CLINIC_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_AUDIT_TRAIL_STATUS_MODIFIER')
		DROP INDEX APPOINTMENT_AUDIT_TRAIL.IX_APPOINTMENT_AUDIT_TRAIL_STATUS_MODIFIER
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_AUDIT_TRAIL_STATUS_MODIFIER
	ON 			APPOINTMENT_AUDIT_TRAIL(STATUS_MODIFIER)
	WITH 			FILLFACTOR = 100
