CREATE PROCEDURE [dbo].[upCreateIndexes_FAMILY_MEMBER_PREFIX] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_FAMILY_MEMBER_PREFIX')
		DROP INDEX FAMILY_MEMBER_PREFIX.ind_FAMILY_MEMBER_PREFIX
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_FAMILY_MEMBER_PREFIX_KEY_FAMILY_MEMBER_PREFIX')
		DROP INDEX FAMILY_MEMBER_PREFIX.IX_FAMILY_MEMBER_PREFIX_KEY_FAMILY_MEMBER_PREFIX
		                                                                
	CREATE INDEX 	IX_FAMILY_MEMBER_PREFIX_KEY_FAMILY_MEMBER_PREFIX
	ON 			FAMILY_MEMBER_PREFIX(KEY_FAMILY_MEMBER_PREFIX)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_FAMILY_MEMBER_PREFIX_NUMBER_')
		DROP INDEX FAMILY_MEMBER_PREFIX.IX_FAMILY_MEMBER_PREFIX_NUMBER_
		                                                                
	CREATE INDEX 	IX_FAMILY_MEMBER_PREFIX_NUMBER_
	ON 			FAMILY_MEMBER_PREFIX(NUMBER_)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_FAMILY_MEMBER_PREFIX_FMP')
		DROP INDEX FAMILY_MEMBER_PREFIX.IX_FAMILY_MEMBER_PREFIX_FMP
		                                                                
	CREATE INDEX 	IX_FAMILY_MEMBER_PREFIX_FMP
	ON 			FAMILY_MEMBER_PREFIX(FMP)
	WITH 			FILLFACTOR = 100
