CREATE PROCEDURE [dbo].[upCreateIndexes_APPOINTMENT_TYPE] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_APPOINTMENT_TYPE')
		DROP INDEX APPOINTMENT_TYPE.ind_APPOINTMENT_TYPE
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_TYPE_KEY_APPOINTMENT_TYPE')
		DROP INDEX APPOINTMENT_TYPE.IX_APPOINTMENT_TYPE_KEY_APPOINTMENT_TYPE
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_TYPE_KEY_APPOINTMENT_TYPE
	ON 			APPOINTMENT_TYPE(KEY_APPOINTMENT_TYPE)
	WITH 			FILLFACTOR = 100
