CREATE PROCEDURE [dbo].[upCreateIndexes_APPOINTMENT_REFUSAL_REASON] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_APPOINTMENT_REFUSAL_REASON')
		DROP INDEX APPOINTMENT_REFUSAL_REASON.ind_APPOINTMENT_REFUSAL_REASON
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_APPOINTMENT_REFUSAL_REASON_KEY_APPOINTMENT_REFUSAL_REASON')
		DROP INDEX APPOINTMENT_REFUSAL_REASON.IX_APPOINTMENT_REFUSAL_REASON_KEY_APPOINTMENT_REFUSAL_REASON
		                                                                
	CREATE INDEX 	IX_APPOINTMENT_REFUSAL_REASON_KEY_APPOINTMENT_REFUSAL_REASON
	ON 			APPOINTMENT_REFUSAL_REASON(KEY_APPOINTMENT_REFUSAL_REASON)
	WITH 			FILLFACTOR = 100
