CREATE PROCEDURE [dbo].[upCreateIndexes_LAB_INTERPRETATION_FILE] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_LAB_INTERPRETATION_FILE')
		DROP INDEX LAB_INTERPRETATION_FILE.ind_LAB_INTERPRETATION_FILE
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_INTERPRETATION_FILE_KEY_LAB_INTERPRETATION_FILE')
		DROP INDEX LAB_INTERPRETATION_FILE.IX_LAB_INTERPRETATION_FILE_KEY_LAB_INTERPRETATION_FILE
		                                                                
	CREATE INDEX 	IX_LAB_INTERPRETATION_FILE_KEY_LAB_INTERPRETATION_FILE
	ON 			LAB_INTERPRETATION_FILE(KEY_LAB_INTERPRETATION_FILE)
	WITH 			FILLFACTOR = 100
