CREATE PROCEDURE [dbo].[upCreateIndexes_NED_PATIENT] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_NED_PATIENT')
		DROP INDEX NED_PATIENT.ind_NED_PATIENT
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NED_PATIENT_KEY_NED_PATIENT')
		DROP INDEX NED_PATIENT.IX_NED_PATIENT_KEY_NED_PATIENT
		
	CREATE INDEX 	IX_NED_PATIENT_KEY_NED_PATIENT
	ON 			NED_PATIENT(KEY_NED_PATIENT)
	WITH 			FILLFACTOR = 100
		
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NED_PATIENT_PATIENT_NAME_IEN')
		DROP INDEX NED_PATIENT.IX_NED_PATIENT_PATIENT_NAME_IEN		
	CREATE INDEX 	IX_NED_PATIENT_PATIENT_NAME_IEN
	ON 			NED_PATIENT(PATIENT_NAME_IEN)
	WITH 			FILLFACTOR = 100
