CREATE PROCEDURE [dbo].[upCreateIndexes_ENCOUNTER] AS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'ind_ENCOUNTER')
		DROP INDEX ENCOUNTER.ind_ENCOUNTER
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_ENCOUNTER_KEY_ENCOUNTER')
		DROP INDEX ENCOUNTER.IX_ENCOUNTER_KEY_ENCOUNTER
		
	CREATE INDEX 	IX_ENCOUNTER_KEY_ENCOUNTER
	ON 			ENCOUNTER(KEY_ENCOUNTER)
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_ENCOUNTER_PATIENT_IEN')
		DROP INDEX ENCOUNTER.IX_ENCOUNTER_PATIENT_IEN				
				                               
	CREATE INDEX	 	IX_ENCOUNTER_PATIENT_IEN
	ON 			ENCOUNTER(PATIENT_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_ENCOUNTER_PROVIDER_IEN')
		DROP INDEX ENCOUNTER.IX_ENCOUNTER_PROVIDER_IEN								
	CREATE INDEX 	IX_ENCOUNTER_PROVIDER_IEN
	ON 			ENCOUNTER(PROVIDER_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_ENCOUNTER_DRG_CODE_IEN')
		DROP INDEX ENCOUNTER.IX_ENCOUNTER_DRG_CODE_IEN												
	CREATE INDEX 	IX_ENCOUNTER_DRG_CODE_IEN
	ON 			ENCOUNTER(DRG_CODE_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_ENCOUNTER_DATE_TIME')
		DROP INDEX ENCOUNTER.IX_ENCOUNTER_DATE_TIME												
	CREATE CLUSTERED INDEX 	IX_ENCOUNTER_DATE_TIME
	ON 			ENCOUNTER(DATE_TIME)
	WITH 			FILLFACTOR = 100
