CREATE PROCEDURE [dbo].[upCreateIndexes_CPT_HCPCS$MODIFIER] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_CPT_HCPCS$MODIFIER')
		DROP INDEX CPT_HCPCS$MODIFIER.ind_CPT_HCPCS$MODIFIER
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_CPT_HCPCS$MODIFIER_KEY_CPT_HCPCS$MODIFIER')
		DROP INDEX CPT_HCPCS$MODIFIER.IX_CPT_HCPCS$MODIFIER_KEY_CPT_HCPCS$MODIFIER
		                                                                
	CREATE INDEX 	IX_CPT_HCPCS$MODIFIER_KEY_CPT_HCPCS$MODIFIER
	ON 			CPT_HCPCS$MODIFIER(KEY_CPT_HCPCS$MODIFIER)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_CPT_HCPCS$MODIFIER_KEY_CPT_HCPCS')
		DROP INDEX CPT_HCPCS$MODIFIER.IX_CPT_HCPCS$MODIFIER_KEY_CPT_HCPCS
		                                                                
	CREATE INDEX 	IX_CPT_HCPCS$MODIFIER_KEY_CPT_HCPCS
	ON 			CPT_HCPCS$MODIFIER(KEY_CPT_HCPCS)
	WITH 			FILLFACTOR = 100
