create PROCEDURE [dbo].[upCreateIndexes_AHLTA_CERVICAL_ICD9] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_AHLTA_CERVICAL_ICD9')
		DROP INDEX AHLTA_CERVICAL_ICD9.ind_AHLTA_CERVICAL_ICD9
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_AHLTA_CERVICAL_ICD9_FMP_SPONSOR_SSN')
		DROP INDEX AHLTA_CERVICAL_ICD9.IX_AHLTA_CERVICAL_ICD9_FMP_SPONSOR_SSN
		                                                                
	CREATE INDEX IX_AHLTA_CERVICAL_ICD9_FMP_SPONSOR_SSN
	ON 			AHLTA_CERVICAL_ICD9([FMP Sponsor SSN])
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_AHLTA_CERVICAL_ICD9_FMP_SponsorSSN')
		DROP INDEX AHLTA_CERVICAL_ICD9.IX_AHLTA_CERVICAL_ICD9_FMP_SponsorSSN

	CREATE CLUSTERED INDEX IX_AHLTA_CERVICAL_ICD9_FMP_SponsorSSN
	ON 			AHLTA_CERVICAL_ICD9(FMP,SponsorSSN)
	WITH 			FILLFACTOR = 100
