CREATE PROCEDURE [dbo].[upCreateIndexes_MILITARY_GRADE_RANK] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_MILITARY_GRADE_RANK')
		DROP INDEX MILITARY_GRADE_RANK.ind_MILITARY_GRADE_RANK
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MILITARY_GRADE_RANK_KEY_MILITARY_GRADE_RANK')
		DROP INDEX MILITARY_GRADE_RANK.IX_MILITARY_GRADE_RANK_KEY_MILITARY_GRADE_RANK
		
	CREATE INDEX 	IX_MILITARY_GRADE_RANK_KEY_MILITARY_GRADE_RANK
	ON 			MILITARY_GRADE_RANK(KEY_MILITARY_GRADE_RANK)
	WITH 			FILLFACTOR = 100
