create PROCEDURE [dbo].[upCreateIndexes_POP_HEALTH_ATIDEPRESSANT] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_POP_HEALTH_ANTIDEPRESSANT')
		DROP INDEX POP_HEALTH_ANTIDEPRESSANT.ind_POP_HEALTH_ANTIDEPRESSANT
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_ANTIDEPRESSANT_EDIPN')
		DROP INDEX POP_HEALTH_ANTIDEPRESSANT.IX_POP_HEALTH_ANTIDEPRESSANT_EDIPN
		                                                                
	CREATE INDEX 	IX_POP_HEALTH_ANTIDEPRESSANT_EDIPN
	ON 			POP_HEALTH_ANTIDEPRESSANT(EDIPN)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_ANTIDEPRESSANT_FMP')
		DROP INDEX POP_HEALTH_ANTIDEPRESSANT.IX_POP_HEALTH_ANTIDEPRESSANT_FMP
		                                                                
	CREATE INDEX 	IX_POP_HEALTH_ANTIDEPRESSANT_FMP
	ON 			POP_HEALTH_ANTIDEPRESSANT(FMP)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_ANTIDEPRESSANT_CtrlRxDate')
		DROP INDEX POP_HEALTH_ANTIDEPRESSANT.IX_POP_HEALTH_ANTIDEPRESSANT_EarliestPrescriptionDate
		                                                                
	CREATE INDEX 	IX_POP_HEALTH_ANTIDEPRESSANT_EarliestPrescriptionDate
	ON 			POP_HEALTH_ANTIDEPRESSANT([Earliest Prescription Date])
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_ANTIDEPRESSANT_LastPrescriptionDate')
		DROP INDEX POP_HEALTH_ANTIDEPRESSANT.IX_POP_HEALTH_ANTIDEPRESSANT_LastPrescriptionDate
		                                                                
	CREATE INDEX 	IX_POP_HEALTH_ANTIDEPRESSANT_LastPrescriptionDate
	ON 			POP_HEALTH_ANTIDEPRESSANT([Last Prescription Date])
	WITH 			FILLFACTOR = 100

	--IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_ASTHMA_FMP_EDIPN')
	--	DROP INDEX POP_HEALTH_ASTHMA.IX_POP_HEALTH_ASTHMA_FMP_EDIPN
		                                                                
	--CREATE INDEX 	IX_POP_HEALTH_ASTHMA_FMP_EDIPN
	--ON 			POP_HEALTH_ASTHMA(FMP,EDIPN)
	--WITH 			FILLFACTOR = 100
