CREATE PROCEDURE [dbo].[upCreateIndexes_KG_ADC_DATA] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_KG_ADC_DATA')
		DROP INDEX KG_ADC_DATA.ind_KG_ADC_DATA
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_KG_ADC_DATA_KEY_KG_ADC_DATA')
		DROP INDEX KG_ADC_DATA.IX_KG_ADC_DATA_KEY_KG_ADC_DATA
		
	CREATE UNIQUE CLUSTERED INDEX 	IX_KG_ADC_DATA_KEY_KG_ADC_DATA
	ON 			KG_ADC_DATA(KEY_KG_ADC_DATA)
	WITH 			FILLFACTOR = 100
		
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_KG_ADC_DATA_APPOINTMENT_IEN')
		DROP INDEX KG_ADC_DATA.IX_KG_ADC_DATA_APPOINTMENT_IEN
	CREATE INDEX 	IX_KG_ADC_DATA_APPOINTMENT_IEN
	ON 			KG_ADC_DATA(APPOINTMENT_IEN)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_KG_ADC_DATA_CHIEF_COMPLAINT_IEN')
		DROP INDEX KG_ADC_DATA.IX_KG_ADC_DATA_CHIEF_COMPLAINT_IEN			
	CREATE INDEX 	IX_KG_ADC_DATA_CHIEF_COMPLAINT_IEN
	ON 			KG_ADC_DATA(CHIEF_COMPLAINT_IEN)
	WITH 			FILLFACTOR = 100
