CREATE PROCEDURE [dbo].[upCreateIndexes_ORDER_PRIORITY] AS

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_ORDER_PRIORITY')
		DROP INDEX ORDER_PRIORITY.ind_ORDER_PRIORITY

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_ORDER_PRIORITY_KEY_ORDER_PRIORITY')
		DROP INDEX	ORDER_PRIORITY.IX_ORDER_PRIORITY_KEY_ORDER_PRIORITY
	
	CREATE INDEX IX_ORDER_PRIORITY_KEY_ORDER_PRIORITY
	ON			ORDER_PRIORITY(KEY_ORDER_PRIORITY)
	WITH			FILLFACTOR = 100
