CREATE PROCEDURE [dbo].[upCreateIndexes_MCP_ALTERNATE_CARE_VALUE] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_MCP_ALTERNATE_CARE_VALUE')
		DROP INDEX MCP_ALTERNATE_CARE_VALUE.ind_MCP_ALTERNATE_CARE_VALUE
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_ALTERNATE_CARE_VALUE_KEY_MCP_ALTERNATE_CARE_VALUE')
		DROP INDEX MCP_ALTERNATE_CARE_VALUE.IX_MCP_ALTERNATE_CARE_VALUE_KEY_MCP_ALTERNATE_CARE_VALUE
		                                                                
	CREATE INDEX 	IX_MCP_ALTERNATE_CARE_VALUE_KEY_MCP_ALTERNATE_CARE_VALUE
	ON 			MCP_ALTERNATE_CARE_VALUE(KEY_MCP_ALTERNATE_CARE_VALUE)
	WITH 			FILLFACTOR = 100
