CREATE PROCEDURE [dbo].[upCreateIndexes_AP_DESCRIPTION_DIAGNOSIS] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_AP_DESCRIPTION_DIAGNOSIS')
		DROP INDEX AP_DESCRIPTION_DIAGNOSIS.ind_AP_DESCRIPTION_DIAGNOSIS
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_AP_DESCRIPTION_DIAGNOSIS_KEY_AP_DESCRIPTION_DIAGNOSIS')
		DROP INDEX AP_DESCRIPTION_DIAGNOSIS.IX_AP_DESCRIPTION_DIAGNOSIS_KEY_AP_DESCRIPTION_DIAGNOSIS
		                                                                
	CREATE INDEX 	IX_AP_DESCRIPTION_DIAGNOSIS_KEY_AP_DESCRIPTION_DIAGNOSIS
	ON 			AP_DESCRIPTION_DIAGNOSIS(KEY_AP_DESCRIPTION_DIAGNOSIS)
	WITH 			FILLFACTOR = 100
