CREATE PROCEDURE [dbo].[upCreateIndexes_POP_HEALTH_MAMMOGRAPHY] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_POP_HEALTH_MAMMOGRAPHY')
		DROP INDEX POP_HEALTH_MAMMOGRAPHY.ind_POP_HEALTH_MAMMOGRAPHY
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_MAMMOGRAPHY_EDIPN')
		DROP INDEX POP_HEALTH_MAMMOGRAPHY.IX_POP_HEALTH_MAMMOGRAPHY_EDIPN
		                                                                
	CREATE INDEX 	IX_POP_HEALTH_MAMMOGRAPHY_EDIPN
	ON 			POP_HEALTH_MAMMOGRAPHY(EDIPN)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_MAMMOGRAPHY_FMP')
		DROP INDEX POP_HEALTH_MAMMOGRAPHY.IX_POP_HEALTH_MAMMOGRAPHY_FMP
		                                                                
	CREATE INDEX 	IX_POP_HEALTH_MAMMOGRAPHY_FMP
	ON 			POP_HEALTH_MAMMOGRAPHY(FMP)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_MAMMOGRAPHY_LastExamDate')
		DROP INDEX POP_HEALTH_MAMMOGRAPHY.IX_POP_HEALTH_MAMMOGRAPHY_LastExamDate
		                                                                
	CREATE INDEX 	IX_POP_HEALTH_MAMMOGRAPHY_LastExamDate
	ON 			POP_HEALTH_MAMMOGRAPHY(LastExamDate)
	WITH 			FILLFACTOR = 100


	--IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_POP_HEALTH_MAMMOGRAPHY_FMP_SponsorSSN')
	--	DROP INDEX POP_HEALTH_MAMMOGRAPHY.IX_POP_HEALTH_MAMMOGRAPHY_FMP_SponsorSSN
		                                                                
	--CREATE INDEX 	IX_POP_HEALTH_MAMMOGRAPHY_FMP_SponsorSSN
	--ON 			POP_HEALTH_MAMMOGRAPHY(FMP,SponsorSSN)
	--WITH 			FILLFACTOR = 100
