create PROCEDURE [dbo].[upCreateIndexes_MCP_REFERRAL$APPOINTMENT_REFUSALS] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_MCP_REFERRAL$APPOINTMENT_REFUSALS')
		DROP INDEX MCP_REFERRAL$APPOINTMENT_REFUSALS.ind_MCP_REFERRAL$APPOINTMENT_REFUSALS
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL')
		DROP INDEX MCP_REFERRAL$APPOINTMENT_REFUSALS.IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL
	ON 			MCP_REFERRAL$APPOINTMENT_REFUSALS(KEY_MCP_REFERRAL)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL$APPOINTMENT_REFUSALS')
		DROP INDEX MCP_REFERRAL$APPOINTMENT_REFUSALS.IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL$APPOINTMENT_REFUSALS
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL$APPOINTMENT_REFUSALS_KEY_MCP_REFERRAL$APPOINTMENT_REFUSALS
	ON 			MCP_REFERRAL$APPOINTMENT_REFUSALS(KEY_MCP_REFERRAL$APPOINTMENT_REFUSALS)
	WITH 			FILLFACTOR = 100
