CREATE PROCEDURE [dbo].[upCreateIndexes_NDI_ELIGIBILITY] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_NDI_ELIGIBILITY')
		DROP INDEX NDI_ELIGIBILITY.ind_NDI_ELIGIBILITY
		
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NDI_ELIGIBILITY_PCM_ID')
		DROP INDEX NDI_ELIGIBILITY.IX_NDI_ELIGIBILITY_PCM_ID
		
	CREATE INDEX 	IX_NDI_ELIGIBILITY_PCM_ID
	ON 			NDI_ELIGIBILITY(PCM_ID)
	WITH 			FILLFACTOR = 100
		
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NDI_ELIGIBILITY_PATIENT_NAME_IEN')
		DROP INDEX NDI_ELIGIBILITY.IX_NDI_ELIGIBILITY_PATIENT_NAME_IEN		
	CREATE INDEX 	IX_NDI_ELIGIBILITY_PATIENT_NAME_IEN
	ON 			NDI_ELIGIBILITY(PATIENT_NAME_IEN)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_NDI_ELIGIBILITY_PCM_DMIS_IEN')
		DROP INDEX NDI_ELIGIBILITY.IX_NDI_ELIGIBILITY_PCM_DMIS_IEN		
	CREATE INDEX 	IX_NDI_ELIGIBILITY_PCM_DMIS_IEN
	ON 			NDI_ELIGIBILITY(PCM_DMIS_IEN)
	WITH 			FILLFACTOR = 100
