CREATE PROCEDURE [dbo].[upCreateIndexes_SOURCE_OF_ADMISSION] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_SOURCE_OF_ADMISSION')
	DROP INDEX SOURCE_OF_ADMISSION.ind_SOURCE_OF_ADMISSION
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_SOURCE_OF_ADMISSION_KEY_SOURCE_OF_ADMISSION')
	DROP INDEX SOURCE_OF_ADMISSION.IX_SOURCE_OF_ADMISSION_KEY_SOURCE_OF_ADMISSION

	CREATE INDEX IX_SOURCE_OF_ADMISSION_KEY_SOURCE_OF_ADMISSION
	ON SOURCE_OF_ADMISSION(KEY_SOURCE_OF_ADMISSION)
	WITH		FILLFACTOR = 100
