CREATE PROCEDURE [dbo].[upCreateIndexes_PRODUCTIVITY] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_PRODUCTIVITY')
		DROP INDEX PRODUCTIVITY.ind_PRODUCTIVITY
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRODUCTIVITY_PatientAppointmentKey')
		DROP INDEX PRODUCTIVITY.IX_PRODUCTIVITY_PatientAppointmentKey
		
	CREATE INDEX 	IX_PRODUCTIVITY_PatientAppointmentKey
	ON 			PRODUCTIVITY(PatientAppointmentKey) 
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRODUCTIVITY_AppointmentStatusCode')
		DROP INDEX PRODUCTIVITY.IX_PRODUCTIVITY_AppointmentStatusCode
		
	CREATE INDEX 	IX_PRODUCTIVITY_AppointmentStatusCode
	ON 			PRODUCTIVITY(AppointmentStatusCode) 
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRODUCTIVITY_AppointmentType')
		DROP INDEX PRODUCTIVITY.IX_PRODUCTIVITY_AppointmentType
		
	CREATE INDEX 	IX_PRODUCTIVITY_AppointmentType
	ON 			PRODUCTIVITY(AppointmentType) 
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRODUCTIVITY_ProviderCode')
		DROP INDEX PRODUCTIVITY.IX_PRODUCTIVITY_ProviderCode
		
	CREATE INDEX 	IX_PRODUCTIVITY_ProviderCode
	ON 			PRODUCTIVITY(ProviderCode) 
	WITH 			FILLFACTOR = 100
