CREATE PROCEDURE [dbo].[upCreateIndexes_RECORD_MOVEMENT_TYPES] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_RECORD_MOVEMENT_TYPES')
		DROP INDEX RECORD_MOVEMENT_TYPES.ind_RECORD_MOVEMENT_TYPES
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_RECORD_MOVEMENT_TYPES_KEY_RECORD_MOVEMENT_TYPES')
		DROP INDEX RECORD_MOVEMENT_TYPES.IX_RECORD_MOVEMENT_TYPES_KEY_RECORD_MOVEMENT_TYPES
		                                                                
	CREATE INDEX 	IX_RECORD_MOVEMENT_TYPES_KEY_RECORD_MOVEMENT_TYPES
	ON 			RECORD_MOVEMENT_TYPES(KEY_RECORD_MOVEMENT_TYPES)
	WITH 			FILLFACTOR = 100
