CREATE PROCEDURE [dbo].[upCreateIndexes_ENCOUNTER$DIAGNOSIS__FREE_TEXT_] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_ENCOUNTER$DIAGNOSIS__FREE_TEXT_')
		DROP INDEX ENCOUNTER$DIAGNOSIS__FREE_TEXT_.ind_ENCOUNTER$DIAGNOSIS__FREE_TEXT_
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_ENCOUNTER$DIAGNOSIS__FREE_TEXT__KEY_ENCOUNTER$DIAGNOSIS__FREE_TEXT_')
		DROP INDEX ENCOUNTER$DIAGNOSIS__FREE_TEXT_.IX_ENCOUNTER$DIAGNOSIS__FREE_TEXT__KEY_ENCOUNTER$DIAGNOSIS__FREE_TEXT_
		                                                                
	CREATE INDEX 	IX_ENCOUNTER$DIAGNOSIS__FREE_TEXT__KEY_ENCOUNTER$DIAGNOSIS__FREE_TEXT_
	ON 			ENCOUNTER$DIAGNOSIS__FREE_TEXT_(KEY_ENCOUNTER$DIAGNOSIS__FREE_TEXT_)
	WITH 			FILLFACTOR = 100
