CREATE PROCEDURE [dbo].[upCreateIndexes_BORROWERS_FILE_AREAS] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_BORROWERS_FILE_AREAS')
		DROP INDEX BORROWERS_FILE_AREAS.ind_BORROWERS_FILE_AREAS
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_BORROWERS_FILE_AREAS_KEY_BORROWERS_FILE_AREAS')
		DROP INDEX BORROWERS_FILE_AREAS.IX_BORROWERS_FILE_AREAS_KEY_BORROWERS_FILE_AREAS
		                                                                
	CREATE INDEX 	IX_BORROWERS_FILE_AREAS_KEY_BORROWERS_FILE_AREAS
	ON 			BORROWERS_FILE_AREAS(KEY_BORROWERS_FILE_AREAS)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_BORROWERS_FILE_AREAS_NUMBER_')
		DROP INDEX BORROWERS_FILE_AREAS.IX_BORROWERS_FILE_AREAS_NUMBER_
		                                                                
	CREATE INDEX 	IX_BORROWERS_FILE_AREAS_NUMBER_
	ON 			BORROWERS_FILE_AREAS(NUMBER_)
	WITH 			FILLFACTOR = 100
