CREATE PROCEDURE [dbo].[upCreateIndexes_FORMULARY_GROUP] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_FORMULARY_GROUP')
		DROP INDEX FORMULARY_GROUP.ind_FORMULARY_GROUP
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_FORMULARY_GROUP_KEY_FORMULARY_GROUP')
		DROP INDEX FORMULARY_GROUP.IX_FORMULARY_GROUP_KEY_FORMULARY_GROUP
		                                                                
	CREATE INDEX 	IX_FORMULARY_GROUP_KEY_FORMULARY_GROUP
	ON 			FORMULARY_GROUP(KEY_FORMULARY_GROUP)
	WITH 			FILLFACTOR = 100
