CREATE PROCEDURE [dbo].[upCreateIndexes_MEPRS_CODES] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_MEPRS_CODES')
		DROP INDEX MEPRS_CODES.ind_MEPRS_CODES
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MEPRS_CODES_KEY_MEPRS_CODES')
		DROP INDEX MEPRS_CODES.IX_MEPRS_CODES_KEY_MEPRS_CODES
		
	CREATE INDEX 	IX_MEPRS_CODES_KEY_MEPRS_CODES
	ON 			MEPRS_CODES(KEY_MEPRS_CODES)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MEPRS_CODES_DMIS_ID_IEN')
		DROP INDEX MEPRS_CODES.IX_MEPRS_CODES_DMIS_ID_IEN				
	CREATE INDEX 	IX_MEPRS_CODES_DMIS_ID_IEN
	ON 			MEPRS_CODES(DMIS_ID_IEN)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MEPRS_CODES_CODE')
		DROP INDEX MEPRS_CODES.IX_MEPRS_CODES_CODE			
	CREATE INDEX 	IX_MEPRS_CODES_CODE
	ON 			MEPRS_CODES(CODE)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MEPRS_CODES_KEY_MEPRS_CODES')
		DROP INDEX MEPRS_CODES.IX_MEPRS_CODES_KEY_MEPRS_CODES				
	CREATE INDEX 	IX_MEPRS_CODES_KEY_MEPRS_CODES
	ON 			MEPRS_CODES(KEY_MEPRS_CODES)
	WITH 			FILLFACTOR = 100
