CREATE PROCEDURE [dbo].[upCreateIndexes_BRANCH_OF_SERVICE] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_BRANCH_OF_SERVICE')
		DROP INDEX BRANCH_OF_SERVICE.ind_BRANCH_OF_SERVICE
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_BRANCH_OF_SERVICE_KEY_BRANCH_OF_SERVICE')
		DROP INDEX BRANCH_OF_SERVICE.IX_BRANCH_OF_SERVICE_KEY_BRANCH_OF_SERVICE
		                                                                
	CREATE INDEX 	IX_BRANCH_OF_SERVICE_KEY_BRANCH_OF_SERVICE
	ON 			BRANCH_OF_SERVICE(KEY_BRANCH_OF_SERVICE)
	WITH 			FILLFACTOR = 100
