CREATE PROCEDURE [dbo].[upCreateIndexes_CPT_HCPCS] AS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'ind_CPT_HCPCS')
		DROP INDEX CPT_HCPCS.ind_CPT_HCPCS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_CPT_HCPCS_KEY_CPT_HCPCS')
		DROP INDEX CPT_HCPCS.IX_CPT_HCPCS_KEY_CPT_HCPCS
		
	CREATE INDEX 	IX_CPT_HCPCS_KEY_CPT_HCPCS
	ON 			CPT_HCPCS(KEY_CPT_HCPCS)
	WITH 			FILLFACTOR = 100
				
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_CPT_HCPCS_CODE')
		DROP INDEX CPT_HCPCS.IX_CPT_HCPCS_CODE				
	CREATE INDEX 	IX_CPT_HCPCS_CODE
	ON 			CPT_HCPCS(CODE)
	WITH 			FILLFACTOR = 100
