CREATE PROCEDURE [dbo].[upCreateIndexes_LAB_TEST$LAB_WORK_ELEMENT] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_LAB_TEST$LAB_WORK_ELEMENT')
		DROP INDEX LAB_TEST$LAB_WORK_ELEMENT.ind_LAB_TEST$LAB_WORK_ELEMENT
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST$LAB_WORK_ELEMENT')
		DROP INDEX LAB_TEST$LAB_WORK_ELEMENT.IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST$LAB_WORK_ELEMENT
		
	CREATE INDEX 	IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST$LAB_WORK_ELEMENT
	ON 			LAB_TEST$LAB_WORK_ELEMENT(KEY_LAB_TEST$LAB_WORK_ELEMENT)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST')
		DROP INDEX LAB_TEST$LAB_WORK_ELEMENT.IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST
	CREATE INDEX 	IX_LAB_TEST$LAB_WORK_ELEMENT_KEY_LAB_TEST
	ON 			LAB_TEST$LAB_WORK_ELEMENT(KEY_LAB_TEST)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_TEST$LAB_WORK_ELEMENT_LAB_WORK_ELEMENT_IEN')
		DROP INDEX LAB_TEST$LAB_WORK_ELEMENT.IX_LAB_TEST$LAB_WORK_ELEMENT_LAB_WORK_ELEMENT_IEN
	CREATE INDEX 	IX_LAB_TEST$LAB_WORK_ELEMENT_LAB_WORK_ELEMENT_IEN
	ON 			LAB_TEST$LAB_WORK_ELEMENT(LAB_WORK_ELEMENT_IEN)
	WITH 			FILLFACTOR = 100
