CREATE PROCEDURE [dbo].[upCreateIndexes_MCP_REFERRAL] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_MCP_REFERRAL')
		DROP INDEX MCP_REFERRAL.ind_MCP_REFERRAL
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL_KEY_MCP_REFERRAL')
		DROP INDEX MCP_REFERRAL.IX_MCP_REFERRAL_KEY_MCP_REFERRAL
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL_KEY_MCP_REFERRAL
	ON 			MCP_REFERRAL(KEY_MCP_REFERRAL)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL_ORDER_IEN')
		DROP INDEX MCP_REFERRAL.IX_MCP_REFERRAL_ORDER_IEN
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL_ORDER_IEN
	ON 			MCP_REFERRAL(ORDER_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL_REFERRAL_FROM_IEN')
		DROP INDEX MCP_REFERRAL.IX_MCP_REFERRAL_REFERRAL_FROM_IEN
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL_REFERRAL_FROM_IEN
	ON 			MCP_REFERRAL(REFERRAL_FROM_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL_REFERRED_BY_IEN')
		DROP INDEX MCP_REFERRAL.IX_MCP_REFERRAL_REFERRED_BY_IEN
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL_REFERRED_BY_IEN
	ON 			MCP_REFERRAL(REFERRED_BY_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL_REFERRED_TO_PROVIDER_IEN')
		DROP INDEX MCP_REFERRAL.IX_MCP_REFERRAL_REFERRED_TO_PROVIDER_IEN
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL_REFERRED_TO_PROVIDER_IEN
	ON 			MCP_REFERRAL(REFERRED_TO_PROVIDER_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL_REFERRED_TO_PLACE_OF_CARE_IEN')
		DROP INDEX MCP_REFERRAL.IX_MCP_REFERRAL_REFERRED_TO_PLACE_OF_CARE_IEN
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL_REFERRED_TO_PLACE_OF_CARE_IEN
	ON 			MCP_REFERRAL(REFERRED_TO_PLACE_OF_CARE_IEN)
	WITH 			FILLFACTOR = 100
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_MCP_REFERRAL_REFERRAL_DATE_TIME')
		DROP INDEX MCP_REFERRAL.IX_MCP_REFERRAL_REFERRAL_DATE_TIME
		                                                                
	CREATE INDEX 	IX_MCP_REFERRAL_REFERRAL_DATE_TIME
	ON 			MCP_REFERRAL(REFERRAL_DATE_TIME)
	WITH 			FILLFACTOR = 100
