CREATE PROCEDURE [dbo].[upCreateIndexes_PDTS_PROFILE_COLLECTION_FILE] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_PDTS_PROFILE_COLLECTION_FILE')
		DROP INDEX PDTS_PROFILE_COLLECTION_FILE.ind_PDTS_PROFILE_COLLECTION_FILE
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PDTS_PROFILE_COLLECTION_FILE_KEY_PDTS_PROFILE_COLLECTION_FILE')
		DROP INDEX PDTS_PROFILE_COLLECTION_FILE.IX_PDTS_PROFILE_COLLECTION_FILE_KEY_PDTS_PROFILE_COLLECTION_FILE
		                                                                
	CREATE INDEX 	IX_PDTS_PROFILE_COLLECTION_FILE_KEY_PDTS_PROFILE_COLLECTION_FILE
	ON 			PDTS_PROFILE_COLLECTION_FILE(KEY_PDTS_PROFILE_COLLECTION_FILE)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PDTS_PROFILE_COLLECTION_FILE_REQUESTED_DATE_FILLED')
		DROP INDEX PDTS_PROFILE_COLLECTION_FILE.IX_PDTS_PROFILE_COLLECTION_FILE_REQUESTED_DATE_FILLED
		                                                                
	CREATE CLUSTERED INDEX 	IX_PDTS_PROFILE_COLLECTION_FILE_REQUESTED_DATE_FILLED
	ON 			PDTS_PROFILE_COLLECTION_FILE(REQUESTED_DATE_FILLED)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PDTS_PROFILE_COLLECTION_FILE_PATIENT_IEN')
		DROP INDEX PDTS_PROFILE_COLLECTION_FILE.IX_PDTS_PROFILE_COLLECTION_FILE_PATIENT_IEN
		                                                                
	CREATE  INDEX 	IX_PDTS_PROFILE_COLLECTION_FILE_PATIENT_IEN
	ON 			PDTS_PROFILE_COLLECTION_FILE(PATIENT_IEN)
	WITH 			FILLFACTOR = 100
