CREATE PROCEDURE [dbo].[upCreateIndexes_LAB_TEST] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_LAB_TEST')
		DROP INDEX LAB_TEST.ind_LAB_TEST
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_LAB_TEST_KEY_LAB_TEST')
		DROP INDEX LAB_TEST.IX_LAB_TEST_KEY_LAB_TEST
		
	CREATE INDEX 	IX_LAB_TEST_KEY_LAB_TEST
	ON 			LAB_TEST(KEY_LAB_TEST)
	WITH 			FILLFACTOR = 100
