CREATE PROCEDURE [dbo].[upCreateIndexes_WARD_LOCATION$ROOM] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_WARD_LOCATION$ROOM')
	DROP INDEX WARD_LOCATION$ROOM.ind_WARD_LOCATION$ROOM
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_WARD_LOCATION$ROOM_KEY_WARD_LOCATION$ROOM')
	DROP INDEX WARD_LOCATION$ROOM.IX_WARD_LOCATION$ROOM_KEY_WARD_LOCATION$ROOM

	CREATE INDEX IX_WARD_LOCATION$ROOM_KEY_WARD_LOCATION$ROOM
	ON WARD_LOCATION$ROOM(KEY_WARD_LOCATION$ROOM)
	WITH		FILLFACTOR = 100
