CREATE PROCEDURE [dbo].[upCreateIndexes_PRESCRIPTION$FILL_DATES] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_PRESCRIPTION$FILL_DATES')
		DROP INDEX PRESCRIPTION$FILL_DATES.ind_PRESCRIPTION$FILL_DATES

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION$FILL_DATES')
		DROP INDEX PRESCRIPTION$FILL_DATES.IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION$FILL_DATES	
	CREATE INDEX 	IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION$FILL_DATES
	ON 			PRESCRIPTION$FILL_DATES(KEY_PRESCRIPTION$FILL_DATES)
	WITH 			FILLFACTOR = 100
	
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRESCRIPTION$FILL_DATES_FILL_DATES')
		DROP INDEX PRESCRIPTION$FILL_DATES.IX_PRESCRIPTION$FILL_DATES_FILL_DATES				
	CREATE CLUSTERED INDEX 	IX_PRESCRIPTION$FILL_DATES_FILL_DATES
	ON 			PRESCRIPTION$FILL_DATES(FILL_DATES)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION')
		DROP INDEX PRESCRIPTION$FILL_DATES.IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION				
	CREATE INDEX 	IX_PRESCRIPTION$FILL_DATES_KEY_PRESCRIPTION
	ON 			PRESCRIPTION$FILL_DATES(KEY_PRESCRIPTION)
	WITH 			FILLFACTOR = 100
