CREATE PROCEDURE [dbo].[upCreateIndexes_PRESCRIPTION_ACTIVITY_LOG] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_PRESCRIPTION$ACTIVITY_LOG')
		DROP INDEX PRESCRIPTION$ACTIVITY_LOG.ind_PRESCRIPTION$ACTIVITY_LOG

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRESCRIPTION$ACTIVITY_LOG_KEY_PRESCRIPTION')
		DROP INDEX PRESCRIPTION$ACTIVITY_LOG.IX_PRESCRIPTION$ACTIVITY_LOG_KEY_PRESCRIPTION				
	CREATE INDEX 	IX_PRESCRIPTION$ACTIVITY_LOG_KEY_PRESCRIPTION
	ON 			PRESCRIPTION$ACTIVITY_LOG(KEY_PRESCRIPTION)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRESCRIPTION$ACTIVITY_lOG_KEY_PRESCRIPTION$ACTIVITY_LOG')
		DROP INDEX PRESCRIPTION$ACTIVITY_LOG.IX_PRESCRIPTION$ACTIVITY_lOG_KEY_PRESCRIPTION$ACTIVITY_LOG				
	CREATE clustered INDEX 	IX_PRESCRIPTION$ACTIVITY_lOG_KEY_PRESCRIPTION$ACTIVITY_LOG
	ON 			PRESCRIPTION$ACTIVITY_LOG(KEY_PRESCRIPTION$ACTIVITY_LOG)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_PRESCRIPTION$ACTIVITY_LOG_REASON_CODE_IEN')
		DROP INDEX PRESCRIPTION$ACTIVITY_LOG.IX_PRESCRIPTION$ACTIVITY_LOG_REASON_CODE_IEN
	CREATE INDEX 	IX_PRESCRIPTION$ACTIVITY_LOG_REASON_CODE_IEN
	ON 			PRESCRIPTION$ACTIVITY_LOG(REASON_CODE_IEN)
	WITH 			FILLFACTOR = 100
