CREATE PROCEDURE [dbo].[upCreateIndexes_MCP_REFERRAL$APPOINTMENTS] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IND_MCP_REFERRAL$APPOINTMENTS')
		DROP INDEX MCP_REFERRAL$APPOINTMENTS.ind_MCP_REFERRAL$APPOINTMENTS

	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME ='IX_MCP_REFERRAL$APPOINTMENTS_KEY_MCP_REFERRAL$APPOINTMENTS')
		DROP INDEX MCP_REFERRAL$APPOINTMENTS.IX_MCP_REFERRAL$APPOINTMENTS_KEY_MCP_REFERRAL$APPOINTMENTS

	CREATE INDEX IX_MCP_REFERRAL$APPOINTMENTS_KEY_MCP_REFERRAL$APPOINTMENTS
	ON			MCP_REFERRAL$APPOINTMENTS(KEY_MCP_REFERRAL$APPOINTMENTS)
	WITH			FILLFACTOR = 100
