CREATE PROCEDURE [dbo].[upCreateIndexes_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS')
		DROP INDEX ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS.ind_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS_KEY_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS')
		DROP INDEX ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS.IX_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS_KEY_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS
		                                                                
	CREATE INDEX 	IX_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS_KEY_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS
	ON 			ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS(KEY_ENCOUNTER$ICD_OPERATIONS_PR$ASSISTING_HCPS)
	WITH 			FILLFACTOR = 100
