CREATE PROCEDURE [dbo].[upCreateIndexes_PATIENT_CATEGORY] AS
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'ind_PATIENT_CATEGORY')
	DROP INDEX PATIENT_CATEGORY.ind_PATIENT_CATEGORY
	
	IF EXISTS (SELECT NAME FROM SYSINDEXES WHERE NAME = 'IX_PATIENT_CATEGORY_KEY_PATIENT_CATEGORY')
	DROP INDEX	PATIENT_CATEGORY.IX_PATIENT_CATEGORY_KEY_PATIENT_CATEGORY
	
	CREATE INDEX IX_PATIENT_CATEGORY_KEY_PATIENT_CATEGORY
	ON PATIENT_CATEGORY(KEY_PATIENT_CATEGORY)
	WITH		FILLFACTOR = 100
