CREATE PROCEDURE [dbo].[upCreateIndexes_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS] AS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'ind_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS')
		DROP INDEX SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS.ind_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL')
		DROP INDEX SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS.IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL
		
	CREATE INDEX 	IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL
	ON 			SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS(KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL)
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY')
		DROP INDEX SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS.IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY				
				                               
	CREATE INDEX	 	IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY
	ON 			SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS(KEY_SCHEDULABLE_ENTITY)
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES')
		DROP INDEX SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS.IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES								
	CREATE INDEX 	IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES
	ON 			SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS(KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES)
	WITH 			FILLFACTOR = 100
	IF EXISTS(SELECT name FROM sysindexes WHERE name = 'IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_MULTIKEYS')
		DROP INDEX SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS.IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_MULTIKEYS								
	CREATE CLUSTERED INDEX 	IX_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS_MULTIKEYS
	ON 			SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SLOTS(KEY_SCHEDULABLE_ENTITY,KEY_SCHEDULABLE_ENTITY$SCHEDULE_DATE_TIMES,KEY_SCHEDULABLE_ENT$SCHEDULE_DATE_T$APPOINTMENT_SL)
	WITH 			FILLFACTOR = 100
