CREATE PROCEDURE [dbo].[upCreateIndexes_CLINICAL_HISTORY] AS
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ind_CLINICAL_HISTORY')
		DROP INDEX CLINICAL_HISTORY.ind_CLINICAL_HISTORY
                                                                
	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_CLINICAL_HISTORY_KEY_CLINICAL_HISTORY')
		DROP INDEX CLINICAL_HISTORY.IX_CLINICAL_HISTORY_KEY_CLINICAL_HISTORY
		                                                                
	CREATE INDEX 	IX_CLINICAL_HISTORY_KEY_CLINICAL_HISTORY
	ON 			CLINICAL_HISTORY(KEY_CLINICAL_HISTORY)
	WITH 			FILLFACTOR = 100

	IF EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_CLINICAL_HISTORY_NAME_IEN')
		DROP INDEX CLINICAL_HISTORY.IX_CLINICAL_HISTORY_NAME_IEN
		                                                                
	CREATE INDEX 	IX_CLINICAL_HISTORY_NAME_IEN
	ON 			CLINICAL_HISTORY(NAME_IEN)
	WITH 			FILLFACTOR = 100
