CREATE PROCEDURE [dbo].[upSTG_PROVIDER_ACTIVITY]
AS
	
DECLARE @exists int

DECLARE @pro numeric(12,4)

EXEC dbo.upActivityLog 'Begin STG Provider Activity',0;

TRUNCATE TABLE STG_PROVIDER_ACTIVITY;

DECLARE curSTGPro CURSOR FAST_FORWARD FOR
SELECT	SURGEON_IEN AS PROVIDER_IEN
FROM	ENCOUNTER$ICD_OPERATIONS_PROCEDURES
WHERE	(DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, GETDATE()))) AND (SURGEON_IEN IS NOT NULL)
AND		SURGEON_IEN IS NOT NULL
UNION
SELECT	ANESTHESIOLOGIST_IEN AS PROVIDER_IEN
FROM	ENCOUNTER$ICD_OPERATIONS_PROCEDURES
WHERE	(DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, GETDATE()))) AND (ANESTHESIOLOGIST_IEN IS NOT NULL)
AND		ANESTHESIOLOGIST_IEN IS NOT NULL
UNION
SELECT	ORDERING_HCP_IEN AS PROVIDER_IEN
FROM	ORDER_
WHERE	ORDER_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
AND		ORDERING_HCP_IEN IS NOT NULL
UNION
SELECT	PROVIDER_IEN AS PROVIDER_IEN
FROM	PATIENT_APPOINTMENT
WHERE	APPOINTMENT_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
AND		PROVIDER_IEN IS NOT NULL
UNION
SELECT	PROVIDER_IEN
FROM	ENCOUNTER
WHERE	DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
AND		PROVIDER_IEN IS NOT NULL
UNION
SELECT	PRO.KEY_PROVIDER AS PROVIDER_IEN
FROM	USER_ USR INNER JOIN
		PROVIDER PRO 
		ON USR.PROVIDER_IEN = PRO.KEY_PROVIDER
WHERE	(USR.TERMINATION_DATE IS NULL) 
		OR (USR.TERMINATION_DATE > dbo.StartOfDay(GETDATE()))
		AND PRO.KEY_PROVIDER IS NOT NULL
UNION
SELECT	PROVIDER_IEN
FROM	PRESCRIPTION
WHERE	LAST_FILL_DATE >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
AND		PROVIDER_IEN IS NOT NULL
UNION
SELECT	REFERRED_TO_PROVIDER_IEN
FROM	MCP_REFERRAL
WHERE	REFERRAL_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
AND		REFERRED_TO_PROVIDER_IEN IS NOT NULL
UNION
SELECT	REFERRED_BY_IEN
FROM	MCP_REFERRAL
WHERE	REFERRAL_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
AND		REFERRED_BY_IEN IS NOT NULL
UNION 
SELECT	REVIEWER_IEN
FROM	MCP_REFERRAL$APPOINTMENT_REQUEST_REVIEW
WHERE	REVIEW_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
AND		REVIEWER_IEN IS NOT NULL

OPEN curSTGPro

EXEC dbo.upActivityLog 'Fetch STG Provider Activity',0
FETCH NEXT FROM curSTGPro INTO @pro

if(@@FETCH_STATUS = 0)
BEGIN

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		BEGIN TRANSACTION

			INSERT INTO STG_PROVIDER_ACTIVITY
			(
			Provider_Ien
			)
			VALUES
			(@pro);
	
		FETCH NEXT FROM curSTGPro INTO @pro

		COMMIT
	END

END
CLOSE curSTGPro
DEALLOCATE curSTGPro


EXEC dbo.upActivityLog 'End STG Provider Activity',0;
