create PROCEDURE [dbo].[upSTG_PATIENT_PROVIDER]
AS
	
	--DECLARE @exists int

	--DECLARE @pat numeric(13,3)
	--DECLARE @pro numeric(21,3)
	--DECLARE @pdate varchar(10)
	--DECLARE @dmis numeric(21,3)
	--DECLARE @max numeric(17,3)
	--DECLARE @pcm numeric(17,3)
	--DECLARE

EXEC dbo.upActivityLog 'Begin STG Patient Provider',0;

TRUNCATE TABLE STG_PATIENT_PROVIDER;

--DECLARE curSTGMaxEnr CURSOR FAST_FORWARD FOR
INSERT INTO STG_PATIENT_PROVIDER
(
	KEY_NED_PATIENT,
	PCM_IEN,
	PCM_PROJECTED_END_DATE,
	DMIS_ID_IEN,
	MaxEnr,
	MaxPcm,
	HCDP_CONTRACTOR_COVERAGE_CODE_IEN,
	BENEFICIARY_CATEGORY_IEN
)
SELECT DISTINCT 
	MPCM.KEY_NED_PATIENT, 
	PCM.PCM_IEN, 
	PCM.PCM_PROJECTED_END_DATE, 
	ENR.DMIS_ID_IEN, 
	MPCM.MaxEnr, 
    MPCM.MaxPcm, 
	ENR.HCDP_CONTRACTOR_COVERAGE_CODE_IEN, 
	PCM.BENEFICIARY_CATEGORY_IEN
FROM
	dbo.stg_Max_Pcm AS MPCM 
	INNER JOIN dbo.NED_PATIENT$ENROLLMENT_HISTORY AS ENR 
	ON MPCM.KEY_NED_PATIENT = ENR.KEY_NED_PATIENT 
	AND MPCM.MaxEnr = ENR.KEY_NED_PATIENT$ENROLLMENT_HISTORY 
	INNER JOIN NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY AS PCM 
	ON MPCM.KEY_NED_PATIENT = PCM.KEY_NED_PATIENT 
	AND MPCM.MaxPcm = PCM.KEY_NED_PATIENT$ENROLLMENT_HISTORY$PCM_HISTORY 
	AND MPCM.MaxEnr = PCM.KEY_NED_PATIENT$ENROLLMENT_HISTORY
ORDER BY MPCM.KEY_NED_PATIENT

--OPEN curSTGPat

EXEC dbo.upActivityLog 'End STG Patient Provider',0

/*FETCH NEXT FROM curSTGPat INTO @pat

if(@@FETCH_STATUS = 0)
BEGIN

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		BEGIN TRANSACTION

			INSERT INTO STG_PATIENT_ACTIVITY
			(
			Patient_Ien
			)
			VALUES
			(@pat);
	
		FETCH NEXT FROM curSTGPat INTO @pat

		COMMIT
	END

END
CLOSE curSTGPat
DEALLOCATE curSTGPat


EXEC dbo.upActivityLog 'End STG Patient Activity',0;

*/
