CREATE PROCEDURE [dbo].[upSTG_PATIENT_ACTIVITY]
AS
	
	DECLARE @exists int

	DECLARE @pat numeric(21,3)

EXEC dbo.upActivityLog 'Begin STG Patient Activity',0;

TRUNCATE TABLE STG_PATIENT_ACTIVITY;

DECLARE curSTGPat CURSOR FAST_FORWARD FOR
SELECT	PATIENT_IEN
FROM	ORDER_
WHERE	ORDER_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
UNION
SELECT	NAME_IEN AS PATIENT_IEN
FROM	PATIENT_APPOINTMENT
WHERE	APPOINTMENT_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
UNION
SELECT	PATIENT_IEN
FROM	ENCOUNTER
WHERE	DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
UNION
SELECT	PATIENT_IEN
FROM	PRESCRIPTION
WHERE	EXPIRATION_DATE >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
UNION
SELECT	PATIENT_IEN
FROM	MCP_REFERRAL
WHERE	REFERRAL_DATE_TIME >= dbo.StartOfDay(DATEADD(d, - 100, getdate()))
UNION
SELECT	PDTS.PATIENT_IEN AS PATIENT_IEN
FROM    PDTS_PROFILE_COLLECTION_F$ACCEPTED_RESPONSE_DETAIL AS PDTSACC 
		INNER JOIN PDTS_PROFILE_COLLECTION_FILE AS PDTS 
		ON PDTSACC.KEY_PDTS_PROFILE_COLLECTION_FILE = PDTS.KEY_PDTS_PROFILE_COLLECTION_FILE
WHERE	PDTSACC.ACCEPTED_DATE_FILLED >= dbo.StartOfDay(DATEADD(d, - 20, getdate())) 
		OR PDTS.REQUESTED_DATE_FILLED >= dbo.StartOfDay(DATEADD(d, - 20, getdate()))
UNION
SELECT	PAT.KEY_PATIENT AS PATIENT_IEN
FROM	dbo.PATIENT AS PAT 
		INNER JOIN dbo.POP_HEALTH_ASTHMA AS ASTH 
		ON PAT.DOD_ID_# = ASTH.EDIPN
UNION
SELECT	PAT.KEY_PATIENT AS PATIENT_IEN
FROM	dbo.PATIENT AS PAT 
		INNER JOIN dbo.POP_HEALTH_CERVICAL AS CERV 
		ON PAT.DOD_ID_# = CERV.EDIPN
UNION
SELECT	PAT.KEY_PATIENT AS PATIENT_IEN
FROM	dbo.PATIENT AS PAT  
		INNER JOIN dbo.POP_HEALTH_COLON AS COLON 
		ON PAT.DOD_ID_# = COLON.EDIPN
UNION
SELECT	PAT.KEY_PATIENT AS PATIENT_IEN
FROM	dbo.PATIENT AS PAT 
		INNER JOIN dbo.POP_HEALTH_DIABETES AS DIAB 
		ON PAT.DOD_ID_# = DIAB.EDIPN
UNION
SELECT	PAT.KEY_PATIENT AS PATIENT_IEN
FROM	dbo.PATIENT AS PAT 
		INNER JOIN dbo.POP_HEALTH_MAMMOGRAPHY AS MAMMO 
		ON PAT.DOD_ID_# = MAMMO.EDIPN				
UNION
SELECT	PAT.KEY_PATIENT AS PATIENT_IEN
FROM	FAMILY_MEMBER_PREFIX AS FMP 
		INNER JOIN dbo.PATIENT AS PAT 
		ON FMP.KEY_FAMILY_MEMBER_PREFIX = PAT.FMP_IEN 
		INNER JOIN dbo.BMI 
		ON FMP.FMP = BMI.FMP AND PAT.SPONSOR_SSN = dbo.FormattedSSN(BMI.[Sponsor SSN])
UNION
SELECT	PAT.KEY_PATIENT AS PATIENT_IEN
FROM	FAMILY_MEMBER_PREFIX AS FMP 
		INNER JOIN dbo.PATIENT AS PAT 
		ON FMP.KEY_FAMILY_MEMBER_PREFIX = PAT.FMP_IEN 
		INNER JOIN dbo.SMOKING_CESSATION AS CESS 
		ON FMP.FMP = CESS.FMP AND PAT.SPONSOR_SSN = dbo.FormattedSSN(CESS.[Sponsor SSN])		
		

OPEN curSTGPat

EXEC dbo.upActivityLog 'Fetch STG Patient Activity',0
FETCH NEXT FROM curSTGPat INTO @pat

if(@@FETCH_STATUS = 0)
BEGIN

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		BEGIN TRANSACTION

			INSERT INTO STG_PATIENT_ACTIVITY
			(
			Patient_Ien
			)
			VALUES
			(@pat);
	
		FETCH NEXT FROM curSTGPat INTO @pat

		COMMIT
	END

END
CLOSE curSTGPat
DEALLOCATE curSTGPat


EXEC dbo.upActivityLog 'End STG Patient Activity',0;
